### ISSUE TITLE
DllImport with Microsoft.Data.SqlClient.SNI.dll doesn't work when running from a network share

### ISSUE THREAD

**Issue by Doomblaster** [dotnet/SqlClient#1086]
So as title says, I've published a standalone dotnet core (3.1.15) console application and put it on a network share. I've also tried upgrading to net5.0. Basically it fails when people are trying to run it directly from that network location. It fails with the following:
`System.DllNotFoundException: Dll was not found.
   at Microsoft.Data.SqlClient.SNINativeMethodWrapper.UnmanagedIsTokenRestricted(IntPtr token, Boolean& isRestricted)
   at Microsoft.Data.Win32NativeMethods.IsTokenRestrictedWrapper(IntPtr token)
   at Microsoft.Data.ProviderBase.DbConnectionPoolIdentity.GetCurrentNative()
   at Microsoft.Data.ProviderBase.DbConnectionPoolIdentity.GetCurrent()
   at Microsoft.Data.ProviderBase.DbConnectionPoolGroup.GetConnectionPool(DbConnectionFactory connectionFactory)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.GetConnectionPool(DbConnection owningObject, DbConnectionPoolGroup connectionPoolGroup)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource``1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource``1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource``1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource``1 retry, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.OpenAsync(CancellationToken cancellationToken)`

If they copy it to their local machine, it works without problems.

Just to test, I added a DllImport in my own code and called the same method to in a way force load the unmanaged dll, which got me one step further (and possibly 2 back), because then it started failing with:

`System.TypeInitializationException: The type initializer for 'Microsoft.Data.SqlClient.SqlAuthenticationProviderManager' threw an exception.
---> System.IO.FileLoadException: 
File name: 'System.Configuration.ConfigurationManager, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
at Microsoft.Data.SqlClient.SqlAuthenticationProviderManager..cctor()
--- End of inner exception stack trace ---
at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool)
at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
at Microsoft.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()`

Obviously it's related to being on a windows share, but I'm not sure if this is specific to Microsoft.Data.SqlClient or dotnet core itself, and if it's possible at all to actually fix it. Experienced the same issue with System.Data.SqlClient which tries to do some stuff with sni.dll.

Expectation:
Being able to run application from a network share

**Comment by ErikEJ** [comment]
Are you running from a UNC path or a mapped drive?

**Comment by Doomblaster** [comment]
> Are you running from a UNC path or a mapped drive?

I've tried both, doesn't make a difference

**Comment by Doomblaster** [comment]
okay...this is weird
When running exe from cmd it fails
When running exe from mapped folder in powershell it fails
When running exe from UNC path in powershell it fails

downloaded dotnet runtime 3.1.15 zip and unpacked it to C:\dotnet, then started doing various "C:\dotnet\dotnet.exe program.dll"
When running with dotnet runtime manually from mapped folder in cmd it fails
When running with dotnet runtime manually from mapped folder in powershell it fails
When running with dotnet runtime manually from UNC path in powershell it works

someone please explain!

**Comment by cheenamalhotra** [comment]
Hi @Doomblaster 

We don't do anything special for native DLLs in .NET Core. The .NET Core runtime takes care of gathering the runtime native artifacts from references and loading them as needed.

I would recommend opening issue with dotnet/runtime repository.

**Comment by Doomblaster** [comment]
> Hi @Doomblaster
> 
> We don't do anything special for native DLLs in .NET Core. The .NET Core runtime takes care of gathering the runtime native artifacts from references and loading them as needed.
> 
> I would recommend opening issue with dotnet/runtime repository.

I figured as much as well...but I also got the System.Configuration.ConfigurationManager which possibly (?) is related to you. Even though that probably is a sidetrack, and the fact that I really can't find a reference to the specific version in your source code, now you know that at least 😄

**Comment by cheenamalhotra** [comment]
@Doomblaster 

Have you tried with latest **v2.1.3**?

**Comment by Doomblaster** [comment]
> @Doomblaster
> 
> Have you tried with latest **v2.1.3**?

Yes.

**Comment by Doomblaster** [comment]
@cheenamalhotra 
FWIW in the 2.1.3 nuget package, the Microsoft.Data.SqlClient.dll in the /runtimes/win/lib/netcoreapp3.1 folder, it does depend on System.Configuration.ConfigurationManager v4.0.3.0 
![image](https://user-images.githubusercontent.com/1055547/120316514-cc88a400-c2dd-11eb-939d-3cf49063de8f.png)
This is the one that is published with my application, and if I try to add [managed networking](https://docs.microsoft.com/en-us/sql/connect/ado-net/appcontext-switches?view=sql-server-ver15#enabling-managed-networking-on-windows) it starts complaining about this file is missing. Shouldn't this really refer to System.Configuration.ConfigurationManager v4.7.0 which is the one that is actually published with the rest of my app.

**Comment by cheenamalhotra** [comment]
**v2.1.3** does depend on Configuration Manager v4.7.0 for .NET Core 3.1 

https://www.nuget.org/packages/Microsoft.Data.SqlClient/

**Comment by Doomblaster** [comment]
> **v2.1.3** does depend on Configuration Manager v4.7.0 for .NET Core 3.1
> 
> https://www.nuget.org/packages/Microsoft.Data.SqlClient/

That's just the manifest in the nuget saying that. 4.7.0 is also published, however, the Microsoft.Data.SqlClient.dll published is not depending on 4.7.0, but 4.0.3 as you can see from my screenshot. It is also defined as a netcoreapp2.1 and not a Netcoreapp3.1 dll as I would expect. All in all the building/packaging of the nuget seems a bit odd.

**Comment by cheenamalhotra** [comment]
**4.0.3.0** is assembly version and not NuGet package version.

You can compare this version to Configuration Manager DLL in v4.7.0 by manually downloading and exploring it.

**Comment by cheenamalhotra** [comment]
Hi @Doomblaster 

Is there anything else you need help with, or we will proceed to closing this issue in few days.

**Comment by cheenamalhotra** [comment]
Closing due to inactivity.
