### ISSUE TITLE
System.InvalidOperationException: 'Internal connection fatal error.'

### ISSUE THREAD

**Issue by figueiredorui** [dotnet/SqlClient#1116]
I'm looking for some help troubleshooting an issue that I'm having in one of my Development machines.

The following code is throwing a System.InvalidOperationException: 'Internal connection fatal error.'  when opening the connection.

```c#
using System;
using Microsoft.Data.SqlClient;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
			using (var connection = new SqlConnection("Server=localhost;Database=Test02;Trusted_Connection=True;"))
			{
				connection.Open();
				Console.WriteLine("Connected successfully.");
				Console.ReadKey(true);
			}
		}
    }
}
```
Here is the stach trace
```c#
 at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.CompleteLogin(Boolean enlistOK)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open()
   at ConsoleApp1.Program.Main(String[] args) in Program.cs:line 12
```

On the same machine, using the legacy library 'System.Data.SqlClient', the following code works fine
```c#
using System.Data.SqlClient;

namespace ConsoleApp2
{
    class Program
    {
        static void Main(string[] args)
        {
			using (var connection = new SqlConnection("Server=localhost;Database=Test02;Trusted_Connection=True;"))
			{
				connection.Open();
				Console.WriteLine("Connected successfully.");
				Console.ReadKey(true);
			}
		}
    }
}
```
I have tried a few things like:
Repair .NET 5
Repair SQL Server 2019 Developer
Repair VS2019 

Does anyone have suggestions that could help to understand the source of the issue?

Thanks

**Comment by ericsampson** [comment]
You could try running something like WireShark to capture the difference between the two cases at the TCP level, because there's probably not enough information in the stacktrace to help.

**Comment by johnnypham** [comment]
Hi @figueiredorui, what version of Microsoft.Data.SqlClient are you using? Is this a .NET Core or .NET Framework application? You can try [enabling event tracing](https://docs.microsoft.com/en-us/sql/connect/ado-net/enable-eventsource-tracing?view=sql-server-ver15) and posting the event log here.

**Comment by r-work** [comment]
Similar issue here, works fine with **2.1.3**

**Comment by cheenamalhotra** [comment]
Could you also try out the 3 preview versions of v3.0.0 to get the first version to contain this issue?

**Comment by r-work** [comment]
@cheenamalhotra preview 1 seems to be working. 2, 3 and stable are not working.

**Comment by johnnypham** [comment]
@figueiredorui @r-work can you provide as much details as you can about your client/server environment (version, platform, etc) so we can get a local repro to investigate this?

**Comment by figueiredorui** [comment]
I'm setting up a new development environment and installing the various tools/frameworks to find out which one makes my project fail running. So far so good ...

**Comment by fraserbooth** [comment]
I'm experiencing very similar with .NET Core 3.1 and Microsoft.Data.SqlClient 3.0.0:

```
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open()
   at Sites.ExecuteGet() in Sites.cs:line 33

```

I assume its relevant that this issue started for me when I was forced to apply the latest Windows Update (KB5003637). I'm working on Win 10 Pro with VS2019 (16.9.4).

...any thoughts on ways to investigate and resolve this?

**Comment by johnnypham** [comment]
>  .NET Core 3.1 and Microsoft.Data.SqlClient 3.0.0:
> Windows Update (KB5003637). Win 10 Pro with VS2019 (16.9.4).

I wasn't able to reproduce it with this same configuration. Can you confirm if the issue is present starting with 3.0.0-preview2?

**Comment by fraserbooth** [comment]
Hi @johnnypham,

Thank you for your reply. I've just enabled prerelease in NuGet, and installed 3.0.0-preview2.21106.5 which is exhibiting the same behaviour.

Is there any other information I can share so that your system can reproduce the same error? One of my colleagues updated his system to the same Window Update Version and is now also getting the same error while previously everything worked fine, so we have managed to reproduced this at least twice...

All the best,

Fraser

**Comment by johnnypham** [comment]
Can you try 3.0.0-preview1?

**Comment by fraserbooth** [comment]
Unfortunately exactly the same error message...

**Comment by cheenamalhotra** [comment]
> I assume its relevant that this issue started for me when I was forced to apply the latest Windows Update (KB5003637). I'm working on Win 10 Pro with VS2019 (16.9.4).

Hi @fraserbooth 

Your issue seems different that what is being discussed here from earlier customer. In your case it seems to be related to some sort of configuration issue or an environment related problem. Could you open a new ticket with all related information:
- SQL Server version
- Client OS version and enabled TLS protocols
- Connection string
- If possible a small repro to reproduce issue by running it.

**Comment by cheenamalhotra** [comment]
@figueiredorui 

Checking in, did you manage to create a repro to this issue?

**Comment by cheenamalhotra** [comment]
Closing due to inactivity and lack of repro.

**Comment by pjmolina** [comment]
Seems the same error:

**Comment by pjmolina** [comment]
**Update:** fixed on my side doing the following actions:

1. Replaced `System.Data.SqlServer` for `Microsoft.Data.SqlServer`
2. Installed additional **icu-libs** in my docker image and disabled Globalization Invariant setting as commented here [#220](https://github.com/dotnet/SqlClient/issues/220#issue-498595465)

```dockerfile
RUN apk add icu-libs
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
```

**Comment by DavoudEshtehari** [comment]
@pjmolina Thank you for the update.
Could you clarify step 1? Do you mean using `Microsoft.Data.SqlClient` instead of `System.Data.SqlClient`?

**Comment by pjmolina** [comment]
.

> @pjmolina Thank you for the update. Could you clarify step 1? Do you mean using `Microsoft.Data.SqlClient` instead of `System.Data.SqlClient`?

Exactly: replacing the library and then updating the references across the project.

**Comment by ad-akshay** [comment]
> pjmolina

Thank you! It works like a charm :)

**Comment by vovcacik** [comment]
I had the same issue with System SqlClient. After upgrading to Microsoft.Data.SqlClient it turned out the problem was with **invariant globalization**. Turning it off helped me with both System and Microsoft SqlClient. 

```
 <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings> 
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>
```

The moral is, you may get more useful error messages from Microsoft SqlClient than from the System one.
