### ISSUE TITLE
System.DllNotFoundException: Unable to load DLL 'Microsoft.Data.SqlClient.SNI.x64.dll' In very specific scenario

### ISSUE THREAD

**Issue by myurashchyk** [dotnet/SqlClient#1146]
### Describe the bug
Legacy WebService.asmx running under .Net Framework 4.6.2 with physical path configured in IIS to **network share** (not reproduced with local folder. Not reproduced with console app.)

Starting from version 2.x it is crashes with message System.DllNotFoundException: Unable to load DLL 'Microsoft.Data.SqlClient.SNI.x64.dll'

In 1.1 version of [SNINativeMethodWrapper.cs](https://github.com/dotnet/SqlClient/blob/1.1-servicing/src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/Interop/SNINativeMethodWrapper.cs) in static .ctor LoadLibrary was executed with correct path. In version 2.1 there is no call to LoadLibrary.
```
Exception message:
System.DllNotFoundException
  HResult=0x80131524
  Message=Unable to load DLL 'Microsoft.Data.SqlClient.SNI.x64.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
  Source=Microsoft.Data.SqlClient
  StackTrace:
   at Microsoft.Data.SqlClient.SNINativeManagedWrapperX64.UnmanagedIsTokenRestricted(IntPtr token, Boolean& isRestricted)
   at Microsoft.Data.Win32NativeMethods.IsTokenRestrictedWrapper(IntPtr token)
   at Microsoft.Data.ProviderBase.DbConnectionPoolIdentity.GetCurrent()
   at Microsoft.Data.ProviderBase.DbConnectionPoolGroup.GetConnectionPool(DbConnectionFactory connectionFactory)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.GetConnectionPool(DbConnection owningObject, DbConnectionPoolGroup connectionPoolGroup)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
```

### To reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
[System.Web.Services.WebService(Namespace:="http://tempuri.org//MyService")]
Public Class MyService: System.Web.Services.WebService

    [WebMethod()]
    public string foo() 
{
        var connection =  new Microsoft.Data.SqlClient.SqlConnection(connectionString);
        connection.Open();
        var command = connection.CreateCommand();
        command.CommandText = "select 5";
        return command.ExecuteScalar()?.ToString();
}
```

### Expected behavior
No exception is thrown. Connection to DB is working.

### Further technical details
Microsoft.Data.SqlClient version: 2.1.3
Microsoft.Data.SqlClient.SNI version: 2.1.1
.NET target: Framework 4.6.2
SQL Server version:  SQL Server 2019
Operating system:  Windows 10

**Additional context**

**Comment by David-Engel** [comment]
@myurashchyk From 1.x to 2.x, the dependency of SNI native binaries changed from the same filename being stored in subfolders (x64 and x86) relative to Microsoft.Data.SqlClient.dll to different filenames (Microsoft.Data.SqlClient.SNI.x64.dll and Microsoft.Data.SqlClient.SNI.x86.dll) stored in the same folder as Microsoft.Data.SqlClient.dll. Does your deployment have the new file structure? Did you verify that the files are actually deployed there for SqlClient to load?

I'm just wondering if this is a deployment issue, or an issue actually loading the DLLs from a network share.

**Comment by myurashchyk** [comment]
@David-Engel 
I created small project with a single method. If I map IIS to local folder, it works. If I map it to the same folder via network share, it fails.
Moreover I made additional check. I've copied following method from [SNINativeMethodWrapper.cs v 2.1](https://github.com/dotnet/SqlClient/blob/2.1-servicing/src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/Interop/SNINativeMethodWrapper.cs)
```c#

        private static uint SNIInitialize([In] IntPtr pmo)
        {
            return s_is64bitProcess ?
                SNINativeManagedWrapperX64.SNIInitialize(pmo) :
                SNINativeManagedWrapperX86.SNIInitialize(pmo);
        }
```
and call to it fails if running from network share without calling LoadLibrary. 
LoadLibrary fixes issue.
Microsoft.Data.SqlClient.X64.dll is copied to output folder.

**Comment by David-Engel** [comment]
@RustinAlexandru 

You might be trying to cross a trust boundary. If you are on .NET Framework, this app.config setting might help your app run from a network share:

https://learn.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/loadfromremotesources-element

**Comment by RustinAlexandru** [comment]
Thank you for the suggestion, tried that, but no luck, still getting the error.

System.DllNotFoundException: Unable to load DLL 'Microsoft.Data.SqlClient.SNI.x64.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Microsoft.Data.SqlClient.SNINativeManagedWrapperX64.UnmanagedIsTokenRestricted(IntPtr token, Boolean& isRestricted)
   at Microsoft.Data.Win32NativeMethods.IsTokenRestrictedWrapper(IntPtr token) in D:\a\_work\1\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\Interop\SNINativeMethodWrapper.cs:line 1442
   at Microsoft.Data.ProviderBase.DbConnectionPoolIdentity.GetCurrent() in D:\a\_work\1\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\ProviderBase\DbConnectionPoolIdentity.cs:line 115

Any other ideas we could be trying?

**Comment by RustinAlexandru** [comment]
For anyone else, having this issue, one workaround we did is just load the SNI dll ourselves, something like this:

`   [DllImport("kernel32.dll", SetLastError = true)]
   public static extern IntPtr LoadLibrary(string dllToLoad);

   static void LoadSNI()
   {
       var sniDll = solutionDirectory/ "bin" / "Microsoft.Data.SqlClient.SNI.x64.dll";  // where solutionDirectory is a network share path
       LoadLibrary(sniDll );
   }`
   
   Not great, but gets the job done, hopefully this issue gets some attention and will be fixed in later versions.
