### ISSUE TITLE
NullReference exception in Microsoft.Data.SqlClient.TdsParserStateObject.CheckSetResetConnectionState

### ISSUE THREAD

**Issue by SL-S-L** [dotnet/SqlClient#1160]
### Describe the bug
Since I migrated my api to use Microsoft.Data.SqlClient(v3.0.0) I still encounter NullReferenceException in the logs of my api.
The issue seems totally random.

Exception message:
Object reference not set to an instance of an object.
Stack trace:
"TargetSite":"Void CheckSetResetConnectionState(UInt32, Microsoft.Data.SqlClient.CallbackType)", 
"StackTrace":  
at Microsoft.Data.SqlClient.TdsParserStateObject.CheckSetResetConnectionState(UInt32 error, CallbackType callbackType) 
at Microsoft.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync() 
at Microsoft.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()  
at Microsoft.Data.SqlClient.TdsParserStateObject.TryPrepareBuffer()  
at Microsoft.Data.SqlClient.TdsParserStateObject.TryReadByte(Byte& value) 
at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
at Microsoft.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
at Microsoft.Data.SqlClient.TdsParser.ProcessAttention(TdsParserStateObject stateObj)  
at Microsoft.Data.SqlClient.TdsParser.ProcessPendingAck(TdsParserStateObject stateObj)
at Microsoft.Data.SqlClient.TdsParserStateObject.ResetCancelAndProcessAttention() 
at Microsoft.Data.SqlClient.TdsParserStateObject.CloseSession() 
at Microsoft.Data.SqlClient.SqlCommand.EndExecuteReaderAsync(IAsyncResult asyncResult)
at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)

### Expected behavior
No exception.

### Further technical details
Microsoft.Data.SqlClient version: v3.0.0
.NET target: Core 3.1
SQL Server version: SQL Server 2019
Operating system: Docker container

**Comment by cheenamalhotra** [comment]
Hi @SL-S-L 

Could you provide a repro to your issue?

**Comment by SL-S-L** [comment]
Hi @cheenamalhotra 

I can't provide a test repo now, and I will try to capture EventSource later.
and my code just like this:

using (var conn = new SqlConnection(ConnectionString))
                {
                    using (var cmd = new SqlCommand())
                    {
                        cmd.Connection = conn;
                        if (cmd.Connection.State != ConnectionState.Open)
                        {
                            await cmd.Connection.OpenAsync();
                        }

                        cmd.CommandText = "StoredProcedureName";
                        cmd.CommandType = CommandType.StoredProcedure;

                        SqlHelper.AddParameters("@Parameter1", SqlDbType.UniqueIdentifier, cmd, Parameter1);

                        return await cmd.ExecuteNonQueryAsync();
                    }
                }

**Comment by JRahnama** [comment]
@SL-S-L any update here?

I created a sample app based on what you mentioned above:
 ```
static async Task Main(string[] args)
        {
            string procName = "ProcTest";
            string tableName = "TestTable";

            AppContext.SetSwitch("Switch.Microsoft.Data.SqlClient.UseManagedNetworkingOnWindows", true);
            string creatTableQuery = $"IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'{tableName}') " +
                $"CREATE TABLE {tableName} (c1 uniqueidentifier)";

            string createProc = $"CREATE PROCEDURE [{procName}] @parameter1 uniqueidentifier " +
                $"As Insert into {tableName} (c1) values (@parameter1)";


            SqlConnectionStringBuilder builder = new()
            {
                DataSource = "localhost",
                InitialCatalog = <database name>,
                IntegratedSecurity = true
            };
            using SqlConnection conn = new(builder.ConnectionString);
            using SqlCommand cmd = new();
            cmd.Connection = conn;

            if (cmd.Connection.State != ConnectionState.Open)
            {
                await cmd.Connection.OpenAsync();
            }
            cmd.CommandText = "TestProc";
            cmd.CommandType = CommandType.StoredProcedure;
            SqlParameter param = new()
            {
                ParameterName = "@parameter1",
                SqlDbType = SqlDbType.UniqueIdentifier,
                Value = Guid.NewGuid()
            };
            cmd.Parameters.Add(param);
            await cmd.ExecuteNonQueryAsync();

            string testCommand = "SELECT * FROM TestTable10";
            cmd.CommandType = CommandType.Text;
            cmd.CommandText = testCommand;
            using var reader = cmd.ExecuteReader();
            while (reader.Read())
            {
                Console.WriteLine(reader.GetGuid(0));
            }
        }
    }
```

and no issue was detected either on Windows or Unix platforms.

**Comment by JRahnama** [comment]
Closing due to inactivity. Please feel free to reopen if the issue persists.
