### ISSUE TITLE
Tests: TvpMain should be split

### ISSUE THREAD

**Issue by Wraith2** [dotnet/SqlClient#1172]
[TvpTest](https://github.com/dotnet/SqlClient/blob/main/src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/ParameterTest/TvpTest.cs) is a large single complicated test. It's purpose isn't clear and debugging any failure within it is proving to be very difficult, first of all identifying the failure and then debugging through the bulk of working code to the site of the problem when there are thrown errors in expected situations.

This test should be broken up into smaller units if possible and those units given descriptive names so the failure reasons are readily understandable from the name.

**Comment by cheenamalhotra** [comment]
Hi @Wraith2 

I agree it's an old design that needs to be improved.
We've been wanting to do that too for a long time, we'll see if it can be prioritized sometime soon.

**Comment by Wraith2** [comment]
This currently fails on main:

```
[xUnit.net 00:07:46.24]     Microsoft.Data.SqlClient.ManualTesting.Tests.TvpTest.TestMain [FAIL]
[xUnit.net 00:07:46.24]       Assert.True() Failure
[xUnit.net 00:07:46.24]       Expected: True
[xUnit.net 00:07:46.24]       Actual:   False
[xUnit.net 00:07:46.24]       Stack Trace:
[xUnit.net 00:07:46.24]         E:\Programming\csharp7\SqlClient\src\Microsoft.Data.SqlClient\tests\ManualTests\SQL\ParameterTest\TvpTest.cs(53,0): at Microsoft.Data.SqlClient.ManualTesting.Tests.TvpTest.TestMain()
  Failed Microsoft.Data.SqlClient.ManualTesting.Tests.TvpTest.TestMain [5 s]
  Error Message:
   Assert.True() Failure
Expected: True
Actual:   False
  Stack Trace:
     at Microsoft.Data.SqlClient.ManualTesting.Tests.TvpTest.TestMain() in E:\Programming\csharp7\SqlClient\src\Microsoft.Data.SqlClient\tests\ManualTests\SQL\ParameterTest\TvpTest.cs:line 53
```

**Comment by JRahnama** [comment]
@Wraith2 I am going to start working on separating the tests today. A PR would be out soon I hope.

**Comment by Wraith2** [comment]
Good luck, I think you'll need it.
My purpose was to point out that any PR's blocked by this failure may not be causing real faults.
