### ISSUE TITLE
NullReferenceException in SqlBulkCopy.WriteToServerAsync

### ISSUE THREAD

**Issue by steven-musick** [dotnet/SqlClient#1195]
### Describe the bug
NullReferenceException thrown when calling WriteToServerAsync(datatable) inside a function and returning the task directly.

```
Exception message: Object reference not set to an instance of an object.
Stack trace:
at Microsoft.Data.SqlClient.SqlBulkCopy.CheckAndRaiseNotification()
   at Microsoft.Data.SqlClient.SqlBulkCopy.<>c__DisplayClass126_0.<CopyRowsAsync>b__0()
   at Microsoft.Data.SqlClient.AsyncHelper.<>c__DisplayClass3_0.<ContinueTask>b__0(Task tsk)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at SqlBulkCopyErrorRepro.Program.<Main>d__0.MoveNext() in C:\code\other\microsoft-data-sqlclient-sqlbulkcopy-nullref\SqlBulkCopyErrorRepro\Program.cs:line 31
```

### To reproduce
Minimal reproduction available here:
https://github.com/steven-musick/microsoft-data-sqlclient-sqlbulkcopy-nullref

Reproduced against both an AWS RDS sql server instance as well as Azure Sql Database, but could not reproduce with a local database, latency may be a factor here.

Includes both a function that works and one that does not. The only difference between the 2 functions is that one of them is specified as async, while the other returns the task directly (in either case, the function result it awaited in main).

### Expected behavior
Data is bulk inserted to the database.

### Further technical details
Microsoft.Data.SqlClient version: 3.0.0
.NET target: .NET 5
SQL Server version: SQL Server 2019
Operating system: Reproduced with both Windows 10 pro and Linux docker container.

**Comment by steven-musick** [comment]
Alright, found my issue, was just me being stupid.

By returning (without awaiting) inside a using statement, the using was ending before the function actually finished.
