### ISSUE TITLE
SqlClient doesn't honor "Connect Timeout=0"

### ISSUE THREAD

**Issue by JohnyL** [dotnet/SqlClient#125]
I'm using `Connect Timeout=0` setting to make SqlClient *not* throw exception because I have lengthy queries. However, it doesn't honor this setting. I get the following exception:

```
Unhandled Exception: Microsoft.Data.SqlClient.SqlException: Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception: The wait operation timed out.
   --- End of inner exception stack trace ---
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader()
   at ConsoleCore.Program.Main(String[] args) in D:\Projects\ConsoleCore\Program.cs:line 52
```

### Further technical details
Microsoft.Data.SqlClient version: 1.0.19128.1-Preview
.NET target: Core 3.0.100-preview6-012264
SQL Server version: SQL Server 2019 CTP 3.0
Operating system: Windows 10 x64 Home Build 1809

**Comment by mgravell** [comment]
Doesn't the connect timeout only impact `Open[Async]`? are you looking for `DbCommand.CommandTimeout`?

**Comment by JohnyL** [comment]
@mgravell It's a test console application. The SqlCommand.CommandTimeout was the solution (thanks!), but I wonder why it doesn't work for connection string?

**Comment by David-Engel** [comment]
@JohnyL Connect Timeout is not the same as CommandTimeout. There is no connection string option to adjust the default CommandTimeout.

**Comment by David-Engel** [comment]
@JohnyL Connect Timeout is not the same as CommandTimeout. There is no connection string option to adjust the default CommandTimeout.
