### ISSUE TITLE
SqlBulkCopy crashes instead of inserting default values with option KeepNulls off.

### ISSUE THREAD

**Issue by EamonNerbonne** [dotnet/SqlClient#1259]
### Describe the bug

When inserting records via SqlBulkCopy without the KeepNulls option enabled into a table with a non-nullable column with a default value constraint that is mapped to a C# property containing null values, SqlBulkCopy crashes. The [docs](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlbulkcopyoptions) say: *KeepNulls [...] When not specified, null values are replaced by default values where applicable.*

The following exception occurs.

```
Unhandled exception. System.InvalidOperationException: Column 'SomeValue' does not allow DBNull.Value.
   at Microsoft.Data.SqlClient.SqlBulkCopy.ConvertValue(Object value, _SqlMetaData metadata, Boolean isNull, Boolean& isSqlType, Boolean& coercedToDataFeed)
   at Microsoft.Data.SqlClient.SqlBulkCopy.ReadWriteColumnValueAsync(Int32 col)
   at Microsoft.Data.SqlClient.SqlBulkCopy.CopyColumnsAsync(Int32 col, TaskCompletionSource`1 source)
   at Microsoft.Data.SqlClient.SqlBulkCopy.CopyRowsAsync(Int32 rowsSoFar, Int32 totalRows, CancellationToken cts, TaskCompletionSource`1 source)
   at Microsoft.Data.SqlClient.SqlBulkCopy.CopyBatchesAsyncContinued(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts, TaskCompletionSource`1 source)
   at Microsoft.Data.SqlClient.SqlBulkCopy.CopyBatchesAsync(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts, TaskCompletionSource`1 source)
   at Microsoft.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestContinuedAsync(BulkCopySimpleResultSet internalResults, CancellationToken cts, TaskCompletionSource`1 source)
   at Microsoft.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestAsync(CancellationToken cts, TaskCompletionSource`1 source)
   at Microsoft.Data.SqlClient.SqlBulkCopy.WriteToServerInternalAsync(CancellationToken ctoken)
   at Microsoft.Data.SqlClient.SqlBulkCopy.WriteRowSourceToServerAsync(Int32 columnCount, CancellationToken ctoken)
   at Microsoft.Data.SqlClient.SqlBulkCopy.WriteToServer(DataTable table, DataRowState rowState)
   at Microsoft.Data.SqlClient.SqlBulkCopy.WriteToServer(DataTable table)
   at <Program>$.<Main>$(String[] args) in C:\Users\nerbonne.PCA2018\source\repos\SqlBulkCopyBug\SqlBulkCopyBug\Program.cs:line 27
```

### To reproduce

Single-file program:
```C#
using System;
using System.Data;
using System.Transactions;
using Microsoft.Data.SqlClient;

using var transaction = new CommittableTransaction();
var connectionString = Environment.GetEnvironmentVariable("CONNECTION_STRING") ??
                       @"Server = (localdb)\MSSQLLocalDB; Integrated Security = true";
using var connection = new SqlConnection(connectionString);
connection.Open();
connection.EnlistTransaction(transaction);

using var createTable = new SqlCommand
{
    Connection = connection,
    CommandText = @"create table Demo ( SomeValue int not null constraint SomeDefault default (1))"
};
createTable.ExecuteNonQuery();

using var bulkcopy = new SqlBulkCopy(connection) { DestinationTableName = "Demo" };
using var datatable = new DataTable();
datatable.Columns.Add("SomeInput", typeof(int));
datatable.Rows.Add(42);

datatable.Rows.Add(default(int?)); //works fine without this row

bulkcopy.WriteToServer(datatable); // crashes here

transaction.Rollback();
```

Project file:
```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="3.0.0" />
  </ItemGroup>

</Project>
```
### Expected behavior
The bulk copy completes without crash (i.e. the table contains 42 and 1 right thereafter)

### Further technical details
Microsoft.Data.SqlClient version: via nuget 3.0.0
.NET target: appears irrelevant, but repro runs on .net 5.0
SQL Server version: appears irrelevant, but this repro runs with sql server 2019 LocalDB
Operating system: appears irrelevant, but this repreo runs on Windows 10 21H1

**Additional context**
The crash also occurs for other overloads of WriteToServer and with various other SqlBulkCopyOptions, as long as KeepNulls is off and the column is non-nullable.  A possible workaround could be to mark the columns nullable, but this isn't always possible (e.g. for primary keys with `next value for` defaults), and even where possible, the impact on the data model isn't ideal.

**Comment by JRahnama** [comment]
@EamonNerbonne I will look into this and will update you soon.

Thanks.

**Comment by JRahnama** [comment]
@EamonNerbonne  as you have mentioned inserting a nullable variable to a `NOT NULL` column is not permitted.
If you change 
```csharp
datatable.Rows.Add(default(int?)); //works fine without this row
```
to 
```csharp
datatable.Rows.Add(default(int)); //works fine without this row
```
it should be working fine.

**Comment by EamonNerbonne** [comment]
However, that inserts the wrong value.

If I change the repro to this, perhaps its clearer: 

```C#
using System;
using System.Data;
using System.Transactions;
using Microsoft.Data.SqlClient;

using var transaction = new CommittableTransaction();
var connectionString = Environment.GetEnvironmentVariable("CONNECTION_STRING") ??
    @"Server = (localdb)\MSSQLLocalDB; Integrated Security = true";
using var connection = new SqlConnection(connectionString);
connection.Open();
connection.EnlistTransaction(transaction);

var colType = "int not null";
//var colType =  "int null"; //wrong datamodel; but does print "1"

var createTableSql = $"create table Demo ( SomeValue {colType} constraint SomeDefault default (1))";
using var createTable = new SqlCommand { Connection = connection, CommandText = createTableSql };
createTable.ExecuteNonQuery();

using var bulkcopy = new SqlBulkCopy(connection) { DestinationTableName = "Demo" };
using var datatable = new DataTable();
datatable.Columns.Add("SomeInput", typeof(int));
datatable.Rows.Add(default(int?));
//datatable.Rows.Add(default(int)); //alternative that does not throw but prints wrong output: "0"

bulkcopy.WriteToServer(datatable); // crashes here

var selectSql = @"select SomeValue from Demo";
using var selectValue = new SqlCommand { Connection = connection, CommandText = selectSql };
var insertedValue = (int)selectValue.ExecuteScalar();
Console.WriteLine(insertedValue);

transaction.Rollback();
```

To avoid the  crash there are two alternatives:

 - Using a nullable column for a non-nullable value allows for `KeepNulls` off to work as described in the docs, but nullable columns cannot be e.g. part of a primary key, an in any case it's a misleading datamodel which may have consequences on things like query plans.
 - inserting 0 does not crash, but that ignores the default value constraint; which kind of defeats the purpose.

The real-life usecase where this matters is to insert a non-stable value; i.e. for constraints that provide defaults like `sysdatetime()` or `next value for MySequence`.

**Comment by JRahnama** [comment]
I see. When the field in the database is set to `NOT NULL` and is defined as `DEFAULT CONSTRAINT ` there would be to possibilities:

1. Pass the value in this case the database will not pick the default value, if this is the case it can never set to `DBNull.Value`.
2. Do not pass the value to the database and the default will be picked up. This could be achieved either by defining 
               1.   Do not define the value in the data table you are passing to BulkCopy
               2. If the field is in the source define `ColumnMappings` collections, so that you can leave that field out.

In simpler words, such data should never be added to the source when database is set to `NOT NULL` and is defined as `DEFAULT CONSTRAINT `

**Comment by EamonNerbonne** [comment]
Yeah, there are workarounds (but nothing trivial), especially if data is partially default, and partially not.  The behavior the  [docs](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlbulkcopyoptions)  *seem* to imply would be ideal: *KeepNulls [...] When not specified, null values are replaced by default values where applicable.* - and that actually works, as long as the target is nullable.

**Comment by Wraith2** [comment]
The docs are talking about sql NULL and as far as I've seen there is no understanding of Nullable<T> in this library  because most of the code predates that capability. Just don't use nallables and make sure you use DBNull.Value where you might mean NULL.

**Comment by EamonNerbonne** [comment]
DBNull.Value has the same behavior as C# null, here. However, it sounds like the behaviour is by design? The docs don't make that clear, and it does not appear to be an sql-server limitation as the `bcp` utility does support non-KeepNulls behavior inserting mixed null/non-null input into a non-null target column with a default value.  

This is simple to try by following the bcp example: https://docs.microsoft.com/en-us/sql/relational-databases/import-export/keep-nulls-or-use-default-values-during-bulk-import-sql-server?view=sql-server-ver15#sample-table but using a non-nullable target column:

```SQL
CREATE DATABASE TestDatabase;
GO

USE TestDatabase;
CREATE TABLE dbo.myNulls ( 
   PersonID smallint not null,
   FirstName varchar(25),
   LastName varchar(30),
   Kids varchar(13) not null DEFAULT 'Default Value',
   BirthDate date
   );
```

with the provided sample content:
```
1,Anthony,Grosse,Yes,1980-02-23
2,Alica,Fatnowna,No,1963-11-14
3,Stella,Rosenhain,,1992-03-02
```

And then inserted from the command line:
```
bcp TestDatabase.dbo.myNulls IN C:\Temp\myNulls.bcp -c -t, -T
```
(you'll need to quote the `-t,` if you're using powershell).

The resulting data contains the value `Default Value` in the kids column corresponding to PersonID 3, even though the target column is non-nullable.

However, if this isn't practically feasible using `SqlBulkCopy`, perhaps it would help to at least clarify the limitation in the docs, e.g. saying something like: *When not specified, null values in the source are replaced by default values in the target when the target column has a default constraint and is nullable.*

**Comment by JRahnama** [comment]
@EamonNerbonne I am going to test this against other drivers to see if the behavior is different.

**Comment by kf-gonzalez2** [comment]
Closing this issue due to inactivity, feel free to open back if it still an issue

**Comment by mcgiany** [comment]
> Closing this issue due to inactivity, feel free to open back if it still an issue

What inactivity? We are waiting for the fix in the BulkCopy. This is still an issue in current version of SqlClient.
Neither not include column in source or set null value not working.

There is not possible option to bulky copy if there is NOT NULL column with default constraint in the table if we want to apply the default value.
Imagine case where default constraint is "NEXT VALUE FOR someSequence" in ID column of the table. Impossible.
