### ISSUE TITLE
SqlConnection.GetSchema() Throws Exception on UWP in release

### ISSUE THREAD

**Issue by eidon** [dotnet/SqlClient#132]
SqlConnection.GetSchema(System.Data.SqlClient.SqlClientMetaDataCollectionNames.Tables) generate "Value cannot be null. Parameter name: xmlStream" exception  on Microsoft.NETCore.UniversalWindowsPlatform 6.2.8

Stack Trace:
   at System.Data.ProviderBase.DbMetaDataFactory..ctor(Stream xmlStream, String serverVersion, String normalizedServerVersion)
   at System.Data.SqlClient.SqlConnectionFactory.CreateMetaDataFactory(DbConnectionInternal internalConnection, Boolean& cacheMetaDataFactory)
   at System.Data.ProviderBase.DbConnectionFactory.GetMetaDataFactory(DbConnectionPoolGroup connectionPoolGroup, DbConnectionInternal internalConnection)
   at System.Data.ProviderBase.DbConnectionInternal.GetSchema(DbConnectionFactory factory, DbConnectionPoolGroup poolGroup, DbConnection outerConnection, String collectionName, String[] restrictions)
   at System.Data.SqlClient.SqlConnection.GetSchema(String collectionName, String[] restrictionValues)
   at System.Data.SqlClient.SqlConnection.GetSchema(String collectionName)
   at AklauSimpleQueryUWP.Data.CrudSQL.GetSchemaTables(DataTable& pDataTable) in D:\Users\ricci\Documenti\Visual Studio 2019\Projects\Aklau_Simple_Query_UWP\Data\CrudSQL.cs:line 119

**Comment by cheenamalhotra** [comment]
Hi @divega

Can you provide us a repro for the issue?

**Comment by eidon** [comment]
> Hi @divega
> 
> Can you provide us a repro for the issue?

HI, 
i've the same problem of @tuggernuts reported at this link (with sample code):
https://github.com/dotnet/SqlClient/issues/46

My code is very simple:
internal bool GetSchemaTables(out DataTable pDataTable) {
            pDataTable = null;

            try {
                using (System.Data.SqlClient.SqlConnection objSqlConnection =
                        new System.Data.SqlClient.SqlConnection(new Data.CrudSQL(base.Server, base.Database, base.User, base.Password).cnnString(1))) {

                    objSqlConnection.Open();
                    pDataTable = objSqlConnection.GetSchema(System.Data.SqlClient.SqlClientMetaDataCollectionNames.Tables);

                    return true;
                }
            }
            catch (Exception ex) {
                base.Error = ex.Message;
                return false;
            }
        }

**Comment by cheenamalhotra** [comment]
Closing this as #46 already exists.
