### ISSUE TITLE
SqlAuthenticationParameters.ConnectionTimeout throws MissingMethodException

### ISSUE THREAD

**Issue by smichtch** [dotnet/SqlClient#1335]
### Describe the bug
`SqlAuthenticationParameters.ConnectionTimeout` throws `MissingMethodException`

```
System.MissingMethodException: Method not found: 'Int32 Microsoft.Data.SqlClient.SqlAuthenticationParameters.get_ConnectionTimeout()'.
   at Microsoft.Data.ProviderBase.DbConnectionPool.CheckPoolBlockingPeriod(Exception e)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open()
   at DatabaseTestController.TestSqlConnection(Action`1 customize)
```

### To reproduce
Reproduces by accessing `ConnectionTimeout` from a custom `SqlAuthenticationProvider`: 
```c#
class MyCustomSqlAuthenticationProvider : SqlAuthenticationProvider
{
    public override async Task<SqlAuthenticationToken> AcquireTokenAsync(SqlAuthenticationParameters parameters)
    {
        // System.MissingMethodException thrown here
        var connectionTimeout = parameters.ConnectionTimeout;
        ...
    }
    ...
}
```

### Expected behavior
`SqlAuthenticationParameters.ConnectionTimeout` returns an integer value.

### Further technical details
Microsoft.Data.SqlClient version: 3.0.1
.NET target: netcoreapp3.1 and net472
SQL Server version: N/A
Operating system: Windows 10 Enterprise Build 19043

**Additional context**
It looks like `SqlAuthenticationParameters.ConnectionTimeout` is implemented a a field
https://github.com/dotnet/SqlClient/blob/6c46392d7ae3b06daf9f87eada1b7d9f4494a1d4/src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlAuthenticationParameters.cs#L41

but in the ref assemblies it's a property:
https://github.com/dotnet/SqlClient/blob/6c46392d7ae3b06daf9f87eada1b7d9f4494a1d4/src/Microsoft.Data.SqlClient/netfx/ref/Microsoft.Data.SqlClient.cs#L152
https://github.com/dotnet/SqlClient/blob/6c46392d7ae3b06daf9f87eada1b7d9f4494a1d4/src/Microsoft.Data.SqlClient/netcore/ref/Microsoft.Data.SqlClient.cs#L196

Seems like it might just be a typo (i.e. impl missing a `{ get; }`) but since `SqlAuthenticationParameters` is marked `partial` maybe I'm not seeing some generated code.

**Comment by cheenamalhotra** [comment]
Hi @smichtch 

I'm leaning to agree it should have been a property, but strangely it works fine for our provider implementation.
https://github.com/dotnet/SqlClient/blob/4316474cdb6f3e09d0a9f10d70042215fa1fa74c/src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/ActiveDirectoryAuthenticationProvider.cs#L111

> but since SqlAuthenticationParameters is marked partial maybe I'm not seeing some generated code.

I think that is a left over keyword, the class is complete in ref project.

**Comment by smichtch** [comment]
@cheenamalhotra `ActiveDirectoryAuthenticationProvider` in Microsoft.Data.SqlClient is not looking at the ref assemblies, it's getting the field from the implementation class directly:
![image](https://user-images.githubusercontent.com/15808774/137033620-87436b0f-14b4-495e-98d3-713b530847ef.png)

**Comment by cheenamalhotra** [comment]
Yes, I just tried in standalone and found this issue as well.

I've opened PR https://github.com/dotnet/SqlClient/pull/1336 to address this, below package is built with this change, please try and let me know.

Add to local feed: [Microsoft.Data.SqlClient.4.0.0-dev.nupkg.zip](https://github.com/dotnet/SqlClient/files/7333333/Microsoft.Data.SqlClient.4.0.0-dev.nupkg.zip)
`<PackageReference Include="Microsoft.Data.SqlClient" Version="4.0.0-dev" />`

Thanks for catching this bug 👍🏻
