### ISSUE TITLE
[Bug] MSI is not working in net core 2.2 Web App

### ISSUE THREAD

**Issue by IdeaHunter** [dotnet/SqlClient#138]
### Describe the bug
Unable to use MSI on net core 2.2 windows web app. 
i have tried to follow tutorial on setting up MSI to access data in Azure SQL Server Database
First, i created app service and assigned system managed identity
![app-service](https://user-images.githubusercontent.com/10799080/61153113-e571eb80-a4f2-11e9-9205-8e026fd0d999.png)
Second i have created Azure AD Group and added  system managed identity to a group
![sql group](https://user-images.githubusercontent.com/10799080/61153140-02a6ba00-a4f3-11e9-9916-e8d1eebf5a9c.png)
Then  i connected to azure database right way(tm) and added Azure AD Group and granted it admin rights db_datareader db_datawriter db_ddladmin
![sql users](https://user-images.githubusercontent.com/10799080/61153532-30403300-a4f4-11e9-8442-d627c25cdce9.png)
Then i took a connection string from azure admin panel and modified it to be usable for MSI(see code below)

Then i tried to run code and it seems like it produces valid jwt token(checked under debugger)
![access token](https://user-images.githubusercontent.com/10799080/61153509-20285380-a4f4-11e9-8520-2a45cafcb74d.png)
The code giving me following problem
```
Exception message: 
Login failed for user 'NT AUTHORITY\ANONYMOUS LOGON'.
Stack trace:
at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at GraphQL.WebApi.Startup.<>c.<ConfigureServices>b__4_7(IServiceProvider serviceProvider) 
```

### To reproduce
```c# 
var provider = new AzureServiceTokenProvider();
var token = provider.GetAccessTokenAsync("https://database.windows.net/", "xxxxxxxxx.onmicrosoft.com").Result;
 var sqlConnection = new SqlConnection("Data Source=xxxxx.database.windows.net;Initial Catalog=testing");
sqlConnection.AccessToken = token;
sqlConnection.Open()
```
And when i execute following command
```sql
use master;
SELECT *
FROM sys.event_log
where event_type = 'connection_failed'
```
on sql server im getting following result
```
testing	2019-07-12 18:30:00.0000000	2019-07-12 18:35:00.0000000	connectivity	connection_failed	4	login_failed_for_user	2	2	Login failed for user.
```
### Expected behavior
I should be able to open sql connection with this setup, but i dont 

### Further technical details
Microsoft.Data.SqlClient version: (4.6.1)
Microsoft.Azure.Services.AppAuthentication version: (1.2.0)
.NET target: (Core 2.2.4)
SQL Server version: (Azure SQL)
Operating system: (Azure Managed, no idea)

**Additional context**
Im have an app that can connect to multiple databases and i need MSI to dont share username/password and make app more secure and manageable

**Comment by cheenamalhotra** [comment]
Hi @IdeaHunter 

I'm not sure of `AzureServiceTokenProvider` is the correct way to acquire Managed Identity token. Please refer Microsoft documentation here on how to do the same: [Get a token using C#](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-token#get-a-token-using-c)

Also, you can try this sample app ([msi-netcore-sample](https://github.com/cheenamalhotra/msi-netcore-sample)) that has been tested and works with **Microsoft.Data.SqlClient** - latest preview version.

**Comment by IdeaHunter** [comment]
Hi @cheenamalhotra 
Thanks for help!

I Tried this code on App Service and got exception:
>An attempt was made to access a socket in a way forbidden by its access permissions

However i when i tried code just for testing on a vm - it was working. 
Im digging in and trying to find what may have caused it

**Comment by cheenamalhotra** [comment]
Hi @IdeaHunter 

Yes I just recalled, on app service/functions you'd have to modify the API to use MSI_ENDPOINT environment variable as host and pass MSI_SECRET to HTTP Request. App Service/Function Apps still use the old version of API. You can look at this document for more info: https://docs.microsoft.com/en-us/azure/app-service/overview-managed-identity

I will update my sample to also connect universally. I somehow was focusing only on Azure VM.

**Comment by cheenamalhotra** [comment]
Hi @IdeaHunter 

I've updated the Console App to add functionality to fetch tokens on App Service/Function.
Also, I created a new ASP.NET Sample App for deploying directly on Azure App Service: [cheenamalhotra/msi-netcore-web-sample](https://github.com/cheenamalhotra/msi-netcore-web-sample).

Everything works with Microsoft.Data.SqlClient. Let us know if you have any further questions.

**Comment by IdeaHunter** [comment]
@cheenamalhotra Thanks a lot for help!
I can confirm that code provided works fine for a AppService and SqlClient works as expected!

The thing that doesnt work with same configuration is Microsoft.Azure.Services.AppAuthentication
Can we please move this ticket to https://github.com/Azure/azure-sdk-for-net ?

**Comment by David-Engel** [comment]
@IdeaHunter We don't have access to transfer issues to other GitHub repositories. You'll need to file the issue there yourself.
