### ISSUE TITLE
Service principal auth - "Login failed for user '<token-identified principal>"

### ISSUE THREAD

**Issue by andrei-faber** [dotnet/SqlClient#1408]
### Describe the bug
When trying to use service principal authentication, always getting the following error: `Login failed for user '<token-identified principal>`

```
Microsoft.Data.SqlClient.SqlException (0x80131904): Login failed for user '<token-identified principal>'.
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.CompleteLogin(Boolean enlistOK)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open()
   at AzureStorageTools.Program.TestSql1() in D:\Projects\AzureStorageTools\AzureStorageTools\Program.cs:line 129
   at AzureStorageTools.Program.Main(String[] args) in D:\Projects\AzureStorageTools\AzureStorageTools\Program.cs:line 35
ClientConnectionId:032ae7c2-1271-490d-806c-c6e5d49b3eca
Error Number:18456,State:1,Class:14
```

### To reproduce

```c#
var credential = new ClientSecretCredential(settings.TenantId, settings.ClientAppId, secret);

var connectionString = $"Server=tcp:{workspaceName}-ondemand.sql.azuresynapse.net,1433; Encrypt=True; " +
    "Database=master; Persist Security Info=False; MultipleActiveResultSets=False; TrustServerCertificate=True;";

using var connection = new SqlConnection(connectionString);
var token = credential.GetToken(new(new[] { "https://database.windows.net/.default", }), default).Token;
connection.AccessToken = token;
connection.Open(); // fails here
```
Same ClientSecretCredential object works no problem for accessing other resources (for instance Azure blob storage).

For comparison, this code works successfully:
```c#
var credential = new AzurePowerShellCredential();

var connectionString = $"Server=tcp:{workspaceName}-ondemand.sql.azuresynapse.net,1433; Encrypt=True; " +
    "Database=master; Persist Security Info=False; MultipleActiveResultSets=False; TrustServerCertificate=True;";

using var connection = new SqlConnection(connectionString);
var token = credential.GetToken(new(new[] { "https://database.windows.net/.default", }), default).Token;
connection.AccessToken = token;
connection.Open();
```

### Expected behavior
Authenticate.

### Further technical details
Microsoft.Data.SqlClient version: 4.0.0
.NET target: 5.0
SQL Server version: Azure Synapse SQL on demand pool
Operating system: Windows 11

**Comment by JRahnama** [comment]
@andrei-faber the issue seems not related to SqlClient probably a different setup has been provided for two different non-SqlClient functions `AzurePowerShellCredential` and `ClientSecretCredential`, but since MDS is using MSAL library to acquire token , System.Data.SqlClient is using native ADAL, I can suggest try below code to see if you can get connection.
Keep in mind the user secret needs to be [SecureString](https://docs.microsoft.com/en-us/dotnet/api/system.security.securestring?view=net-6.0). the code provided below is using `AcquireTokenByIntegratedWindowsAuth` this could be changed to any other configuration provided by the class.
```C#
	    string appId = <provide application id>;
            string scope = "https://database.windows.net//.default";
            string[] scopes = new string[] { scope };
            
            // Provide details here.
            string authority = "https://login.windows.net/<tenantId>";
            string server = "<server>.database.windows.net";
            string database = "";

            IPublicClientApplication pcApp = PublicClientApplicationBuilder.Create(appId)
                    .WithAuthority(authority)
                    .Build();
            try{
                AuthenticationResult result = pcApp.AcquireTokenByIntegratedWindowsAuth(scopes).ExecuteAsync().Result;
                Console.WriteLine("Access token acquired successfully from MSAL.");
                
                try{
                    SqlConnection connection = new SqlConnection($"Server={server}; Initial Catalog={database};");
                    connection.AccessToken = result.AccessToken;
                    connection.Open();
                    Console.WriteLine("Connected to Azure SQL successfully.");
                }
                catch(Exception e){
                    Console.WriteLine("Could not connect to SQL Server. Error occurred in SqlClient: " + e.Message);
                }
            }
            catch(Exception e){
                Console.WriteLine("Could not acquire access token. Error occurred in MSAL Library: " + e.Message);
            }
```

**Comment by andrei-faber** [comment]
@JRahnama it seems that IPublicClientApplication doesn't support service principal or managed identity.

**Comment by JRahnama** [comment]
@andrei-faber, the issue is probably happens due to wrong token generated, FYI, MDS (`Microsoft.Data.SqlClient`) is supporting that internally and you do not have to assign the token manually. the only thing you need to do is: 
`ConnectionString = @"Server=demo.database.windows.net; Authentication=Active Directory Service Principal; Database=testdb; User Id=AppId; Password=secret"; `

you can read more [here](https://docs.microsoft.com/en-us/sql/connect/ado-net/sql/azure-active-directory-authentication?view=sql-server-ver15#using-active-directory-service-principal-authentication).

**Comment by andrei-faber** [comment]
@JRahnama I already tried that, got same error.

And another strange thing that I noticed.
This code works fine when I login in PowerShell with my user account. But when I login in PowerShell using the service principal, it fails with the same exception ‘Login failed for user '<token-identified principal>”
```
 var credential = new AzurePowerShellCredential();

 var blobServiceClient = new BlobServiceClient(settings.StorageUrl, credential);
 var containers = blobServiceClient.GetBlobContainers().ToArray(); // succeeds in any auth mode

 var connectionString = $"Server=tcp:{workspaceName}-ondemand.sql.azuresynapse.net,1433; Encrypt=True; " +
        "Database=master; Persist Security Info=False; MultipleActiveResultSets=False; TrustServerCertificate=True;";

 using var connection = new SqlConnection(connectionString);
 var token = credential.GetToken(new(new[] { “https://database.windows.net/.default”, }), default).Token;
 connection.AccessToken = token;
 connection.Open(); // fails here - service principal auth only
```

**Comment by andrei-faber** [comment]
@DigiBanks99 in my particular case, it was necessary to execute this setup command to allow it access a storage account that the query relied upon:
```
CREATE CREDENTIAL [{StorageUrl}/{containerName}] WITH IDENTITY = '{ClientId}@[https://login.microsoftonline.com/{TenantId}/wsfed'](https://login.microsoftonline.com/%7BTenantId%7D/wsfed%27), SECRET = '{ClientSecret}'"
```
