### ISSUE TITLE
MARS on and pooling on throws quite a few exceptions in Debian 9

### ISSUE THREAD

**Issue by johnsimons** [dotnet/SqlClient#141]
### Describe the bug

Running with `MultipleActiveResultSets=True` it crashes the process in Debian 9
I have included some code below that reproduces the problem.

Once you run that code provided, after about 20 seconds it starts throwing:
```
System.Data.SqlClient.SqlException (0x80131904): Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception (258): Unknown error 258
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SqlClient.SqlCommand.ExecuteReader()
   at Program.DoSelect(SqlConnection connection) in /home/john/test/Program.cs:line 96
   at Program.<>c__DisplayClass1_0.<Main>b__2() in /home/john/test/Program.cs:line 65
ClientConnectionId:75adcf5a-46df-4d92-96ec-475eb9761cbc
Error Number:-2,State:0,Class:11
ClientConnectionId before routing:39fc66d8-f418-471f-b691-a2af8c6ab694
Routing Destination:f4c9c9048e30.tr1.australiacentral1-a.worker.database.windows.net,11072
```
And then after a minute or so it crashed the process with:
```
Unhandled Exception: System.AggregateException: One or more errors occurred. (Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.) (Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.) ---> System.InvalidOperationException: Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Program.<>c__DisplayClass1_0.<Main>b__2() in /home/john/test/Program.cs:line 61
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Program.Main(String[] args) in /home/john/test/Program.cs:line 48
Aborted
```

### To reproduce
Run the following snippet of code in a Debian 9 Azure VM.
You also need an Azure SQL database.

The connection string for an azure database should look something like:
`Server=tcp:xxxx.database.windows.net,1433;Initial Catalog=test;Persist Security Info=False;User ID={your_username};Password={your_password};MultipleActiveResultSets=True;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;`
Just be aware I modified the connection string to have `MultipleActiveResultSets=True`.

Snippet:
```c#
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Threading;
using System.Threading.Tasks;

class Program
{
    static volatile int connectionOpen = 0;
        
    static void Main(string[] args)
    {
        var cb = new SqlConnectionStringBuilder(args[0]);

        try
        {
            using (var connection = new SqlConnection(cb.ConnectionString))
            {
                connection.Open();

                CreateTable(connection);
            }
        }
        catch (SqlException e)
        {
            Console.WriteLine(e.ToString());
        }

        var stop = false;
        Console.CancelKeyPress += (sender, eventArgs) =>
        {
            Console.Out.WriteLine("Stopping....");
            eventArgs.Cancel = true;
            stop = true;
        };

        var rnd = new Random();
        
        var task = Task.Run(() =>
        {
            while (!stop)
            {
                Console.Out.WriteLine($"Connections open {connectionOpen}");
                Thread.Sleep(1000);
            }
        });

        while (!stop)
        {
            var tasks = new List<Task>();
            for (var i = 0; i < 300; i++)
            {
                tasks.Add(Task.Run(() =>
                {
                    var opened = false;
                    try
                    {
                        using (var connection = new SqlConnection(cb.ConnectionString))
                        {
                            connection.Open();
                            Interlocked.Increment(ref connectionOpen);
                            opened = true;

                            DoSelect(connection);
                            Thread.Sleep(rnd.Next(10, 500));
                        }
                    }
                    catch (SqlException e)
                    {
                        Console.WriteLine(e.ToString());
                    }
                    finally
                    {
                        if (opened)
                        {
                            Interlocked.Decrement(ref connectionOpen);
                        }
                    }
                }));
            }

            Task.WaitAll(tasks.ToArray());
        }

        task.Wait();

        Console.Out.WriteLine("Done");
    }

    static void DoSelect(SqlConnection connection)
    {
        var tsql = @"SELECT * FROM test;";

        using (var command = new SqlCommand(tsql, connection))
        {
            using (SqlDataReader reader = command.ExecuteReader())
            {
                while (reader.Read())
                {

                }
            }
        }
    }

    static void CreateTable(SqlConnection connection)
    {
        var tsql = @"
                DROP TABLE IF EXISTS test;
                CREATE TABLE test
                (
                    DepartmentCode  nchar(4)          not null    PRIMARY KEY,
                    DepartmentName  nvarchar(128)     not null
                );";

        using (var command = new SqlCommand(tsql, connection))
        {

            command.ExecuteNonQuery();
        }
    }
}
```

### Expected behavior
I expect the process not to crash if the max pool connections are reached, the same behaviour as in Windows.

### Further technical details
I tried the following nuget packages: 
    System.Data.SqlClient version: 4.6.1
    System.Data.SqlClient version: 4.7.0-preview6.19303.8
    Microsoft.Data.SqlClient version: 1.0.19189.1-Preview
.NET target: Core 2.2
SQL Server version: SQL Azure, using Elastic Standard tier
Operating system:
![image](https://user-images.githubusercontent.com/122651/61437327-2436f400-a980-11e9-96be-ed7c3264e7d4.png)

**Additional context**
Also tried it on a docker container, same issue.

**Comment by johnsimons** [comment]
So I modified my repro code to use async/await code, and it seems to work fine!
```c#
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Threading;
using System.Threading.Tasks;

class Program
{
    static volatile int connectionOpen;

    static async Task Main(string[] args)
    {
        var cb = new SqlConnectionStringBuilder(args[0]);

        try
        {
            using (var connection = new SqlConnection(cb.ConnectionString))
            {
                await connection.OpenAsync();

                await CreateTable(connection);
            }
        }
        catch (SqlException e)
        {
            Console.WriteLine(e.ToString());
        }

        var stop = false;
        Console.CancelKeyPress += (sender, eventArgs) =>
        {
            Console.Out.WriteLine("Stopping....");
            eventArgs.Cancel = true;
            stop = true;
        };

        var rnd = new Random();

        var task = Task.Run(() =>
        {
            while (!stop)
            {
                Console.Out.WriteLine($"Connections open {connectionOpen}");
                Thread.Sleep(1000);
            }
        });

        while (!stop)
        {
            var tasks = new List<Task>();
            for (var i = 0; i < 300; i++)
            {
                tasks.Add(Task.Run(async () =>
                {
                    var opened = false;
                    try
                    {
                        using (var connection = new SqlConnection(cb.ConnectionString))
                        {
                            await connection.OpenAsync();
                            Interlocked.Increment(ref connectionOpen);
                            opened = true;

                            await DoSelect(connection);
                            await Task.Delay(rnd.Next(10, 500));
                        }
                    }
                    catch (SqlException e)
                    {
                        Console.WriteLine(e.ToString());
                    }
                    finally
                    {
                        if (opened)
                        {
                            Interlocked.Decrement(ref connectionOpen);
                        }
                    }
                }));
            }

            await Task.WhenAll(tasks);
        }

        await task;

        Console.Out.WriteLine("Done");
    }

    static async Task DoSelect(SqlConnection connection)
    {
        var tsql = @"SELECT * FROM test;";

        using (var command = new SqlCommand(tsql, connection))
        {
            using (SqlDataReader reader = await command.ExecuteReaderAsync())
            {
                while (await reader.ReadAsync())
                {

                }
            }
        }
    }

    static async Task CreateTable(SqlConnection connection)
    {
        var tsql = @"
                DROP TABLE IF EXISTS test;
                CREATE TABLE test
                (
                    DepartmentCode  nchar(4)          not null    PRIMARY KEY,
                    DepartmentName  nvarchar(128)     not null
                );";

        using (var command = new SqlCommand(tsql, connection))
        {

            await command.ExecuteNonQueryAsync();
        }
    }
}

```

**Comment by johnsimons** [comment]
So the process crash was entirely my bad coding, I was only catching `SqlException` and when the pool overflows it throws a different exception, so I modified the `catch (SqlException e)` to `catch (Exception e)` and it now does not crash.
But I am still seeing lots of `System.Data.SqlClient.SqlException (0x80131904): Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception (258): Unknown error 258`

**Comment by cheenamalhotra** [comment]
Hi @johnsimons 

It looks similar to #129 to me. Although that one doesn’t mention Mars.
If you can confirm it’s same, we can track this issue with #129 and close this one.

**Comment by johnsimons** [comment]
@cheenamalhotra it may be similar, but the issue I am seeing is when using `System.Data.SqlClient` not `Microsoft.Data.SqlClient`, and https://github.com/dotnet/SqlClient/issues/129#issuecomment-506802350 seems to be saying that it works in  `System.Data.SqlClient`

**Comment by cheenamalhotra** [comment]
So this issue does occur with System.Data.SqlClient v4.6.1 as well?
I’m just trying to connect the dots as both issues have timeout expiration when pool reaches max limit.

**Comment by cheenamalhotra** [comment]
Also you did mention “Microsoft.Data.SqlClient latest public” in the issue description.. Can you correct that so we can look into the exact version/range of versions?

**Comment by johnsimons** [comment]
@cheenamalhotra I updated those details, let me know if you need anything else?

**Comment by cheenamalhotra** [comment]
@johnsimons 

Would request you to test the scenario once again with latest preview version of the driver. We have made some related fixes, it may fix this issue. If not, we'll keep it open for more investigations into MARS.

**Comment by johnsimons** [comment]
@cheenamalhotra Have just tried the repro with the latest preview ( 1.0.19221.1-Preview) and still get the same errors

**Comment by pawelpabich** [comment]
@cheenamalhotra as far as I can see only the new SqlClient was patched. 

Taking into account that:

a) The new client is still at the pre-release stage
b) All bug reports use the old client

It would be great if the old client was patched too.

**Comment by kf-gonzalez** [comment]
We are closing this issue due to inactivity. Feel free to open a new ticket if you still have the issue with the fix mentioned above.
