### ISSUE TITLE
Migrating from .NET5 to .NET6 throws PlatformNotSupported_DataSqlClient exception on startup in linux

### ISSUE THREAD

**Issue by DFDark** [dotnet/SqlClient#1427]
### Describe the bug
After migration from .NET5 to .NET6 any attempt to run the app ends with `System.PlatformNotSupportedException: Strings.PlatformNotSupported_DataSqlClient` on Linux manjaro. The same code works fine when run in Windows 10/Visual Studio 2019.

The crash happens at the startup when trying to resolve context migrations `contextInstance.Database.Migrate();`

### To Reproduce
<details>
  <summary>Class invoking the exception</summary>

```
class DbContextsMigrator
    {
        public void MigrateDatabase(IServiceProvider serviceProvider, string[] dependentAssemblies)
        {
            if (serviceProvider == null)
                throw new ArgumentNullException(nameof(serviceProvider));
            if (dependentAssemblies == null)
                throw new ArgumentNullException(nameof(dependentAssemblies));

            Assembly[] assemblies = LoadAssemblies(dependentAssemblies);

            Type[] dbContextTypes = assemblies.SelectMany(a => a.GetExportedTypes())
                .Where(t => typeof(DbContext).IsAssignableFrom(t) && !t.IsInterface && !t.IsAbstract)
                .ToArray();

            foreach (Type eachDbContextType in dbContextTypes)
            {
                var genericDbContextOptionsType = typeof(DbContextOptions<>).MakeGenericType(eachDbContextType);

                object dbContextOptionsInstance = serviceProvider.GetService(genericDbContextOptionsType);

                using (DbContext contextInstance = (DbContext) Activator.CreateInstance(eachDbContextType, dbContextOptionsInstance))
                {
                    contextInstance.Database.Migrate();
                }
            }
        }

        private Assembly[] LoadAssemblies(string[] dependentAssemblies)
        {
            var assemblies = new Assembly[dependentAssemblies.Length];

            for (int i = 0; i < dependentAssemblies.Length; i++)
            {
                assemblies[i] = Assembly.Load(dependentAssemblies[i]);
            }

            return assemblies;
        }
```
</details>

### Exceptions (if any)
<details>
  <summary>System.PlatformNotSupportedException: Strings.PlatformNotSupported_DataSqlClient</summary>

```
warn: Microsoft.EntityFrameworkCore.Model.Validation[10400]
Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data; this mode should only be enabled during development.
Application startup exception: System.PlatformNotSupportedException: Strings.PlatformNotSupported_DataSqlClient
   at Microsoft.Data.SqlClient.SqlConnection..ctor(String connectionString)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerConnection.CreateDbConnection()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.get_DbConnection()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.<>c__DisplayClass18_0.<Exists>b__0(DateTime giveUp)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__DisplayClass12_0`2.<Execute>b__0(DbContext c, TState s)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation, Func`2 verifySucceeded)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.Exists(Boolean retryOnNotExists)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at <Project>.Framework.Data.DbContextsMigrator.MigrateDatabase(IServiceProvider serviceProvider, String[] dependentAssemblies) in /<ProjectPath>/src/<Project>.Framework/Data/DbContextsMigrator.cs:line 31
   at <Project>.Framework.Environment.ApiStarter.EnsureDatabaseMigrations(IServiceProvider serviceProvider, String[] depdendentAssemblies) in /<ProjectPath>/src/<Project>.Framework/Environment/ApiStarter.cs:line 48
   at <Project>.WebApi.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, ILoggerFactory loggerFactory, IHostApplicationLifetime appLifetime) in /<ProjectPath>/src/<Project>.WebApi/Startup.cs:line 251
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
crit: Microsoft.AspNetCore.Hosting.Diagnostics[6]
      Application startup exception
      System.PlatformNotSupportedException: Strings.PlatformNotSupported_DataSqlClient
         at Microsoft.Data.SqlClient.SqlConnection..ctor(String connectionString)
         at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerConnection.CreateDbConnection()
         at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.get_DbConnection()
         at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
         at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.<>c__DisplayClass18_0.<Exists>b__0(DateTime giveUp)
         at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__DisplayClass12_0`2.<Execute>b__0(DbContext c, TState s)
         at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
         at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation, Func`2 verifySucceeded)
         at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.Exists(Boolean retryOnNotExists)
         at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.Exists()
         at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
         at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
         at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
         at <Project>.Framework.Data.DbContextsMigrator.MigrateDatabase(IServiceProvider serviceProvider, String[] dependentAssemblies) in /<ProjectPath>/src/<Project>.Framework/Data/DbContextsMigrator.cs:line 31
         at <Project>.Framework.Environment.ApiStarter.EnsureDatabaseMigrations(IServiceProvider serviceProvider, String[] depdendentAssemblies) in /<ProjectPath>/src/<Project>.Framework/Environment/ApiStarter.cs:line 48
         at <Project>.WebApi.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, ILoggerFactory loggerFactory, IHostApplicationLifetime appLifetime) in /<ProjectPath>/src/<Project>.WebApi/Startup.cs:line 251
         at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
         at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
         at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
         at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
         at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
         at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
         at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
         at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
Unhandled exception. System.PlatformNotSupportedException: Strings.PlatformNotSupported_DataSqlClient
   at Microsoft.Data.SqlClient.SqlConnection..ctor(String connectionString)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerConnection.CreateDbConnection()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.get_DbConnection()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.<>c__DisplayClass18_0.<Exists>b__0(DateTime giveUp)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__DisplayClass12_0`2.<Execute>b__0(DbContext c, TState s)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation, Func`2 verifySucceeded)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.Exists(Boolean retryOnNotExists)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at <Project>.Framework.Data.DbContextsMigrator.MigrateDatabase(IServiceProvider serviceProvider, String[] dependentAssemblies) in /<ProjectPath>/src/<Project>.Framework/Data/DbContextsMigrator.cs:line 31
   at <Project>.Framework.Environment.ApiStarter.EnsureDatabaseMigrations(IServiceProvider serviceProvider, String[] depdendentAssemblies) in /<ProjectPath>/src/<Project>.Framework/Environment/ApiStarter.cs:line 48
   at <Project>.WebApi.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, ILoggerFactory loggerFactory, IHostApplicationLifetime appLifetime) in /<ProjectPath>/src/<Project>.WebApi/Startup.cs:line 251
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at <Project>.WebApi.Program.Main(String[] args) in /<ProjectPath>/src/<Project>.WebApi/Program.cs:line 
```

</details>

### Further technical details
- ASP.NET Core version: 6.0.0.sdk100-2
- The IDE: VS Code (linux snap)

<details>
  <summary>dotnet --info Output</summary>

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     manjaro
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.100/

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  2.1.818 [/usr/share/dotnet/sdk]
  3.1.120 [/usr/share/dotnet/sdk]
  6.0.100 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.20 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

```

</details>

**Comment by JRahnama** [comment]
@ajcvickers thanks for transferring this to our team. @DFDark can you provide your connection string options please?

**Comment by DFDark** [comment]
Connection string used: (w/o credentials)
`"Data Source=<projecturl>,<port>;Initial Catalog=<db name>;User=<user>;Password=<pass>;MultipleActiveResultSets=True"`

**Comment by ConductorPete** [comment]
I'm getting the same on both Artix x86 (Arch Linux without SystemD/with OpenRC) and Arch Linux arm64. Manjaro Linux (@DFDark 's OS) is also Arch-based.

**Comment by JRahnama** [comment]
@DFDark and @ConductorPete the error message indicates that wrong runtime packages has been picked up. Were you able to see the issue on a newly created basic application? Something that only tries to open a connection? I will do some testing as well.

**Comment by DFDark** [comment]
@JRahnama 
I have just now tried to make very simple console app (hello world level), where I have object model, simple db context (binding to real db) and main program files and got same exception.

As a sidenote, I have tried updating packages to `6.0.1` version from `6.0.0`, problem is still there.

Simple test codes:
<details>
  <summary>DbContext.cs</summary>

```
using System;
using Microsoft.EntityFrameworkCore;

namespace Test
{
    public class TestContext : DbContext
    {
        public IQueryable<AppUserListed> AppUsersListed => Set<AppUserListed>().AsNoTracking();

        protected override void OnConfiguring(DbContextOptionsBuilder opts)
        {

            base.OnConfiguring(opts);
            opts.UseSqlServer("Data Source=<projecturl>,<port>;Initial Catalog=<db name>;User=<user>;Password=<pass>;MultipleActiveResultSets=True");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<AppUserListed>(b =>
            {
                b.ToTable("vAppUserList", "<<schema>>").HasKey(x => x.Id);
                b.HasMany(r => r.Roles)
                 .WithOne(r => r.User)
                    .HasPrincipalKey(r => r.Id)
                    .HasForeignKey(r => r.UserId);
            });
        }
    }
}
```
</details>
<details>
  <summary>Program.cs</summary>

```
using Microsoft.EntityFrameworkCore.SqlServer;

namespace Test
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var context = new TestContext())
            {
                var users = context.AppUsersListed;

                foreach (var user in users)
                {
                    Console.WriteLine("User: {0}, {1}", user.Id, user.FirstName);
                }
            }
        }
    }
}
```
</details>
<details>
  <summary>Exception</summary>

```
Unhandled exception. System.PlatformNotSupportedException: Strings.PlatformNotSupported_DataSqlClient
   at Microsoft.Data.SqlClient.SqlConnectionStringBuilder..ctor(String connectionString)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerConnection.<>c.<get_IsMultipleActiveResultSetsEnabled>b__7_0(String cs)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerConnection.get_IsMultipleActiveResultSetsEnabled()
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerCompiledQueryCacheKeyGenerator.GenerateCacheKey(Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at Test.Program.Main(String[] args) in /home/dfdark/Desktop/TestC/Test/Program.cs:line 13
```
</details>

**Comment by DFDark** [comment]
Updated sdks and runtimes according to @ConductorPete's post and can confirm it works. Still it's weird that AUR packages were outdated, since they were labeled 6.0.0 (therefore should have been correct before)

**Comment by ConductorPete** [comment]
@DFDark I believe that the difference is the patch version going from .100 to .101 - must have been something important in that single increment. The AUR package is still dated back to November 9th - the official release date of .NET6. 5 weeks is a long time to go without patches one would think. 

We need to remember that the AUR is maintained by good citizens who likely have completely different day jobs - so best to keep in mind that these packages aren't infallible.

**Comment by slackerbob** [comment]
I can confirm the same issue on Rocky Linux 8 (a centos 8 fork).

This happens on both:

- `System.Data.SqlClient 4.8.2`
- `Microsoft.Data.SqlClient 4.0.0`

Using the 6.0 runtime:
- `dotnet-runtime-6.0.x86_64             6.0.0-0.10.el8_5`

But NOT on the 5.0 runtime:
- `dotnet-runtime-5.0.x86_64             5.0.13-1.el8_5`

I have the following sdk installed:
- `dotnet-sdk-6.0.x86_64                 6.0.100-0.10.el8_5`

**Comment by JRahnama** [comment]
@slackerbob have you tried to upgrade to the latest net 6 patch release as mentioned above?

**Comment by JRahnama** [comment]
I am closing the issue as resolved. Please feel free to reopen if the issue still exists.

**Comment by slackerbob** [comment]
@JRahnama I migrated to a docker image, which uses version .101 and the problem went away, so it's doubly confirmed that this was a version .100 bug.

**Comment by scott-parkhill** [comment]
Can this be opened again @JRahnama. I'm having the same issues and tried all the advice here and elsewhere. There are a lot of closed issues about this, and stackoverflow posts without any solutions.

Runtimes:

```
Microsoft.AspNetCore.App 5.0.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.1.20 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

Sdks:

```
3.1.120 [/usr/share/dotnet/sdk]
5.0.102 [/usr/share/dotnet/sdk]
5.0.202 [/usr/share/dotnet/sdk]
5.0.203 [/usr/share/dotnet/sdk]
5.0.204 [/usr/share/dotnet/sdk]
6.0.102 [/usr/share/dotnet/sdk]
```

Error message:

```
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'AXH92F4Eg99QE6TOq8LjaSy3osDHI2tdbSD4nzMdI3s'.
      System.PlatformNotSupportedException: Microsoft.Data.SqlClient is not supported on this platform.
         at Microsoft.Data.SqlClient.SqlConnectionStringBuilder..ctor(String connectionString)
         at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerConnection.<>c.<get_IsMultipleActiveResultSetsEnabled>b__7_0(String cs)
         at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
         at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerConnection.get_IsMultipleActiveResultSetsEnabled()
         at Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerCompiledQueryCacheKeyGenerator.GenerateCacheKey(Expression query, Boolean async)
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, LambdaExpression expression, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.SingleOrDefaultAsync[TSource](IQueryable`1 source, Expression`1 predicate, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`9.FindByEmailAsync(String normalizedEmail, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Identity.UserManager`1.FindByEmailAsync(String email)
         at WebModules.Areas.Identity.Pages.Account.LogIn.StartSignIn() in /project_path_omitted
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
         at Microsoft.AspNetCore.Components.Forms.EditForm.HandleSubmitAsync()
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

We've just spend over an hour trying everything we've found online and nothing has worked.

System:
`Manjaro Linux x86_64`

Thank you, and happy Friday!

**Comment by scott-parkhill** [comment]
The above advice by @ConductorPete did not work for me until I totally removed the `microsoft.data.sqlclient` folder in the nuget directory. Below is a reproduction of my exact steps on Manjaro Linux.

1) Remove the sdks and runtimes.

Either do `sudo pacman -R dotnet-sdk` to remove the sdk, or do:
```
sudo rm -R /usr/share/dotnet/sdk/6*
sudo rm -R /usr/share/dotnet/shared/Microsoft.AspNetCore.App/6*
sudo rm -R /usr/share/dotnet/shared/Microsoft.NETCore.App/6*
```

2) Remove the nuget package.

`sudo rm -R ~/.nuget/packages/microsoft.data.sqlclient`

3) Follow the steps of @ConductorPete, reproduced below.

```
curl -sSL https://dot.net/v1/dotnet-install.sh | sudo bash /dev/stdin -c LTS --install-dir /usr/share/dotnet
sudo ln -sf /usr/share/dotnet/dotnet /usr/bin/dotnet
```

**Comment by JRahnama** [comment]
@scott-parkhill I could see you had older versions of sdk. make sure you have deleted all shared folder as well. the good command to check this is `dotnet sdk check`. This will give you enough information to where to look for outdated versions.

**Comment by scott-parkhill** [comment]
I've just encountered this problem again. Oddly enough, running the program with `dotnet run --arch x64 --os linux` works. However, I could not get the debugger in vs code to work to work with this, so ultimately the previous above solution had to be done again. I don't know why this should have worked though.

**Comment by SRMITGit** [comment]
I'm running Manjaro and this problem keeps occurring. Thankfully I can use @ConductorPete, @scott-parkhill , and importantly @JRahnama 's instructions (delete the old versions first) to fix the issue.

**Comment by luanmm** [comment]
It's a problem that I'm getting here too. I already had it working on Ubuntu 22.04 LTS, but something happened after a system update. Running with `dotnet run --arch x64 --os linux` works, but its not a solution, nor even a workaround (at least in a development environment). Tried to clean the environment and install the latest .NET 6 (6.0.108), event with the new dotnet6 package of APT, but the result is the same.

**Comment by christianfosli** [comment]
See-also: https://github.com/dotnet/SqlClient/issues/1423
(seems like the same issue, but that one is still open, so perhaps it's more likely to be noticed)

**Comment by luizgambali** [comment]
I was having a similar problem using PopOs, my app was running normally on Windows, but on linux I got this message when I try to running "dotnet ef database update". After a lot of searching, I found a solution that solved my problem on a Google forum (https://groups.google.com/g/exceldna/c/4PQLjPj76N4/m/gBtxY5M8DAAJ)

I added the following instruction in my csproj:

    <Target Name="PostBuild" AfterTargets="PostBuildEvent">
        <Exec Command="cp $(OutDir)runtimes/unix/lib/netcoreapp3.1/Microsoft.Data.SqlClient.dll $(OutDir)" />
      </Target>

And it worked! I'm using .net 6, entity framework 6.0.9

**Comment by luizgambali** [comment]
I was having a similar issue using PopOs, my app was running normally on Windows, but on Linux I got this message when I ran . After much searching, I found a solution that solved my problem on a Google forum (https://groups.google.com/g/exceldna/c/4PQLjPj76N4/m/w-0kVCYVDAAJ).

I added the following instructions in my csproj:

        <Target Name="PostBuild" AfterTargets="PostBuildEvent">
             <Exec Command="cp $(OutDir)runtimes/unix/lib/netcoreapp3.1/Microsoft.Data.SqlClient.dll $(OutDir)" />
           </Target>

And it worked! I am using .net 6, entity framework 6.0.9

**Comment by luanmm** [comment]
So, it is indeed a problem with SqlClient or a related runtime process, no?

I really don't know the SQL Client architecture to have a clue on how this works and what is causing this problem, but shouldn't be developer responsability to copy anything extra in the build process.

**Comment by luizgambali** [comment]
For me, it is a problem. I agree with you, we shouldn't have to copy the file manually... the solution I used only solves it temporarily, I hope this problem will be fixed soon

**Comment by stann1** [comment]
I can confirm that reinstalling the runtimes from the correct repository (ppa:dotnet/backports) fixed my issue. Seems like after migrating to ubuntu 24.04, the older runtimes - 6,7 are only supported through the backports repo.
