### ISSUE TITLE
SSL Error with valid certificate issued by internal CA

### ISSUE THREAD

**Issue by mortenn** [dotnet/SqlClient#1437]
I have been having issues with SSL errors connecting to an SQL Server;
```
Microsoft.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The target principal name is incorrect.)
 ---> System.ComponentModel.Win32Exception (0x80090322): The target principal name is incorrect.
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParserStateObject.ThrowExceptionAndWarning(Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParserStateObject.SNIWritePacket(PacketHandle packet, UInt32& sniError, Boolean canAccumulate, Boolean callerHasConnectionLock)
   at Microsoft.Data.SqlClient.TdsParserStateObject.WriteSni(Boolean canAccumulate)
   at Microsoft.Data.SqlClient.TdsParserStateObject.WritePacket(Byte flushMode, Boolean canAccumulate)
```

The server is using a certificate that has been provisioned using a Windows CA server via Active Directory.
The CA is signed by a root Windows CA server, and that root certificate is installed in the trusted root/enterprise root certificate store on the server through a GPO.

The certificate has the subject CN=sqldev1.example.com (actual domain name withheld) and there is a SAN property with several alternate addresses listed.

I have tried connecting to sqldev1.example.com rather than one of the SANs, but that did not resolve the issue.
The only workaround I have found is to set `Trust Server Certificate` to true in the connection string, but that negates the whole point of using this PKI chain..

Any suggestions would be very welcome.

**Comment by JRahnama** [comment]
@mortenn I will test it with a self signed certificate and will get back to you soon.

**Comment by mortenn** [comment]
The answer turns out to be that the subject of the certificate must be the dn of the AD user running the sql server engine.

**Comment by JRahnama** [comment]
@mortenn thanks for finding the solution. I am closing the issue as it seems resolved.
