### ISSUE TITLE
ExecuteXmlReader uses XmlReaderSettings that are incompatible with SQL Server

### ISSUE THREAD

**Issue by taspeotis** [dotnet/SqlClient#1445]
### Describe the bug

I am trying to read a data from a system that stores SMS message bodies. The field is `NVARCHAR(MAX)` and each message is terminated with an EOT (end of transmission) character. The EOT character has a decimal value of 4.

When reading this as XML generated by SQL Server's `FOR XML RAW` the XML is rendered with `&#x4;` in it, like so:

```
<row SMS_RECEIVED="Sorry running late&#x4;" />
```

This is not a valid character, and `XmlReader` disallows it by default:

```
System.Xml.XmlException: '', hexadecimal value 0x04, is an invalid character. Line 1, position 233415.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ParseNumericCharRefInline(Int32 startPos, Boolean expand, StringBuilder internalSubsetBuilder, Int32& charCount, EntityType& entityType)
   at System.Xml.XmlTextReaderImpl.ParseNumericCharRefAsync(Boolean expand, StringBuilder internalSubsetBuilder)
   at System.Xml.XmlTextReaderImpl.HandleEntityReferenceAsync(Boolean isInAttributeValue, EntityExpandType expandType)
   at System.Xml.XmlTextReaderImpl.ParseAttributeValueSlowAsync(Int32 curPos, Char quoteChar, NodeData attr)
   at System.Xml.XmlTextReaderImpl.ParseAttributesAsync()
   at System.Xml.AsyncHelper.ReturnTrueTaskWhenFinishCoreAsync(Task task)
   at System.Xml.XmlWriter.WriteNodeAsync_CallAsyncReader(XmlReader reader, Boolean defattr)
   at ...
```

However SQL Server generates this invalid XML, and I have an expectation that `Microsoft.Data.SqlClient` would be able to consume it. This is quite achievable:

https://github.com/dotnet/SqlClient/blob/d4f69fdc1b302a4039a618ae61538a4f98be3b0b/src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlTypes/SqlTypeWorkarounds.cs#L25-L27

These `XmlReaderSettings` need `CheckCharacters = false`.

### To reproduce

```c#
using Microsoft.Data.SqlClient;

const string connectionString = "...";

await using var connection = new SqlConnection(connectionString);
await connection.OpenAsync();
await using var command = connection.CreateCommand();

command.CommandText = "SELECT N'Sorry running late' + CHAR(4) AS SMS_RECEIVED FOR XML RAW";

using var reader = await command.ExecuteXmlReaderAsync();

while (await reader.ReadAsync())
	;
```

### Expected behavior

`Microsoft.Data.SqlClient` is able to parse all the XML SQL Server generates.

### Further technical details
Microsoft.Data.SqlClient version: 4
.NET target: .NET 6
SQL Server version: 2019
Operating system: Windows 11

**Additional context**

I can try my hand a pull request if you agree that `Microsoft.Data.SqlClient` ought to be able to interpret the XML generated by SQL Server, and that `CheckCharacters = false` is the solution.

**Comment by Wraith2** [comment]
> However SQL Server generates this invalid XML,

How does it generate the XML? It certainly returns the xml stored in the field but it should be be mutating anything into an existing form. If something put invalid content into an xml field and SQL server reads it back when that field is requested then that's just what you get for putting invalid data into your field.

**Comment by taspeotis** [comment]
> How does it generate the XML?

It ... just generates it? That's what `FOR XML` does: it instructs SQL Server to generate XML for a result set.

> If something put invalid content into an xml field and SQL server reads it back when that field is requested then that's just what you get for putting invalid data into your field.

The field is `NVARCHAR(MAX)` which permits the storage of characters, EOT is a character. The data stored is valid. For what it's worth it could be `VARCHAR(100)` field or something, EOT is the fifth character in ASCII.

XML doesn't allow the representation of all characters as strings, SQL Server would have to generate something like a CDATA section here or Base64 encode it if it wanted to generate valid XML for all scenarios. At any rate it's still syntactically valid, and can be parsed by `Microsoft.Data.SqlClient` if it created the `XmlReader` with more lenient `XmlReaderSettings`.

**Comment by Wraith2** [comment]
Ok. So the user inserts data into an nvarchar column which contains an known character which would be invalid in xml. User then queries using FOR XML and the server sticks together the nvarchar columns containing the character and returns the result. Then the driver tries to use the result as valid xml and fails.

I think the only possible bug here is that the query returns results. If you want to be pedantic about the contents of the strings being valid in xml then the server response should be an error telling you that the contents of the input data to the query contains invalid characters. I expect that this isn't done for performance and user data permissiveness reasons.

I don't see this as a bug in sql client. If you ask for xml you, the user, should make sure that your data will be valid xml from the query. In this case you know for sure that it will be and you should be responsible for fixing that. Lets see what the MS team (I'm just an external contributor) say.

**Comment by JRahnama** [comment]
@taspeotis and @Wraith2 just to confirm that we are following the conversation and doing some testing. I may not respond till January 4th or 5th as we have lots of emails and issues to go through for a few days.

**Comment by Kvasi** [comment]
I have the same problem and have been trying to get around it by setting CheckCharacters = false, but the new XmlReader still gets CheckCharacters = true
```
using (var reader_org = command.ExecuteXmlReader())
{
    var settings = new XmlReaderSettings { CheckCharacters = false, ConformanceLevel = ConformanceLevel.Auto };
    var reader = XmlReader.Create(reader_org, settings);
    reader.Read();
}
```

**Comment by taspeotis** [comment]
@Kvasi The problem with that approach is `reader` has to read from `reader_org` which is not able to read the XML generated by SQL Server. At a pinch you can get your hands on a `TextReader` and create the `XmlReader` yourself:

```cs
await using var reader = await command.ExecuteReaderAsync();

if (await reader.ReadAsync())
{
    using var textReader = reader.GetTextReader(0);

    var settings = new XmlReaderSettings
    {
        Async = true,
        CheckCharacters = false,
        ConformanceLevel = ConformanceLevel.Fragment
    };

    using var xmlReader = XmlReader.Create(textReader, settings);
```

Whether the underlying `TextReader` implementation is particularly async or not I'm unsure but if you need an `XmlReader` you can get it this way.
