### ISSUE TITLE
Upgrade to 4.0, I get a message when the app runs in an installer can't find Microsoft.Data.SqlClient 3.0.0

### ISSUE THREAD

**Issue by DataJuggler** [dotnet/SqlClient#1448]
### Describe the bug
I updaded a project and Nuget package to .NET6, updgraded from System.Data.SqlClient to Microsoft.Data.SqlClient 4.0.0, and the installer runs. When I try and connect to a database, I get the error can't find Microsoft.Data.SqlClient version 3.0.0.

With packages references I knew how to add a binding redirect, I don't see how to that in a Project file.

Just a comment, your breaking change of 'Encrypt = true' now by default. I went the other way. I started off with encryption by default in 2010 and decided in 2019 it was time to make it Encrypted = false. You broke my project DB Compare, because people paste in connection strings, and they won't work now. I wish this was an option, not a dictate by you. Not everyone is as paranoid about security as you are.

Can someone explain to me how to force the entire app to use 4.0.0 version? 

If you are seeing an exception, include the full exceptions details (message and stack trace).

************** Exception Text **************
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Data.SqlClient, Version=3.0.0.0, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5'. The system cannot find the file specified.
File name: 'Microsoft.Data.SqlClient, Version=3.0.0.0, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5'
   at DataJuggler.Net6.ConnectionStringHelper.BuildConnectionString(String serverName, String databaseName)
   at DBCompare.ConnectionStringBuilderForm.BuildConnectionStringButton_Click(Object sender, EventArgs e) in C:\Projects\GitHub\DBCompare\DBCompare\ConnectionStringBuilderForm.cs:line 65
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.121.56705
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Private.CoreLib.dll
----------------------------------------
DBCompare
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Data%20Juggler/DB%20Compare/DBCompare.dll
----------------------------------------
System.Runtime
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.121.56705
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 6.0.1.0
    Win32 Version: 6.0.121.56705
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.1/System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.121.56705
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.ComponentModel.Primitives.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 6.0.1.0
    Win32 Version: 6.0.121.56705
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.1/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.121.56705
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.121.56705
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.121.56705
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Collections.Specialized.dll
----------------------------------------
DataJuggler.Win.Controls
    Assembly Version: 5.8.9.0
    Win32 Version: 5.8.9.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Data%20Juggler/DB%20Compare/DataJuggler.Win.Controls.dll
----------------------------------------
System.Threading
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.121.56705
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.121.56705
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.121.56705
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Collections.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.121.56705
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.1/System.Drawing.Common.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.121.56705
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.121.56705
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.121.56705
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Threading.Thread.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 6.0.121.56705
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.1/Accessibility.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.121.56705
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.121.56705
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.ComponentModel.dll
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.121.56705
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Numerics.Vectors.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.121.56705
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.1/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.121.56705
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.1/System.Resources.Extensions.dll
----------------------------------------
System.Memory
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.121.56705
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Memory.dll
----------------------------------------
System.Drawing
    Assembly Version: 6.0.1.0
    Win32 Version: 6.0.121.56705
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.1/System.Drawing.dll
----------------------------------------
System.ObjectModel
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.121.56705
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.ObjectModel.dll
----------------------------------------
System.Linq
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.121.56705
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Linq.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.121.56705
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Collections.NonGeneric.dll
----------------------------------------
System.Configuration.ConfigurationManager
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.121.56705
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.1/System.Configuration.ConfigurationManager.dll
----------------------------------------
DataJuggler.UltimateHelper
    Assembly Version: 1.6.8.0
    Win32 Version: 1.6.8.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Data%20Juggler/DB%20Compare/DataJuggler.UltimateHelper.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.121.56705
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Private.Uri.dll
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.121.56705
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
System.Security.Cryptography.Algorithms
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.121.56705
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Security.Cryptography.Algorithms.dll
----------------------------------------
System.Security.Cryptography.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.121.56705
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Security.Cryptography.Primitives.dll
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.121.56705
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.121.56705
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Private.Xml.dll
----------------------------------------
System.Text.RegularExpressions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.121.56705
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Text.RegularExpressions.dll
----------------------------------------
System.Net.WebClient
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.121.56705
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Net.WebClient.dll
----------------------------------------
System.Text.Encoding.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.121.56705
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Text.Encoding.Extensions.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.121.56705
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Runtime.Serialization.Formatters.dll
----------------------------------------
System.Xml.XmlSerializer
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.121.56705
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Xml.XmlSerializer.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.121.56705
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.121.56705
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Collections.Concurrent.dll
----------------------------------------
DataJuggler.Net6
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Data%20Juggler/DB%20Compare/DataJuggler.Net6.dll
----------------------------------------
System.Runtime.Loader
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.121.56705
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Runtime.Loader.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.121.56705
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.121.56705
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.121.56705
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Collections.Immutable.dll
----------------------------------------

************** JIT Debugging **************

```
Exception message:
Stack trace:
```

### To reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
Console.WriteLine("Hello World!");
```

### Further technical details
Microsoft.Data.SqlClient version: (found on the nuget or Microsoft.Data.SqlClient.dll)
.NET target: (e.g. Framework 4.7.1, Core 2.2.2)
SQL Server version: (e.g. SQL Server 2017)
Operating system: (e.g. Windows 2019, Ubuntu 18.04, macOS 10.13, Docker container)

**Additional context**

**Comment by ErikEJ** [comment]
Please share the .csproj of your main executable project


You must have a 3.0 reference somewhere...

**Comment by DataJuggler** [comment]
My project file is attached. Thank you for the fast response.

My project file is attached. I looked all through the projects that are mine, I can't find anything.

Is there a way to force it to use 4.0, like a binding redirect? Switching from packages.config to project references is another thing I wouldn't have voted on.

I understand the benefit to updating if things work. I don't get paid to fix all these changes like salaried people do, but thanks none the less for trying to help.

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Version>6.0.0</Version>
    <PackageId>DataJuggler.DBCompare</PackageId>
    <Authors>DataJuggler</Authors>
    <Company>DataJuggler</Company>
    <Product>DataJuggler.DBCompare</Product>
    <Description>DB Compare compares two instances of a SQL Server database. This project has been on .Net Framework
for about 10 or 12 years or more. DB Compare has been updated to .NET6.0, and should run faster.

C# Developers - Now you can create a project in a manner of minutes and this way you can stay updated with the latest version.

This product is also a standalone application. Using it as a Nuget package is just a nice way to always have
the latest version.</Description>
    <PackageLicenseFile>License.txt</PackageLicenseFile>
    <PackageProjectUrl>https://github.com/DataJuggler/DBCompare</PackageProjectUrl>
    <PackageIcon>Database Compare Transparent.png</PackageIcon>
    <RepositoryUrl>https://github.com/DataJuggler.git</RepositoryUrl>
    <RepositoryType>Git / Git Hub</RepositoryType>
    <PackageTags>C#, SQL, Database, Compare Schema, Compare Databases, Compare SQL</PackageTags>
    <PackageReleaseNotes>Version 5.0.9 - I created a Generate Scripts Button that shows after a Comparison. For now it only creates the Fields that are missing. I will work on this over time. All fields are created as a nullable. If you need to change that, you can change the SQL that is copied to your clipboard.

Version 5.0.8 - I added a link to a video I just made for this project in the ReadMe.txt that opens.

Version 5.0.7 - The text was out of date. I need to convert the text to pull from the binary version number, or remember to enter the text when I update.

Version 5.0.6 - The YouTube Button showed up on the Form, but the background image didn't make it. Now this is fixed. I should have checked for this when I fixed the Swap Button. Oops.

Version 5.0.5 - The Swap Button showed up on the Form, but the background image didn't make it. Now this is fixed.

Version 5.0.4 - Testing including a ReadMe that opens with the project. (Worked)

Version 5.0.3 - It turns out the Label text is set in the Init method of the Main Form.
It is fixed now.

Version 5.0.2 - I left the version # as 2 something on the Main Form. Now it is up to date.
I now know this works! New video coming soon.

Version 5.0.1  - I had an image path that was in my Graphics folder, not in the project folder.

This is the 1st version for .Net 5. This project has been ported from .Net Framework, and this is the 1st
attempt as a Nuget package.</PackageReleaseNotes>
    <ApplicationIcon>Database Compare Transparent.ico</ApplicationIcon>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DataJuggler.RandomShuffler" Version="6.0.0" />
    <PackageReference Include="DataJuggler.UltimateHelper" Version="6.0.0" />
    <PackageReference Include="DataJuggler.Win.Controls" Version="6.1.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="4.0.0" />
    <PackageReference Include="XmlMirror.Runtime6" Version="6.0.1" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Images\Database Compare Transparent.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>    
    <None Include="License\License.txt">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Include="readme.txt" pack="true" PackagePath="." />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\DataJuggler.Net6\DataJuggler.Net6.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>

**Comment by DataJuggler** [comment]
I found it. One of my Nuget packages had a reference to 3.0.0.

It seems kind of hard to go down the chain and see this.

Sorry to bother you, and thank you.

**Comment by JRahnama** [comment]
@DataJuggler I tried to clone your application from your [GitHub repo ](https://github.com/DataJuggler/DBCompare), correct me if I have gone to a wrong repo. By just changing `System.Data.SqlClient` to `Microsoft.Data.SfqlClient` the application worked fine as a project. I did not try the installer or using the created nuget though. There might be referencing to other projects that have dependencies to version 3 of MDS?

Regarding the breaking change, we tried to avoid it for several years, but the security concern was going high. you can read more at this discussion [here](https://github.com/dotnet/SqlClient/pull/1210#issuecomment-898658021).

**Comment by DataJuggler** [comment]
The latest version is not checked in until I can fix this.

Not sure what TargetFramework the check in version is. It was just upgraded to 6.0.0, and Microsoft.Data.SqlClient 4.0.0

I can put a zip file on my server or somewhere else if you prefer.

The problem occurs when a method called Test Database Connection is called, if you don’t add encrypt=false. Short solution is I can just add it, but then I don’t see any benefit to your security upgrade.

Forcing SSL of SQL on people should have been an option, especially for non servers. If anyone is sniffing between my ATT Fiber Modem and my machine, I have bigger problems than SQL.

**Comment by cheenamalhotra** [comment]
Closing as stale
