### ISSUE TITLE
Event Counters are always emitting Zeros in Container

### ISSUE THREAD

**Issue by fame** [dotnet/SqlClient#1526]
I am trying to investigate an issue with Connection pool exhaustion in our AKS containers running alpine Linux. I've tried many variations of the commands described in https://docs.microsoft.com/en-us/sql/connect/ado-net/event-counters?view=sql-server-ver15, but always getting zeros. However, I am able to monitor standard Counters with out any problem.

Image: mcr.microsoft.com/dotnet/runtime-deps:6.0-alpine
Published as self contained app
Using SqlClient https://www.nuget.org/packages/Microsoft.Data.SqlClient/4.0.0
Connection String: 
`Server=tcp:--.database.windows.net,1433;Authentication=Active Directory Default;Initial Catalog=--;Persist Security Info=False;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;`

Tried 1/2/3 second intervals
dotnet-counters monitor Microsoft.Data.SqlClient.EventSource -p 1 --refresh-interval 1
dotnet-trace collect --process-id 1 --providers Microsoft.Data.SqlClient.EventSource:0:1:EventCounterIntervalSec=1

Trying to investigate the following Exception message
```
 System.InvalidOperationException: Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.
   at Microsoft.Data.Common.ADP.ExceptionWithStackTrace(Exception e)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<>c__DisplayClass33_0`2.<<ExecuteAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
```

Can you guys provide any insight on how I should proceed?

**Comment by JRahnama** [comment]
@fame can you provide a small repro for the issue please?

**Comment by cheenamalhotra** [comment]
Closing as stale
