### ISSUE TITLE
System.Data.SqlClient is globally resourced. Unable to connect to sqlserver address

### ISSUE THREAD

**Issue by xueandfeng** [dotnet/SqlClient#154]
When doing docker deployment under linux, I found that I could not connect to the database when I was in the resource of Thai. In Chinese or English, the situation is normal.
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-2.2

**Comment by cheenamalhotra** [comment]
Hi @xueandfeng 

The issue might have been fixed in later versions of System.Data.SqlClient. Would recommend testing with Microsoft.Data.SqlClient ([latest preview](https://www.nuget.org/packages/Microsoft.Data.SqlClient/1.0.19221.1-Preview)) and confirm if it works fine.

**Comment by xueandfeng** [comment]
System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 6): No such device or address
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)
   at System.Data.SqlClient.SNI.SNITCPHandle.Connect(String serverName, Int32 port, TimeSpan timeout)
   at System.Data.SqlClient.SNI.SNITCPHandle..ctor(String serverName, Int32 port, Int64 timerExpire, Object callbackObject, Boolean parallel)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()

Currently using System.Data.SqlClient4.7.0-preview8.19405.3 is still the above error. I feel that using global resources in the case of Thai. Parsing the connection string is wrong

**Comment by xueandfeng** [comment]
![图片](https://user-images.githubusercontent.com/20178645/62995241-44c87000-be92-11e9-989e-91a58b444ddb.png)
I am using Microsoft.Data.SqlClient latest preview version is also the same error. Docker is deployed in Linux.
Normal use under window

![图片](https://user-images.githubusercontent.com/20178645/62995372-d46e1e80-be92-11e9-9b31-df85cb189e62.png)
You can try this under the Linux deployment test.

**Comment by ErikEJ** [comment]
@JRahnama Could this be fixed now?

**Comment by JRahnama** [comment]
@ErikEJ  this is happening in S.D.S and the fix is not going to be back ported unless it is a security fix.

**Comment by JRahnama** [comment]
@ErikEJ to correct my previous comment and adding more to it, if the issue is happening in nuget of S.D.SqlClient, then it cannot be fixed, but if it is happening in S.D.SqlClient it might/could be back ported.

**Comment by JRahnama** [comment]
> So out of scope for this repo?

Correct. We need to keep this open till the backport is done and then we can close the issue.

**Comment by JRahnama** [comment]
In case of any issue related to System.Data.SqlClient reach out to Microsoft support. The issue has been fixed in M.D.Sqlclient.

Closing as this is out of scope.
