### ISSUE TITLE
Regression: v4.0.0 fails connecting to SQL Server 2008 instances with one way mirroring set up

### ISSUE THREAD

**Issue by ssg** [dotnet/SqlClient#1549]
### Describe the bug
When you try to connect SQL Server 2008 instances with a one way mirroring set up, connection attempts fail with a KeyNotFoundException. This can be worked around by adding "Failover Partner=" string to the connection string as explained at https://stackoverflow.com/questions/70409379/microsoft-data-sqlclient-sqlconnection-openasync-throws-error-saying-the-given .

```
Exception message:
Stack trace:
at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
at Microsoft.Data.SqlClient.SqlConnectionPoolGroupProviderInfo.CreateFailoverPermission(SqlConnectionString userConnectionOptions, String actualFailoverPartner)
at Microsoft.Data.SqlClient.SqlConnectionPoolGroupProviderInfo.FailoverCheck(Boolean actualUseFailoverPartner, SqlConnectionString userConnectionOptions, String actualFailoverPartner)
at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, ServerCertificateValidationCallback serverCallback, ClientCertificateRetrievalCallback clientCallback, DbConnectionPool pool, String accessToken, SqlClientOriginalNetworkAddressInfo originalNetworkAddressInfo, Boolean applyTransientFaultHandling)
at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
at Microsoft.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
```

### To reproduce
```
var conn = new SqlConnection("Data Source=server; Database=db; Integrated Security=true;TrustServerCertificate=true");
conn.Open(); // fails - only succeeds with pre-4.x
```

```
var conn = new SqlConnection("Data Source=server; Database=db; Integrated Security=true;TrustServerCertificate=true; Failover Partner=");
conn.Open(); // succeeds
```

### Expected behavior
Connection should succeed as it does with pre-4.x versions without relying on a connection string key existing.

### Further technical details
Microsoft.Data.SqlClient version: 4.0.0-4.1.0
.NET target: .NET Framework 4.8 / .NET Standard 2.0
SQL Server version: 2008
Operating system: Windows Server 2012

### Additional context
The same attempt succeeds on a Windows 11 client, or a SQL Server without mirroring set up.

**Comment by Kaur-Parminder** [comment]
@ssg Thanks, I'll add it to the triage for more discussion.

Did you try with any other version of SQL server? here is list of SQL Server Version M.D.S provides support https://docs.microsoft.com/en-us/sql/connect/ado-net/sqlclient-driver-support-lifecycle?view=sql-server-ver15#sql-version-compatibility-with-microsoftdatasqlclient

**Comment by ssg** [comment]
No, I haven't tried it yet. Will let you know if I can repro it on a newer version. Thank you.

**Comment by JRahnama** [comment]
Closing due to inactivity. Feel free to comment or open a new issue if it still exists.
