### ISSUE TITLE
"The Collation specified by SQL Server is not supported." for Hungarian_Technical_CI_AS collation

### ISSUE THREAD

**Issue by Charles-Gagnon** [dotnet/SqlClient#1572]
### Describe the bug

See https://github.com/microsoft/azuredatastudio/issues/18892 for the original issue where this was noticed.

It seems very similar to https://github.com/dotnet/SqlClient/issues/576

I've been unable to repro this with just a simple test app, still working on this. (I can also repro it locally with ADS though) But the error seems to indicate an issue in SqlClient so opening this issue to see if we can get more information about why this would be happening in our scenario. 

This happens for a database with the `Hungarian_Technical_CI_AS` collation, a `Latin1_General_100_CI_AS` collation doesn't show the problem. 

```
Exception message: Unknown exception during parsing Microsoft.Data.SqlClient.SqlException (0x80131904): The Collation specified by SQL Server is not supported.
```

```
22-03-31 17:52:47.9961298 pid:15040 tid:21 sqltools Error: 0 : Unknown exception during parsing Microsoft.Data.SqlClient.SqlException (0x80131904): The Collation specified by SQL Server is not supported.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   at Microsoft.Data.SqlClient.TdsParser.DrainData(TdsParserStateObject stateObj)
   at Microsoft.Data.SqlClient.TdsParser.ThrowUnsupportedCollationEncountered(TdsParserStateObject stateObj)
   at Microsoft.Data.SqlClient.TdsParserStateObject.TryReadStringWithEncoding(Int32 length, Encoding encoding, Boolean isPlp, String& value)
   at Microsoft.Data.SqlClient.TdsParser.TryReadSqlStringValue(SqlBuffer value, Byte type, Int32 length, Encoding encoding, Boolean isPlp, TdsParserStateObject stateObj)
   at Microsoft.Data.SqlClient.TdsParser.TryReadSqlValue(SqlBuffer value, SqlMetaDataPriv md, Int32 length, TdsParserStateObject stateObj, SqlCommandColumnEncryptionSetting columnEncryptionOverride, String columnName, SqlCommand command)
   at Microsoft.Data.SqlClient.SqlDataReader.TryReadColumnInternal(Int32 i, Boolean readHeaderOnly)
   at Microsoft.Data.SqlClient.SqlDataReader.GetValues(Object[] values)
   at Microsoft.SqlServer.Management.Smo.DataProvider.ReadInternal()
   at Microsoft.SqlServer.Management.Smo.DataProvider.SetConnectionAndQuery(ExecuteSql execSql, String query)
   at Microsoft.SqlServer.Management.Smo.ExecuteSql.GetDataProvider(StringCollection query, Object con, StatementBuilder sb, RetriveMode rm)
   at Microsoft.SqlServer.Management.Smo.ExecuteSql.ExecuteWithResults(StringCollection query, Object con, StatementBuilder sb)
   at Microsoft.SqlServer.Management.Smo.SqlObjectBase.FillData(ResultType resultType, StringCollection sql, Object connectionInfo, StatementBuilder sb)
   at Microsoft.SqlServer.Management.Smo.SqlObjectBase.FillDataWithUseFailure(SqlEnumResult sqlresult, ResultType resultType)
   at Microsoft.SqlServer.Management.Smo.SqlObjectBase.BuildResult(EnumResult result)
   at Microsoft.SqlServer.Management.Smo.DatabaseLevel.GetData(EnumResult res)
   at Microsoft.SqlServer.Management.Sdk.Sfc.Environment.GetData()
   at Microsoft.SqlServer.Management.Sdk.Sfc.Environment.GetData(Request req, Object ci)
   at Microsoft.SqlServer.Management.Sdk.Sfc.Enumerator.GetData(Object connectionInfo, Request request)
   at Microsoft.SqlServer.Management.Smo.ExecutionManager.GetEnumeratorDataReader(Request req)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.GetInitDataReader(String[] fields, OrderBy[] orderby)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.ImplInitialize(String[] fields, OrderBy[] orderby)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.OnPropertyMissing(String propname, Boolean useDefaultValue)
   at Microsoft.SqlServer.Management.Smo.PropertyCollection.RetrieveProperty(Int32 index, Boolean useDefaultOnMissingValue)
   at Microsoft.SqlServer.Management.Smo.PropertyCollection.GetValueWithNullReplacement(String propertyName, Boolean throwOnNullValue, Boolean useDefaultOnMissingValue)
   at Microsoft.SqlServer.Management.Smo.PropertyCollection.GetValueWithNullReplacement(String propertyName)
   at Microsoft.SqlServer.Management.Smo.Database.get_DefaultSchema()
   at Microsoft.SqlServer.Management.SmoMetadataProvider.Database.get_DefaultSchemaName()
   at Microsoft.SqlServer.Management.SqlParser.Binder.DatabaseEx.get_DefaultSchemaName()
   at Microsoft.SqlServer.Management.SqlParser.Binder.DatabaseEx.get_DefaultSchema()
   at Microsoft.SqlServer.Management.SqlParser.Binder.SchemaEx.CreateUnnamedSchema(DatabaseEx database, SchemaEx defaultSchema)
   at Microsoft.SqlServer.Management.SqlParser.Binder.SchemaEx.CreateUnnamedSchema(DatabaseEx database)
   at Microsoft.SqlServer.Management.SqlParser.Binder.DatabaseEx.get_UnnamedSchema()
   at Microsoft.SqlServer.Management.SqlParser.Binder.BatchBindingContext..ctor(DatabaseEx database)
   at Microsoft.SqlServer.Management.SqlParser.Binder.BinderProvider.Binder.BindAll(IEnumerable`1 parseResults, String databaseName, BindMode bindMode)
   at Microsoft.SqlServer.Management.SqlParser.Binder.BinderProvider.Binder.Bind(IEnumerable`1 parseResults, String databaseName, BindMode bindMode)
   at Microsoft.SqlTools.ServiceLayer.LanguageServices.LanguageService.<>c__DisplayClass70_0.<ParseAndBind>b__1(IBindingContext bindingContext, CancellationToken cancelToken) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\LanguageServices\LanguageService.cs:line 987
```

### To reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
Console.WriteLine("Hello World!");
```

### Further technical details
Microsoft.Data.SqlClient version: 3.0.0
.NET target: net6.0
SQL Server version: SQL Server 2022
Operating system: Windows 11

**Additional context**

**Comment by DavoudEshtehari** [comment]
Hi @Charles-Gagnon, 

We'll check it out.

**Comment by Kaur-Parminder** [comment]
@Charles-Gagnon It is likely related to #1396   What SDK and runtime version are you using? There was issue with these collation with .Net6 https://github.com/dotnet/runtime/issues/61977#issuecomment-978125240 I believe, the one you are using is also on list:  hu-HU_technl

I am using these sdk (6.0.201]) and runtime 6.0.3, I see CodePages has been fixed which was root cause originally. if you have lower version can you upgrade version and test if this helps?

**Comment by Charles-Gagnon** [comment]
Updating from 6.0.1 to 6.0.201 SDK did the trick, thank you!
