### ISSUE TITLE
NullReference Exception in SqlParameterCollection.Add() when using a Typed DataSet and EF 6.3 in the same .NET Core 3.0 Project (Preview 8) 

### ISSUE THREAD

**Issue by HSchwichtenberg** [dotnet/SqlClient#172]
**Repro steps**

1. Create a dotnet core 3.0 project (Preview 8)
2. Add PackageReferences 
    PackageReference Include="System.Data.DataSetExtensions" Version="4.6.0-preview3.19128.7" />
    PackageReference Include="System.Data.SqlClient" Version="4.7.0-preview8.19405.3" />
2. Add a typed dataset
3. Run Code, e.g.
     var d = new MyDataSet(); 
    var t = new MyTableTableAdapter();
     t.Connection.ConnectionString = @"...";
     t.Fill(d.MyTable);
4. Now add another reference
    PackageReference Include="EntityFramework" Version="6.3.0-preview8-19405-04" />
5. The above code will fail now at  this._adapter.DeleteCommand.Parameters.Add():
System.NullReferenceException: 'Object reference not set to an instance of an object.'

[TypedDataSetDemo.zip](https://github.com/dotnet/SqlClient/files/3566592/TypedDataSetDemo.zip)

**Expected result**

I should be able to use Typed DataSet and EF 6.3 in the same project (for migrating old projects using Typed DataSets)

**Actual result**

System.NullReferenceException: 'Object reference not set to an instance of an object.' in the generated code.
![2019-09-02_17-28-46](https://user-images.githubusercontent.com/3673169/64124424-49a08580-cda7-11e9-802d-bf42c5ac4165.png)

**Note**

The same error happens if you have the Typed DataSet and the EF 6.3 in different projects that are referenced by the same start project.

**Comment by ErikEJ** [comment]
What if you take EF out of the equation?

**Comment by HSchwichtenberg** [comment]
The code works if there is no reference to EntityFramework 6.3.0-preview8-19405-04. Just add the Nuget reference to EntityFramework 6.3.0-preview8-19405-04 and the generated Typed Dataset code will now fail, even if you don't change the code, i.e. not use EF at all.

**Comment by HSchwichtenberg** [comment]
Just tried the latest nightly builds. The problem is still there:
    PackageReference Include="EntityFramework" Version="6.3.0-preview9-19423-04" />
    PackageReference Include="System.Data.DataSetExtensions" Version="4.6.0-preview4.19203.6" />
    PackageReference Include="System.Data.SqlClient" Version="4.7.0-preview9.19421.4" />

**Comment by ErikEJ** [comment]
I am able to repro with this csproj, so without any EF6 reference:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Data.SqlClient" Version="4.7.0-preview9.19421.4" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="DataSet1.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DataSet1.xsd</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="DataSet1.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>DataSet1.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>

```

**Comment by ErikEJ** [comment]
Stack;

```
   at System.Data.SqlClient.SqlParameter.set_XmlSchemaCollectionDatabase(String value)
   at System.Data.SqlClient.SqlParameter..ctor(String parameterName, SqlDbType dbType, Int32 size, ParameterDirection direction, Byte precision, Byte scale, String sourceColumn, DataRowVersion sourceVersion, Boolean sourceColumnNullMapping, Object value, String xmlSchemaCollectionDatabase, String xmlSchemaCollectionOwningSchema, String xmlSchemaCollectionName)
   at TypedDataSetDemo.DataSet1TableAdapters.ApplicationsTableAdapter.InitAdapter() in C:\Users\Erik\Downloads\TypedDataSetDemo\TypedDataSetDemo\DataSet1.Designer.cs:line 755
   at TypedDataSetDemo.DataSet1TableAdapters.ApplicationsTableAdapter.get_Adapter() in C:\Users\Erik\Downloads\TypedDataSetDemo\TypedDataSetDemo\DataSet1.Designer.cs:line 684
   at TypedDataSetDemo.DataSet1TableAdapters.ApplicationsTableAdapter.Fill(ApplicationsDataTable dataTable) in C:\Users\Erik\Downloads\TypedDataSetDemo\TypedDataSetDemo\DataSet1.Designer.cs:line 801
   at TypedDataSetDemo.Program.Main(String[] args) in C:\Users\Erik\Downloads\TypedDataSetDemo\TypedDataSetDemo\Program.cs:line 13


```

**Comment by Wraith2** [comment]
huh? how...

https://github.com/dotnet/SqlClient/blob/c21aa7cf29ef2a7d38e58179f265dd0135e9082e/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlParameter.cs#L265-L276

**Comment by ErikEJ** [comment]
Using System.Data.SqlClient, not M.D.Sqlclient, perhaps?

**Comment by Wraith2** [comment]
Oh. In which case that'll be something i changed again. There's a subobject for the xml strings since they're so rarely used and the null ref implies that it hasn't been created. that would be strange though since it's supposed to be guarded and lazy created.

**Comment by Wraith2** [comment]
Yup, check out that null checking logic.

https://github.com/dotnet/corefx/blob/019969851b91a473ef769e8fbd8f6b6367a2f062/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlParameter.cs#L256-L274

Any chance you can massage that repro into a test that can go along with the fix?

**Comment by ErikEJ** [comment]
This is the repro in all it's smplicity:

```
            var command = new System.Data.SqlClient.SqlCommand();
            command.Parameters.Add(new System.Data.SqlClient.SqlParameter("@Original_Id", System.Data.SqlDbType.BigInt, 0, System.Data.ParameterDirection.Input, 0, 0, "Id", System.Data.DataRowVersion.Original, false, null, "", "", ""));
```

**Comment by Wraith2** [comment]
I assumed (silly me) that the corefx version had decent coverage in it's unit testing but i'm finding that this can't be true. What we could do with is the code coverage numbers (which are planned i believe) and some people who like writing unit tests (which i hate). You really would have thought there were some dataset unit tests though wouldn't you. Since the fix needs to go into corefx if i open a PR tonight it should be in System.Data.SqlClient in about 3-6 months if it meets the bug fix bar.

**Comment by ErikEJ** [comment]
OK - So the changes that were made in this area have not been ported to M.D.S, is that how it works? 

@divega Could you move this bug to the CoreFx repo?

**Comment by ErikEJ** [comment]
Are these all the tests that we have for SqlParameter??  😨 

https://github.com/dotnet/SqlClient/blob/master/src/Microsoft.Data.SqlClient/tests/FunctionalTests/SqlParameterTest.cs

**Comment by Wraith2** [comment]
Check the manual tests folder. the majority of the testing is done there.

**Comment by cheenamalhotra** [comment]
The change was merged in dotnet/corefx#35549 with low test coverage, which hasn't been ported over to Microsoft.Data.SqlClient and hence you do not see a failure here.

**Comment by Wraith2** [comment]
Fix in corefx PR is posted.

**Comment by ErikEJ** [comment]
@cheenamalhotra how do I get a package with the fix?

**Comment by Wraith2** [comment]
I can build you one if you like

**Comment by HSchwichtenberg** [comment]
Yes, @Wraith2, please provide a download for the package.

**Comment by Wraith2** [comment]
Debug version (which means asserts are present, prf will suck) but it should be enough to prove the fix. I can manually patch in a release version of the netcore assembly if really needed. rename from .zip to .nupkg
[System.Data.SqlClient.5.0.0-dev.19464.1.zip](https://github.com/dotnet/SqlClient/files/3613056/System.Data.SqlClient.5.0.0-dev.19464.1.zip)

**Comment by HSchwichtenberg** [comment]
Thanks, @Wraith2, unfortunately your package requires other packages that are not available on the feeds mentioned here: https://github.com/aspnet/AspNetCore/blob/master/docs/DailyBuilds.md

See attached screenshot
![2019-09-16_16-35-58](https://user-images.githubusercontent.com/3673169/64967115-45449400-d8a0-11e9-8bc1-5a087fb06671.png)

This fix is however important to run typed datasets on .NET Core. When will it be released?
Or is there any workaround how I can run a typed dataset on .NET Core?

**Comment by Wraith2** [comment]
It should be in 3.1 which is an LTS release due out shortly after 3.0. It's still unmerged though, not sure what's going on with that.

**Comment by HSchwichtenberg** [comment]
Sorry, closing the issue was an mistake :-|

**Comment by ErikEJ** [comment]
A a workaround, you can manually modify the generated code to use a shorter constructor.
