### ISSUE TITLE
Crash with 5.0.0 when DacFx is referenced

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/SqlClient#1743]
Error:

```
Unhandled exception. System.TypeLoadException: Could not load type 'Microsoft.Data.SqlClient.Server.IBinarySerialize' from assembly 'Microsoft.Data.SqlClient, Version=5.0.0.0, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5'.
   at System.Reflection.RuntimeAssembly.GetType(QCallAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type, ObjectHandleOnStack keepAlive, ObjectHandleOnStack assemblyLoadContext)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at System.TypeNameParser.ResolveType(Assembly assembly, String[] names, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
   at System.TypeNameParser.ConstructType(Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
   at System.TypeNameParser.GetType(String typeName, Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError)
   at Microsoft.Data.SqlClient.SqlConnection.CheckGetExtendedUDTInfo(SqlMetaDataPriv metaData, Boolean fThrow)
   at Microsoft.Data.SqlClient.SqlDataReader.GetFieldTypeInternal(_SqlMetaData metaData)
   at Microsoft.Data.SqlClient.SqlDataReader.BuildSchemaTable()
   at Microsoft.Data.SqlClient.SqlDataReader.GetSchemaTable()
   at Program.<Main>$(String[] args) in C:\Code\Demo\SqlClient5Crash\Program.cs:line 38

```

Project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
        <PackageReference Include="Microsoft.Data.SqlClient" Version="5.0.0" />
	<PackageReference Include="Microsoft.SqlServer.DacFx" Version="160.6161.0" />
  </ItemGroup>

</Project>

```

Program.cs:

```csharp
using Microsoft.Data.SqlClient;
using System.Data;

using var connection = new SqlConnection("Data Source=.\\SQLEXPRESS;Initial Catalog=Northwind;Integrated Security=true;Encrypt=false");
connection.Open();

using var dmlCommand = connection.CreateCommand();

dmlCommand.CommandText = @"CREATE OR ALTER PROCEDURE [dbo].[SpecialTypes] (
        @Parents hierarchyid,
        @geo geography,
        @geom geometry) 
        AS
        BEGIN
            SELECT 1 AS Id, @geo AS Geo, @Parents AS Parents, @geom as Geom;
        END;";

dmlCommand.ExecuteNonQuery();

using var sqlCommand = connection.CreateCommand();

using var command = connection.CreateCommand();

command.CommandText = "[dbo].[SpecialTypes]";
command.CommandType = CommandType.StoredProcedure;

var param1 = new SqlParameter("@Parents", DBNull.Value);
command.Parameters.Add(param1);

var param2 = new SqlParameter("@geo", DBNull.Value);
command.Parameters.Add(param2);

var param3 = new SqlParameter("@geom", DBNull.Value);
command.Parameters.Add(param3);

using var schemaReader = command.ExecuteReader(CommandBehavior.SchemaOnly);

using var schemaTable = schemaReader.GetSchemaTable();

foreach (DataRow row in schemaTable.Rows)
{
    Console.WriteLine(row["ColumnName"].ToString());
}
```

Non-failing cases:

```xml
  <ItemGroup>
        <PackageReference Include="Microsoft.Data.SqlClient" Version="4.1.0" />
	<PackageReference Include="Microsoft.SqlServer.DacFx" Version="160.6161.0" />
  </ItemGroup>
```

```xml
  <ItemGroup>
        <PackageReference Include="Microsoft.Data.SqlClient" Version="5.0.0" />
  </ItemGroup>
```

Could be related to the fact that DacFx includes a Microsoft.SqlServer.Types.dll file, but I am just guessing here.

@dzsquared What are the plans for adopting SqlClient 5 in DacFx?

**Comment by dzsquared** [comment]
There will be a DacFx preview out with SqlClient 5 this fall - we're narrowing down the date now.

**Comment by JRahnama** [comment]
@ErikEJ should I transfer this to DacFx repo?

**Comment by ErikEJ** [comment]
Not sure. I am not calling any DacFX code...

Seems more like dll hell v2.

**Comment by cheenamalhotra** [comment]
The issue is due to type conflict as MDS 5 now uses types from MS.SqlServer.Server namespace.
That's why apps cannot take both DacFx and MDS 5 dependencies at the same time, until new version of DacFx is released.

Since work is acknowledged and in progress, its a matter of time!

**Comment by ErikEJ** [comment]
@cheenamalhotra thanks. That was also my understanding. 

My real app actually depends on EF Core 7 which in turn depends on MDS 5. 

Fingers crossed for a compatible DacFX  release before November.
