### ISSUE TITLE
'Authentication=Active Directory Default' Login Fails For SPA Site Running VS2022

### ISSUE THREAD

**Issue by summitabrown** [dotnet/SqlClient#1770]
### Describe the bug
I am running a React SPA site locally in VS 2022. I cannot establish a connection to an Azure SQL Database. I have another web app that is an ASP.NET core MVC site and it works successfully in VS 2022. I have narrowed it down to being related to the SPA site.

### Exception:
```
Exception message: Login failed for user '<token-identified principal>'.
Stack Trace:
   at Microsoft.Data.ProviderBase.DbConnectionPool.CheckPoolBlockingPeriod(Exception e)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternal(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(Enumerator enumerator)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Boolean& found)
   at lambda_method31(Closure , QueryContext )
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)

```

### Expected behavior
Establish connection to database just like a regular ASP.NET core web application does.

### Further technical details
Microsoft.Data.SqlClient version: 5.0.0 and 4.0.0
.NET target: 6
SQL Server version: Azure SQL Database
Operating system: Windows 10/VS 2022

**Comment by ErikEJ** [comment]
Are you using System assigned or user assigned?

If system assigned, are you sure the credentials are correct in the user database? 

They will be broken if you have rebuilt the Web app.

**Comment by summitabrown** [comment]
> Are you using System assigned or user assigned?
> 
> If system assigned, are you sure the credentials are correct in the user database?
> 
> They will be broken if you have rebuilt the Web app.

I am having the problem when running the app locally in VS 2022. When the app is running in Azure under an system identity it works.

I would expect the `VisualStudioCredential` piece of the `Active Directory Default` scheme to kick in here but it seems like it isn't.

**Comment by summitabrown** [comment]
Just to follow up I have both the System Identity and an AD Group containing my user account setup in the database. And when I run a different ASP.NET core app locally that isn't doing a SPA proxy it works correctly using my user account

**Comment by summitabrown** [comment]
This is all set. Restarted Visual studio and it worked. 🤷
