### ISSUE TITLE
"Internal connection fatal error" when connecting from a docker container

### ISSUE THREAD

**Issue by a510** [dotnet/SqlClient#1774]
### Describe the bug
I get "Internal connection fatal error" when I try to connect to SQL Server from ASPNET docker container.
I've seen [this issue](https://github.com/dotnet/SqlClient/issues/81) and tried [kihamo's workaround](https://github.com/dotnet/SqlClient/issues/81#issuecomment-399375323) but nothing worked, although the same project works fine on an Azure Database.

```
Exception message:
System.InvalidOperationException: Internal connection fatal error.
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.CompleteLogin(Boolean enlistOK)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
```

### To reproduce
1. Create a new dotnet 6.0 WebAPI project with docker and swagger enabled
1. Add Microsoft.EntityFrameworkCore.SqlServer (v. 6.0.9) nuget package
1. Add `DbContext` and entity classes
1. Add endpoint that fetches data from the EFCore DbContext
1. Run the application on docker and hit this endpoint.

Here's a sample project to reproduce the issue.
[DockerEFSample.zip](https://github.com/dotnet/SqlClient/files/9654236/DockerEFSample.zip)

### Expected behavior
Data returned successfully

### Further technical details
Microsoft.Data.SqlClient version: (v 2.1.4)
.NET target: (v. Core 6.0.304)
SQL Server version: (v. 16.0.700.4)

**Comment by lcheunglci** [comment]
Thanks for bring this issue to our attention, we'll look into it.
