### ISSUE TITLE
Invalid TDS Stream errors with Encrypt=Strict when executing Stored Procedures

### ISSUE THREAD

**Issue by cheenamalhotra** [dotnet/SqlClient#1807]
### Describe the bug
With Strict Encryption (TDS 8.0) enabled, executing stored procedures leads to TDS stream errors.

```
Unhandled exception. Microsoft.Data.SqlClient.SqlException (0x80131904): The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Parameter 1 (""): Data type 0x00 is unknown.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader(Boolean isInternal, Boolean forDescribeParameterEncryption)
   at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteReader(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteReaderInternal(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteReaderAsync(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteReaderAsyncCallback(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
ClientConnectionId:f1420c8a-c31c-4003-a8b1-779930b963fd
Error Number:8009,State:1,Class:16
```

### To reproduce

```c#
    public static async Task Main(string[] args)
    {
        using (SqlConnection connection = new SqlConnection(new SqlConnectionStringBuilder()
        {
            DataSource = "<servername>",
            IntegratedSecurity = true,
            Encrypt = SqlConnectionEncryptOption.Strict,
        }.ConnectionString))
        {
            await connection.OpenAsync();
            using (SqlCommand command = connection.CreateCommand())
            {
                command.CommandText = "sp_who";
                command.CommandType = System.Data.CommandType.StoredProcedure;
                using (SqlDataReader reader = await command.ExecuteReaderAsync().ConfigureAwait(false))
                {
                    while (await reader.ReadAsync())
                    {
                        Console.WriteLine(reader.GetValue(0) + " | " + reader.GetValue(1) + " | " + reader.GetValue(2));
                    }
                }
            }
        }
    }
```

### Expected behavior
Show results as it would when running with TDS 7.x or Encrypt=Mandatory/Optional.

### Further technical details
Microsoft.Data.SqlClient version: 5.0.1
.NET target: .NET 6
SQL Server version: SQL 2022 Preview
Operating system: Windows 11

**Comment by JRahnama** [comment]
@cheenamalhotra Thank you for reporting this. Seems like this is a bug on the server side and it is being investigated.

**Comment by DavoudEshtehari** [comment]
It works without exception using the following configuration:
```
Connection Stiring: `Data Source=<server name>;User ID=sa;Password=***;Encrypt=Strict;Host Name In Certificate=<HNIC>;`

(Praveen Server)
Microsoft SQL Server 2022 (RTM) - 16.0.5016.0 (X64)
        Oct 27 2022 13:44:23 2022.0160.5016.00
        Copyright (C) 2022 Microsoft Corporation
        Enterprise Edition (64-bit) on Windows Server 2022 Datacenter Azure Edition 10.0 <X64> (Build 20348: ) (Hypervisor)

OS: Windows 11 Version 21H2 (OS Build 22000.1098)

Microsoft.Data.SqlClient version: 5.0.1
.NET target: .NET 6
```

Can you verify if it breaks with the same server on your machine, and provide more details if it needs a specific configuration to reproduce, please?

**Comment by cheenamalhotra** [comment]
We can close this, thanks!
