### ISSUE TITLE
DllNotFoundException for Microsoft.Data.SqlClient.SqlConnection.Open on .NET6

### ISSUE THREAD

**Issue by wzm199309** [dotnet/SqlClient#1833]
### Describe the bug
We are migrating Azure SQL IaaS Agent project from .NET fx to .NET6 and using Microsoft.Data.SqlClient to replace System.Data.SqlClient usage, however DllNotFoundException raised at Microsoft.Data.SqlClient.SqlConnection.Open().

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
[Warning] ServerConfigurationsManagementConfigureFailure: System.Exception: SQL Server configuration update failed.
 ---> System.DllNotFoundException: Dll was not found.
   at Microsoft.Data.SqlClient.SNINativeMethodWrapper.UnmanagedIsTokenRestricted(IntPtr token, Boolean& isRestricted)
   at Microsoft.Data.Win32NativeMethods.IsTokenRestrictedWrapper(IntPtr token)
   at Microsoft.Data.ProviderBase.DbConnectionPoolIdentity.GetCurrentNative()
   at Microsoft.Data.ProviderBase.DbConnectionPoolIdentity.GetCurrent()
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open()
   at Microsoft.SqlServer.Management.PermissionControl.PermissionControlManager.<>c__DisplayClass20_0.<GetConnection>b__0()
   at System.Security.Principal.WindowsIdentity.<>c__DisplayClass73_0.<RunImpersonatedInternal>b__0(Object <p0>)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Security.Principal.WindowsIdentity.RunImpersonatedInternal(SafeAccessTokenHandle token, Action action)
   at System.Security.Principal.WindowsIdentity.RunImpersonated(SafeAccessTokenHandle safeAccessTokenHandle, Action action)
   at Microsoft.SqlServer.Management.IaaSUtility.ImpersonationUtility.Run(Int32 processId, Action callback)
   at Microsoft.SqlServer.Management.PermissionControl.PermissionControlManager.GetConnection(String instancename, Boolean useLogger)
   at Microsoft.SqlServer.Management.PermissionControl.PermissionControlManager.ResetTargetQuerySvcLogin()
   at Microsoft.SqlServer.Management.PermissionControl.PermissionControlManager..ctor()
   at Microsoft.SqlServer.Management.PermissionControl.PermissionControlManager.get_Instance()
   at Microsoft.SqlServer.Management.ServerConfigurationsManagement.ServerConfigurationsPluginManager.UpdateConfigurations(PublicSettings publicSettings, SecureString protectedSettingsCertificateThumbprint, SecureString protectedSettings)
   --- End of inner exception stack trace ---
```

### To reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
```

### Further technical details
Microsoft.Data.SqlClient version: (5.0.1)
.NET target: (Net6)
SQL Server version: (SQL Server 2019)
Operating system: (Windows Server 2019)

**Additional context**
Both local console app run and self-contained deployment run failed with same issue, adding /p:IncludeNativeLibrariesForSelfExtract=true wont help

**Comment by lcheunglci** [comment]
Thanks @wzm199309 for bringing this issue to our attention.  We're currently in a middle of a release. We'll get back to you soon.  From a brief glance at the call stack, it looks like it's not finding the `Microsoft.Data.SqlClient.SNI.runtime` DLLs required, please check that the bin `runtimes` folder contains the `win-x64` and `win-x86` contains the `Microsoft.Data.SqlClient.SNI.dll`

**Comment by wzm199309** [comment]
@lcheunglci  thanks we are building our project as x64 self-contained way, I checked the Microsoft.Data.SqlClient.SNI.runtime is there, in this case do we need 32bit version of Microsoft.Data.SqlClient.SNI.runtime ?

**Comment by JRahnama** [comment]
@wzm199309 have you checked the [cheat-sheet](https://github.com/dotnet/SqlClient/blob/main/porting-cheat-sheet.md) for migrating from S.D.SqlClient to M.D.SqlClient? That may solve your issue.

**Comment by wzm199309** [comment]
@JRahnama  @lcheunglci  yes I checked that but there is no mentioning about dll missing issue there, from the callstack this is certain SNI loading issue with MDS, please help verifying it since we are hardly blocked by this issue.

**Comment by JRahnama** [comment]
@wzm199309 is it possible to share a small repro?

**Comment by wzm199309** [comment]
@JRahnama  sure a code snippet would be like this:// Get service name
string sqlServiceName = SqlInstanceHelper.GetSqlServiceName("MSSQLServer", SqlInstanceHelper.SqlServiceType.SqlServer);

// We require process id to impersonate.
int sqlServiceProcessId = ServiceHelper.GetProcessIdByService(sqlServiceName);

SqlConnectionStringBuilder builder = new SqlConnectionStringBuilder
{
    DataSource = SqlInstanceHelper.GetSqlConnectionName(instancename),
    IntegratedSecurity = true,
    ApplicationName = ServiceConstants.ExtensionHandlerName,
    MultipleActiveResultSets = true,
    Pooling = false
};

SqlConnection sqlConnection = new SqlConnection(builder.ConnectionString);

// Open connection while in impersonated mode
ImpersonationUtility.Run(
    sqlServiceProcessId,
    () => { sqlConnection.Open(); });

**Comment by wzm199309** [comment]
@lcheunglci provided a code snippet that can repro this issue, do we need to provide other info needed?

**Comment by lcheunglci** [comment]
Hi @wzm199309 , you mentioned that you're building/publishing as `self-contained` console application. 

I was reading #1835 and I feel like it might be a similar issue.  Can you downgrade from M.D.S. `5.0.1` to M.D.S. `4.1.1` and see if you're still getting this DLL not found exception, and I feel that the sample snippet you provide might not be the issue but the publishing options, so could you provide a sample repro project?  Thanks.

**Comment by wzm199309** [comment]
Thanks for @lcheunglci 's hard work with this issue, we identified the bug is caused by that for self-contained app, its static library(contains sql call) wont be able to load native sni.dll nor M.D.S.SNI.dll during runtime, when sql call is under the impersonation context.   Either copy SNI.dll/M.D.S.SNI.dll or turns sni usage into managed SNI (AppContext.SetSwitch("Switch.Microsoft.Data.SqlClient.UseManagedNetworkingOnWindows",true)) which is part of the M.D.S can fix this issue.
