### ISSUE TITLE
dotnet publish command line started showing ADO issues at runtime

### ISSUE THREAD

**Issue by yogigrantz** [dotnet/SqlClient#1835]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

All along I have been able to publish a single executable console programs with command line like this: 

`dotnet publish <ProgramName> -o C:\Temp\publish2 /p:PublishSingleFile=true /p:PublishTrimmed=true --runtime win-x64` 

And the executable would run without any problem, even if it uses Microsoft.Data.SqlClient library. I believe the last time it worked was with Microsoft.Data.SqlClient 5.0.0 

Now, when I run that dotnet command line and the program is trying to Open a SQL connection, I got this error:

SourceObject: Microsoft.Data.SqlClient
	Type: TypeLoadException
   StackTrace: (shown in the exception error section)

### Expected Behavior

It should just open the SqlConnection without any error. 

When I publish with Visual Studio with Framwork-dependent x64 to produce a single executable, it runs fine and would open the SqlConnection without any error.

I believe the dotnet command line publish should produce the exact same executable with Visual Studio publish. This is important, in case Visual Studio publish has issues then we should be able to fall back to the command line publish

### Steps To Reproduce

Take any console program that uses Microsoft.Data.SqlClient 5.0.1, SqlConnection, and .Open() method, and publish it with that command line. Then run that executable and see if the Open() method would open sql connection successfully

### Exceptions (if any)

at Microsoft.Data.SqlClient.SNINativeMethodWrapper.SNIAddProvider(SNIHandle pConn, ProviderEnum ProvNum, AuthProviderInfo& pInfo)
   at Microsoft.Data.SqlClient.TdsParserStateObjectNative.EnableSsl(UInt32& info, Boolean tlsFirst)
   at Microsoft.Data.SqlClient.TdsParser.EnableSsl(UInt32 info, SqlConnectionEncryptOption encrypt, Boolean integratedSecurity)
   at Microsoft.Data.SqlClient.TdsParser.ConsumePreLoginHandshake(SqlConnectionEncryptOption encrypt, Boolean trustServerCert, Boolean integratedSecurity, Boolean& marsCapable, Boolean& fedAuthRequired, Boolean tlsFirst)
   at Microsoft.Data.SqlClient.TdsParser.Connect(ServerInfo serverInfo, SqlInternalConnectionTds connHandler, Boolean ignoreSniOpenTimeout, Int64 timerExpire, SqlConnectionString connectionOptions, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open()

### .NET Version

.net 6

**Comment by ErikEJ** [comment]
What .NET SDKs do you have installed?

**Comment by JRahnama** [comment]
@yogigrantz I tested the repro and got no issue. I only got some warnings similar to below:
![image](https://user-images.githubusercontent.com/32077152/201442736-fa01e646-4633-4d5b-a1cd-700f2ad4a2a5.png)

it might be related to the fact that I have installed net7. Tests could be done with and without that.

**Comment by JRahnama** [comment]
Ignore my previous comment I was able to repro the issue.

**Comment by yogigrantz** [comment]
> What .NET SDKs do you have installed?

@ErikEJ : I have these installed in my machine: 

.NET SDKs installed:
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.105 [C:\Program Files\dotnet\sdk]
  3.1.200 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.300 [C:\Program Files\dotnet\sdk]
  5.0.411 [C:\Program Files\dotnet\sdk]
  6.0.402 [C:\Program Files\dotnet\sdk]

**Comment by lcheunglci** [comment]
I found that this issue was introduced from `5.0preview2` to `5.0preview3`, and is currently investigating the differences that may have caused this regression.

**Comment by yogigrantz** [comment]
Good finding! thank you @Icheunglci 👍🏻  - I suppose it will be readded in the next build?

**Comment by lcheunglci** [comment]
Otherwise, if you cannot downgrade to to a lower version at the moment, a workaround is to reference the `Managed SNI` instead of the `Native SNI` by specifying the following: `AppContext.SetSwitch("Switch.Microsoft.Data.SqlClient.UseManagedNetworkingOnWindows", true);` at the start of your app before you open a connection and you can check the [docs](https://learn.microsoft.com/en-us/sql/connect/ado-net/appcontext-switches?view=sql-server-ver16#enabling-managed-networking-on-windows) for more info.

**Comment by yogigrantz** [comment]
@lcheunglci : no worries, for now I can publish the console app / single .exe using VS 2022 Publish button. I could downgrade also, but I'd rather just use the publish button for now until the fix is released. Thank you so much for looking into this :)

**Comment by weberms** [comment]
Any updates on this issue?  I'm having the same error at runtime when using dotnet publish with v5.1.1.  Downgrading to v4.1.1 solves the issue.

`System.TypeLoadException

at Microsoft.Data.SqlClient.SNINativeMethodWrapper.SNIAddProvider(SNIHandle pConn, ProviderEnum ProvNum, AuthProviderInfo& pInfo)
   at Microsoft.Data.SqlClient.TdsParserStateObjectNative.EnableSsl(UInt32& info, Boolean tlsFirst, String serverCertificateFilename)
   at Microsoft.Data.SqlClient.TdsParser.EnableSsl(UInt32 info, SqlConnectionEncryptOption encrypt, Boolean integratedSecurity, String serverCertificateFilename)
   at Microsoft.Data.SqlClient.TdsParser.ConsumePreLoginHandshake(SqlConnectionEncryptOption encrypt, Boolean trustServerCert, Boolean integratedSecurity, Boolean& marsCapable, Boolean& fedAuthRequired, Boolean tlsFirst, String serverCert)
   at Microsoft.Data.SqlClient.TdsParser.Connect(ServerInfo serverInfo, SqlInternalConnectionTds connHandler, Boolean ignoreSniOpenTimeout, Int64 timerExpire, SqlConnectionString connectionOptions, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open()
`

**Comment by yogigrantz** [comment]
@weberms  : so far the solution is to use Visual Studio "Publish" button instead of dotnet publish CLI. I keep my Microsoft.Data.SqlClient at 5.0.1 and whenever I need to publish a console app into a single executable, I use the Visual Studio built-in Publish button. For Web applications, where I don't need to publish into a single executable, I can still use dotnet publish command line (which I canned into my VSIX Tool, which in my case is under the Tools menu)

**Comment by weberms** [comment]
Thanks yogigrantz for the tips, however using VS to publish isn't an option as we need to build from command line on our CI server.

**Comment by yogigrantz** [comment]
@weberms  : Yes for CI/CD, so far Microsoft.Data.SqlClient 4.1 seems to be the latest version that works

**Comment by holajan** [comment]
Any updates on this?
I'm having the same issue with PublishTrimmed = true on .NET 7.
I can't use old Microsoft.Data.SqlClient 4.1, because EF Core 7 (Microsoft
.EntityFrameworkCore.SqlServer 7.0.1) uses Microsoft.Data.SqlClient (>= 5.0.1).

**Comment by yogigrantz** [comment]
OK with .net 6, Microsoft.Data.SqlClient 5.1.5, I was able to deploy a single-file executable with this command: 

dotnet publish (myAppName) -o C:\temp\publish /p:PublishSingleFile=true /p:PublishTrimmed=true --runtime win-x64

BUT, the strangest thing is, that I referenced to Microsoft.Data.SqlClient 5.1.5 in .csproj: 

`   <PackageReference Include="Microsoft.Data.SqlClient" Version="5.1.5" />
`

But when I checked my output folder, Microsoft.Data.SqlClient.SNI.dll is version 5.1.1.0 , not 5.1.5. What is going on here?

**Comment by ErikEJ** [comment]
@yogigrantz file version and package version is not the same thing

**Comment by yogigrantz** [comment]
@ErikEJ : but see when I check my local nuget repository: 

C:\Users\(me)\.nuget\packages\microsoft.data.sqlclient\5.1.5 , I saw that the dll have a different file signature: 

![MDS515](https://github.com/dotnet/SqlClient/assets/14880717/f458a49d-7b35-4c71-8f8e-e2d661d44552)

**Comment by yogigrantz** [comment]
worse yet, when I published with this command line: 

dotnet publish (myAppName) -o C:\temp\publish /p:PublishSingleFile=true /p:PublishTrimmed=true --runtime win-x64 

it does produce a single executable, but when I ran that executable, I would get this MDS exception error:

"   at Microsoft.Data.SqlClient.SNINativeMethodWrapper.SNIAddProvider(SNIHandle pConn, ProviderEnum ProvNum, AuthProviderInfo& pInfo)\r\n   at Microsoft.Data.SqlClient.TdsParserStateObjectNative.EnableSsl(UInt32& info, Boolean tlsFirst, String serverCertificateFilename)\r\n   at Microsoft.Data.SqlClient.TdsParser.EnableSsl(UInt32 info, SqlConnectionEncryptOption encrypt, Boolean integratedSecurity, String serverCertificateFilename)\r\n   at Microsoft.Data.SqlClient.TdsParser.ConsumePreLoginHandshake(SqlConnectionEncryptOption encrypt, Boolean trustServerCert, Boolean integratedSecurity, Boolean& marsCapable, Boolean& fedAuthRequired, Boolean tlsFirst, String serverCert)\r\n   at Microsoft.Data.SqlClient.TdsParser.Connect(ServerInfo serverInfo, SqlInternalConnectionTds connHandler, Boolean ignoreSniOpenTimeout, Int64 timerExpire, SqlConnectionString connectionOptions, Boolean withFailover)\r\n   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)\r\n   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)\r\n   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)\r\n   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool)\r\n   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)\r\n   at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)\r\n   at Microsoft.Data.SqlClient.SqlConnection.Open()\r\n   at  .... (my class library) 

But when I published the project with VS2022 publish button, the executable works fine. Either way, Microsoft.Data.SqlClient.SNI File version 5.1.1 is produced in the output folder

**Comment by David-Engel** [comment]
The Microsoft.Data.SqlClient and Microsoft.Data.SqlClient.SNI packages are independent with different files and versions.

**Comment by yogigrantz** [comment]
ok if the File version is irrelevant that's one thing, but the other thing is, when we publish with this command:

dotnet publish (myAppName) -o C:\temp\publish /p:PublishSingleFile=true /p:PublishTrimmed=true --runtime win-x64 

it does produce a single executable, except when we run that executable it throw exception at Microsoft.Data.SqlClient.SNINativeMethodWrapper.SNIAddProvider shown above

**Comment by David-Engel** [comment]
The exception you pasted above is just the stack trace. What was the exception message?

**Comment by yogigrantz** [comment]
The exception message is blank. All I got was just the stack trace. 

Here is a sample source code to recreate this error: 

`using Microsoft.Data.SqlClient;
using Newtonsoft.Json;
using System.Data;

try
{

    using (SqlConnection conn = new SqlConnection("server=******;database=******;user id=******;Password=******;TrustServerCertificate=True"))
    {
        conn.Open();
        using (SqlCommand sqlcmd = new SqlCommand("SampleSPName", conn))
        {
            sqlcmd.CommandType = System.Data.CommandType.StoredProcedure;
            using (DataSet ds = new DataSet())
            {
                using (SqlDataAdapter sqlAdp = new SqlDataAdapter(sqlcmd))
                {
                    int rtnVal = sqlAdp.Fill(ds, "Result");
                    if (ds?.Tables.Count > 0)
                    {
                        Console.WriteLine(JsonConvert.SerializeObject(ds.Tables[0], Formatting.Indented));
                    }
                }
            }
        }
        if (conn.State == System.Data.ConnectionState.Open)
        {
            conn.Close();
        }
    }
}
catch (Exception ex)
{
    Console.WriteLine($"Exception message: {ex.Message.ToString()}");
    Console.WriteLine($"Stack Trace: {ex.StackTrace.ToString()}");
}
Console.ReadLine();`

publish that with this command: 

dotnet publish (myAppName) -o C:\temp\publish /p:PublishSingleFile=true /p:PublishTrimmed=true --runtime win-x64 

and you will see the stack trace but no Exception message

**Comment by yogigrantz** [comment]
@David-Engel  ; you are correct, when /p:PublishTrimmed=true is removed it works. 

Working command line:
dotnet publish (myAppName) -o C:\temp\publish /p:PublishSingleFile=true  --runtime win-x64

I will close this ticket now. Thank you

**Comment by holajan** [comment]
This is not a solution, as we know it works without trimming. But I need the output single file to be trimmed.

Further I have <PublishTrimmed>true</PublishTrimmed> in the .csproj, so setting /p:PublishTrimmed=true in the publish command line is irrelevant and the error remains the same.

**Comment by yogigrantz** [comment]
@David-Engel : Apologies, since PublishTrimmed=true is a requirement in some cases, then this case needs to be reopened to make sure the dotnet publish with /p:PublishTrimmed=true option would produce a working executable that access SQL Server database through Microsoft.Data.SqlClient 5.*

**Comment by JRahnama** [comment]
Closing as a duplicate of #822

**Comment by jdpj518** [comment]
This remains an issue in .NET 9 and Microsoft.Data.SqlClient 6.1.2.  I just spent 8 hours trying to diagnose why my SqlConnection.OpenAsync method was failing at Microsoft.Data.SqlClient.SNINativeMethodWrapper.SNIAddProvider (Stack trace is below).  Spent hours trying to diagnose why this was happening, built test apps to cut out all other logic and dependencies.  finally found this issue and republished without trimming code, and viola! it works.  My headache wishes I had found this sooner.  What a painful 8 hours.  I would please ask if we can get the Trim Code feature working in a way that doesn't break the app.  Thank you, and thanks to the comments here that identified Trim Code as the culprit.

Stack Trace:
   at Microsoft.Data.SqlClient.SNINativeMethodWrapper.SNIAddProvider(SNIHandle pConn, ProviderEnum ProvNum, AuthProviderInfo& pInfo)
   at Microsoft.Data.SqlClient.TdsParserStateObjectNative.EnableSsl(UInt32& info, Boolean tlsFirst, String serverCertificateFilename)
   at Microsoft.Data.SqlClient.TdsParser.EnableSsl(UInt32 info, SqlConnectionEncryptOption encrypt, Boolean integratedSecurity, String serverCertificateFilename)
   at Microsoft.Data.SqlClient.TdsParser.ConsumePreLoginHandshake(SqlConnectionEncryptOption encrypt, Boolean trustServerCert, Boolean integratedSecurity, Boolean& marsCapable, Boolean& fedAuthRequired, Boolean tlsFirst, String serverCert)
   at Microsoft.Data.SqlClient.TdsParser.Connect(ServerInfo serverInfo, SqlInternalConnectionTds connHandler, Boolean ignoreSniOpenTimeout, Int64 timerExpire, SqlConnectionString connectionOptions, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location ---
   at WFMDataFlow.Utilities.ConfigPackage.GetAPIInfo() in {My Project Path}\ConfigPackage.cs:line 58
