### ISSUE TITLE
Microsoft.Data.SqlClient.SqlException (0x80131904): A transport-level error has occurred when receiving results from the server. (provider: TCP Provider, error: 0 - Success)

### ISSUE THREAD

**Issue by devtng** [dotnet/SqlClient#1852]
Hello,

On 11/19/2022, we starting having issues with our Azure Linux Web App connecting to our Azure SQL DB.
The issue is that it only fails about 80% of the time, if you refresh enough you will eventually get to the webpage.
We are able to connect to SQL server/db via SSMS and Azure Data Studio just fine and query all the tables.
The error is not very helpful since it has no error code or description like TLS/SSL handshake failed, etc...
We have also tried updating the Data.SqlClient to 4.1.1 but still have no luck.

Any help is appreciated. Thanks.

> 
> Microsoft.Data.SqlClient.SqlException (0x80131904): A transport-level error has occurred when receiving results from the server. (provider: TCP Provider, error: 0 - Success)
>    at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
>    at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
>    at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
>    at Microsoft.Data.SqlClient.TdsParserStateObject.ThrowExceptionAndWarning(Boolean callerHasConnectionLock, Boolean asyncClose)
>    at Microsoft.Data.SqlClient.TdsParserStateObject.ReadSniError(TdsParserStateObject stateObj, UInt32 error)
>    at Microsoft.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync()
>    at Microsoft.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()
>    at Microsoft.Data.SqlClient.TdsParserStateObject.TryPrepareBuffer()
>    at Microsoft.Data.SqlClient.TdsParserStateObject.TryReadByte(Byte& value)
>    at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
>    at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
>    at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
>    at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
>    at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
>    at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
>    at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
>    at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
>    at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
>    at System.Data.Common.DbCommand.ExecuteReader()
>    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
>    at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
>    at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
>    at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
>    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
>    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
>    at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
>    at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)

**Comment by ErikEJ** [comment]
Updating from?

If you need production support there are multiple paid options? 

Did you change anything in your app on that date?

Have you tried 5.1 ?

**Comment by devtng** [comment]
> 

Hi Erik,

This is not a production env, but in our testing env only.
Nope, no code updates or any configurations. We even tried rolling back to a version from an older date and still had the same issue.

We upgraded from 1.1.4. This morning we updated to 5.0.1 and still no luck.

**Comment by ErikEJ** [comment]
Raise an issue with Azure SQL support.

**Comment by JRahnama** [comment]
Closing the issue as it is external and no activity. Feel free to comment here or open a new issue.
