### ISSUE TITLE
Wrong property being read from /etc/os-release to define platform support

### ISSUE THREAD

**Issue by raibtoffoletto** [dotnet/SqlClient#1954]
### Describe the bug
When using EF with SqlServer driver under some linux distributions,  an exception is thrown saying that Microsoft.Data.SqlClient is not supported despite the full platform support of dotnet.

I saw this behavior with the same versions of dotnet [6.0.113] and EF [7.0.3] in two ubuntu systems that have dotnet installed from the same ubuntu official repository. The only difference is that one is a basic ubuntu server instalation and the other is a desktop distribution fully based on ubuntu called PopOS.

I believe that dotnet is reading the `/etc/os-release` property `ID` to define the platform when it should be reading the `ID_LIKE` because when I altered the ID property to `ubuntu` in the PopOS system, the DLL behaved as expected.

Here are BOTH `/etc/os-release` files.

```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
--------------------------------------------
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
UBUNTU_CODENAME=jammy
```

### As you can see, the correct platform definition is in the `ID_LIKE`, so I suggest merging both to compare and define if the system is supported or not.

My exception:

```
Exception message: Microsoft.Data.SqlClient is not supported on this platform
Stack trace:
System.PlatformNotSupportedException: Microsoft.Data.SqlClient is not supported on this platform.
         at Microsoft.Data.SqlClient.SqlConnectionStringBuilder..ctor(String connectionString)
         at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerConnection.<>c.<get_IsMultipleActiveResultSetsEnabled>b__7_0(String cs)
         at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
         at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerConnection.get_IsMultipleActiveResultSetsEnabled()
         at Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerCompiledQueryCacheKeyGenerator.GenerateCacheKey(Expression query, Boolean async)
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
         at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
         at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
         at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
         at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
         at @@MYPROJECT.Controller@@
         at lambda_method1(Closure , Object , Object[] )
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

```

### To reproduce

Have a Ubuntu system and derivative distro. With the same project using EF and same dotnet version, an exception is thrown in the sub-distro.

### Expected behavior

They should work as the same in both platforms because the sub-distro HAS A CORRECT platform definition.

### Further technical details
Microsoft.Data.SqlClient version: 5.0.1
.NET target: Core 6.0.113
SQL Server version: 2022
Operating system: Ubuntu 22.04 AND PopOS based on 22.04 with same official repos

**Comment by lcheunglci** [comment]
Thanks @raibtoffoletto for bring this to our attention and providing a suggestion to expand the support for the linux distros. We'll have to take a look at the implementation on how the check is performed and get back to you soon.

**Comment by raibtoffoletto** [comment]
Thank you! 
In my quick search I couldn't find the implementation, only mentions to the exception, so if this is not specific to the SqlClient I'm happy to open an issue upstream as well.

**Comment by raibtoffoletto** [comment]
Thanks @lcheunglci . 
So if I understand who implements this is the runtime, so I'll open an issue upstream.
Cheers, R.
