### ISSUE TITLE
"Shared Memory Provider, error: 15 - Function not supported" with Encrypt=Strict

### ISSUE THREAD

**Issue by cheenamalhotra** [dotnet/SqlClient#1956]
### Describe the bug
Randomly saw this error on connecting with SQL 2022 with 'Strict' encryption.

`A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: Shared Memory Provider, error: 15 - Function not supported)`

```
Exception message: System.ComponentModel.Win32Exception (50): The request is not supported.
Stack trace:Microsoft.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: Shared Memory Provider, error: 15 - Function not supported)
 ---> System.ComponentModel.Win32Exception (50): The request is not supported.
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParserStateObject.ThrowExceptionAndWarning(Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParserStateObject.ReadSniError(TdsParserStateObject stateObj, UInt32 error)
   at Microsoft.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync()
   at Microsoft.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()
   at Microsoft.Data.SqlClient.TdsParser.ConsumePreLoginHandshake(SqlConnectionEncryptOption encrypt, Boolean trustServerCert, Boolean integratedSecurity, Boolean& marsCapable, Boolean& fedAuthRequired, Boolean tlsFirst, String serverCert)
   at Microsoft.Data.SqlClient.TdsParser.Connect(ServerInfo serverInfo, SqlInternalConnectionTds connHandler, Boolean ignoreSniOpenTimeout, Int64 timerExpire, SqlConnectionString connectionOptions, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass48_0.<CreateReplaceConnectionContinuation>b__0(Task`1 _)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass30_0.<<OpenAsync>b__0>d.MoveNext() in /_/src/Microsoft.SqlTools.ManagedBatchParser/ReliableConnection/ReliableSqlConnection.cs:line 313
--- End of stack trace from previous location ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in E:\sts\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 686
ClientConnectionId:ff9b25b9-b759-4e83-bde1-50c264efe4b1
Error Number:50,State:0,Class:20
```

### To reproduce

Connection string:
`Server=localhost\<SQL 2022 instance>; Integrated Security=true; Encrypt=Strict; TrustServerCertificate=false; Pooling=no;`

Just connect. Error went away on connecting again.

### Expected behavior
No error expected.

### Further technical details
Microsoft.Data.SqlClient version: v5.1.0
.NET target: .NET 7.0
SQL Server version: SQL Server 2022
Operating system: Windows 11

**Comment by lcheunglci** [comment]
Hi @cheenamalhotra, thanks for bringing this to our attention and for the stacktrace.  I see that you're running the latest MDS LTS version and on Windows 11. The exception seems to be thrown from the NativeSNI. As you mentioned, this randomly occurs, and I have not seen this error before and on the [draft TDS8 test PR](https://github.com/dotnet/SqlClient/pull/1891), it was on hold pending to a patch for Sql Server 2022, but I can revise it so it can cover this use case if it could be consistently reproduced.  I was wondering if this also occurs on the [ManagedSNI on Windows](https://learn.microsoft.com/en-us/sql/connect/ado-net/appcontext-switches?view=sql-server-ver16#enabling-managed-networking-on-windows) otherwise, I may need to get a memory dump and have the [eventsource trace logs](https://learn.microsoft.com/en-us/sql/connect/ado-net/enable-eventsource-tracing?view=sql-server-ver16) to figure out how it got into that state. Thanks!

**Comment by cheenamalhotra** [comment]
From event source logs, I don't have much right now, but I can post what I got in case it helps:

```
<prov.DbConnectionHelper.ConnectionString_Set|API> 9, 'Data Source=localhost\MSSQLSERVER02;Integrated Security=True;Pooling=False;Connect Timeout=30;Encrypt=Strict;Trust Server Certificate=False;Application Name=azdata-GeneralConnection;Connect Retry Count=1;Connect Retry Interval=10'
<prov.DbConnectionHelper.ConnectionString_Get|API> 9
<sc.SqlConfigurableRetryLogicManager.ConnectionProvider|INFO> Requested the ConnectionProvider value.
TdsParserStateObjectFactory.CreateTdsParserStateObject | Info | AppContext switch 'Switch.Microsoft.Data.SqlClient.UseManagedNetworkingOnWindows' not enabled, native networking implementation will be used.
TdsParser.Connect | SEC | Connection Object Id 14, Authentication Mode: SqlPassword
TdsParser.Connect | SEC | SSPI or Active Directory Authentication Library loaded for SQL Server based integrated authentication
SqlConnection.OpenAsyncRetry | Info | Object Id 9
<sc.TdsParser.Connect|SEC> Sending prelogin handshake
<sc.TdsParser.SendPreLoginHandshake|INFO> ClientConnectionID ff9b25b9-b759-4e83-bde1-50c264efe4b1, ActivityID e05033ef-6723-4239-8f58-abede33ea9e6:1
<sc.TdsParser.Connect|SEC> Consuming prelogin handshake
SqlError.ctor | ERR | Info Number 50, Error State 0, Error Class 20, Error Message 'A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: Shared Memory Provider, error: 15 - Function not supported)', Procedure 'None', Line Number 0
<sc|ActiveDirectoryAuthenticationTimeoutRetryHelper|GetCachedToken|Info>Retrieved cached token null.
<sc|ActiveDirectoryAuthenticationTimeoutRetryHelper|CheckCanRetry|Error>Cannot retry when cached token is null.
<sc.SqlInternalConnectionTds.LoginFailure|RES|CPOOL> 14
```

_P.S. `Authentication Mode: SqlPassword` is always printed in logs in .NET Core for Integrated Auth as well which is misleading._

**Comment by cheenamalhotra** [comment]
I finally got it reproduced consistently, it's easier than I thought.. :(
The repro involves opening 2 non-pooled connections back to back with **2 different server instances** using Native SNI.
Happens on both .NET Framework and .NET Core.

```csharp
string local1ConnString = "Server=localhost\\MSSQLSERVER01;Integrated Security=true;Encrypt=Strict;Pooling=False;";
string local2ConnString = "Server=localhost\\MSSQLSERVER02;Integrated Security=true;Encrypt=Strict;Pooling=False;";
try
{
    using SqlConnection conn1 = new(local1ConnString);
    await conn1.OpenAsync();
    await Console.Out.WriteLineAsync($"First connection opened successfully.");

    using SqlConnection conn2 = new (local2ConnString);
    await conn2.OpenAsync();
    await Console.Out.WriteLineAsync($"Second connection opened successfully.");
}
catch (Exception ex)
{
    await Console.Out.WriteLineAsync("Exception occurred: " + ex.Message);
}
```

It would log:

```log
First connection opened successfully.
Exception occurred: A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: Shared Memory Provider, error: 15 - Function not supported)
```

**Comment by v-chojas** [comment]
Does this only happen with two named instances, does it disappear if use tcp instead of shared memory?

**Comment by cheenamalhotra** [comment]
Yes, tcp works fine!

It does also reproduce when directly connecting with Named Pipes/Shared memory (default).
Also once connection is made with TCP, it works fine for the same instance next time with Named Pipes and shared memory protocols too.. 

I guess the reason it worked for me for first connection (noticed now) - was that only TCP was enabled and others were disabled.. but with Shared memory/Named Pipes enabled I get issue on first connection attempt.

**Comment by cheenamalhotra** [comment]
Closing as this has been addressed with latest Native SNI version in [MDS 6.0.1](https://www.nuget.org/packages/Microsoft.Data.SqlClient/6.0.1).
