### ISSUE TITLE
Exception from HRESULT: 0x8007000B

### ISSUE THREAD

**Issue by Patresko** [dotnet/SqlClient#1994]
Im using Window 11 ARM with Paralles on Macbook M1 Pro.

Im not able to attach SQL server in Visual Studio.

```
===================================

An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B) (Microsoft.Data.SqlClient)

------------------------------
Program Location:

   at Microsoft.Data.SqlClient.SNINativeManagedWrapperX64.UnmanagedIsTokenRestricted(IntPtr token, Boolean& isRestricted)
   at Microsoft.Data.Win32NativeMethods.IsTokenRestrictedWrapper(IntPtr token)
   at Microsoft.Data.ProviderBase.DbConnectionPoolIdentity.GetCurrent()
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
   at Microsoft.VisualStudio.Data.Tools.SqlEditor.DataModel.SqlConnectionStrategy.ValidateConnection(UIConnectionInfo ci, IServerConnectionProvider server)
   at Microsoft.SqlServer.ConnectionDlg.UI.ConnectionDialogViewModel.OpenConnectionWithVerifier(IServerConnectionProvider serverConnectionProvider)
```

**Comment by JRahnama** [comment]
@Patresko is your application running for AnyCPU? Sounds like it is running in x64 while on ARM64.

**Comment by Patresko** [comment]
Yes I have 
`Platform target to Any CPU`
 But Im getting exception from above every time when Im trying to link project to the server. Also I have tried to create new .NET project and got same. Its seem there is something wrong with studio for ARM running on Mac.

**Comment by JRahnama** [comment]
@Patresko what version of VS2022 are you using? Can you also let us know about the M.D.Sqlclient version used in your application?

**Comment by Patresko** [comment]
Microsoft Visual Studio Community 2022 (ARM 64-bit) - Current
Version 17.5.4

Microsoft.Data.SqlClient
Version 7.0.5

**Comment by khrizenriquez** [comment]
Any update on this, im getting the same error in my local

**Comment by cheenamalhotra** [comment]
Closing as stale.
