### ISSUE TITLE
SQL Impersonation run failed with System.IO.FileLoadExceptions at .NET self-contained app.

### ISSUE THREAD

**Issue by WD1993** [dotnet/SqlClient#2028]
### Describe the bug
SQL Impersonation run failed with System.IO.FileLoadExceptions at .NET self-contained app.

System.TypeInitializationException: The type initializer for 'Microsoft.Data.SqlClient.SqlAuthenticationProviderManager' threw an exception.
 ---> **System.IO.FileLoadException:** 
File name: 'System.Configuration.ConfigurationManager, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at **Microsoft.Data.SqlClient.SqlAuthenticationProviderManager..cctor**()
   --- End of inner exception stack trace ---
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open()
   at Microsoft.SqlServer.Management.PermissionControl.PermissionControlManager.<>c__DisplayClass21_0.<GetConnection>b__0()
   at System.Security.Principal.WindowsIdentity.<>c__DisplayClass73_0.<RunImpersonatedInternal>b__0(Object <p0>)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Security.Principal.WindowsIdentity.RunImpersonatedInternal(SafeAccessTokenHandle token, Action action)
   at System.Security.Principal.WindowsIdentity.RunImpersonated(SafeAccessTokenHandle safeAccessTokenHandle, Action action)
   at Microsoft.SqlServer.Management.IaaSUtility.ImpersonationUtility.Run(Int32 processId, Action callback)

### To reproduce
Impersonation of SQL Run

```c#
                        ImpersonationUtility.Run(sqlServiceProcessId,
                        () =>
                        {
                            using (SqlConnection sqlConnection = new SqlConnection(connection.ToString()))
                            {
                                sqlConnection.Open();

                                // get the login from the SQL server to avoid case sensitivity issue
                                string currentLoginName = null;

                                using (SqlCommand command = new SqlCommand(CheckIfLoginExists, sqlConnection))
                                {
                                    command.Parameters.AddWithValue("@accountName", accountName);
                                    using (SqlDataReader reader = command.ExecuteReader())
                                    {
                                        if (reader.HasRows && reader.Read())
                                        {
                                            // there will be only one login at server-level
                                            currentLoginName = (string)reader[0];
                                        }
                                    }
                                }

                                if (!string.IsNullOrEmpty(currentLoginName))
                                {
                                    // login exists and need to be removed
                                    using (SqlCommand dropcommand = new SqlCommand(DropSqlLogin, sqlConnection))
                                    {
                                        dropcommand.Parameters.AddWithValue("@accountName", currentLoginName);
                                        dropcommand.ExecuteNonQuery();
                                    }
                                    Logger.LogInfo($"Successfully removed {currentLoginName} from {sqlServiceName}");
                                }
                                else
                                {
                                    Logger.LogInfo($"Skipping removal of {accountName} from {sqlServiceName} as login doesn't exist.");
                                }
                            }
                        });
```

### Further technical details
Microsoft.Data.SqlClient version: (5.0.1)
.NET target: (.NET7)
SQL Server version: (SQL Server 2017,SQL Server 2019)
Operating system: (WS2016 WS2019)

**Additional context**

**Comment by WD1993** [comment]
another similar exception raised from the same func call:
**Failed to remove service account 'NT Service\SQLIaaSExtensionQuery'. Proceeding to next step. System.IO.FileLoadException: 
File name: 'System.Transactions.Local, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at Microsoft.SqlServer.Management.SqlIaaSHandler.Setup.SqlIaaSExtensionDeployerHelper.DropSqlLoginImpersonateSqlStartupAccount(String instanceName, String accountName, String appName, Int32 sqlConnectionErrorsRetryCount, TimeSpan sqlConnectionErrorsRetryInterval)
   at Microsoft.SqlServer.Management.SqlIaaSHandler.Setup.SqlIaaSExtensionDeployerHelper.DropExtensionQueryServiceAccount(String targetedSqlInstance)**

**Comment by mdaigle** [comment]
Hi @WD1993, are you still facing this issue with the latest driver version? I will close this issue if I don't hear back from you. Thanks!
