### ISSUE TITLE
Connectionless ExecuteReader call never returns in Azure Function

### ISSUE THREAD

**Issue by AaronViviano** [dotnet/SqlClient#2046]
### Describe the bug
When the following code is executed in an Azure Function the call to `ExecuteReader` call never returns, even though the connection on the command is not set. When the code is run in a command line application an exception is thrown because the connection for the command isn't set.

### To reproduce
Please see the "Function Code" for reproduction.

#### Function Code
```
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using Microsoft.Data.SqlClient;

namespace CourseDBFunction
{
    public static class GetCoursesUnit
    {
        [FunctionName("GetCourses")]
        public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Function, "get", Route = null)] HttpRequest req,
            ILogger log)
        {
            List<Course> courses = new List<Course>();
            string connectionString = "{connection_string}"
            string statement = "SELECT CourseID, CourseName, Rating from Course;";
            SqlConnection connection = new SqlConnection(connectionString);
            connection.Open();
            SqlCommand command = new SqlCommand(statement);
            SqlDataReader reader = command.ExecuteReader(); // This should thrown an exception
            /*while (reader.Read()) {
                Course course = new Course() {
                    CourseID = reader.GetInt32(0),
                    CourseName = reader.GetString(1),
                    Rating = reader.GetDecimal(2),
                };

                courses.Add(course);
            }*/
            reader.Close();
            connection.Close();
            return new OkObjectResult(courses);
        }
    }
}

#### Command Line Application Code
```C#
using CourseDBFunction;
using Microsoft.Data.SqlClient;

namespace ConsoleApp2 {
    internal class Program {
        static void Main(string[] args) {
            List<Course> courses = new List<Course>();
            string connectionString = "connection_string";
            string statement = "SELECT CourseID, CourseName, Rating from Course;";
            SqlConnection connection = new SqlConnection(connectionString);
            connection.Open();
            SqlCommand command = new SqlCommand(statement);
            SqlDataReader reader = command.ExecuteReader();
            /*while (reader.Read()) {
                Course course = new Course() {
                    CourseID = reader.GetInt32(0),
                    CourseName = reader.GetString(1),
                    Rating = reader.GetDecimal(2),
                };

                courses.Add(course);
            }*/
            reader.Close();
            connection.Close();
            Console.Write(courses);
            return;
        }
    }
}
```
#### Command Line Generated Exception
```
System.InvalidOperationException
  HResult=0x80131509
  Message=ExecuteReader: Connection property has not been initialized.
  Source=Microsoft.Data.SqlClient
  StackTrace:
   at Microsoft.Data.SqlClient.SqlCommand.ValidateCommand(Boolean isAsync, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader()
   at ConsoleApp2.Program.Main(String[] args) in C:\repos\ConsoleApp2\Program.cs:line 13
```
#### Additional class for context
```c#
namespace CourseDBFunction {
    class Course {
        public int CourseID { get; set; }
        public string CourseName { get; set; }
        public decimal Rating { get; set; }

        public override string ToString() {
            return $"{CourseID},{CourseName},{Rating}";
        }
    }
}
```

### Expected behavior
The `ExecuteReader` method should generate an exception in a similar manner to the command line application call. 

### Further technical details
Function app and command lines apps are built with .Net 6.0.
Microsoft.Data.SqlClient 5.1.1
#### Visual Studio Information
```
Microsoft Visual Studio Community 2022
Version 17.5.1
VisualStudio.17.Release/17.5.1+33424.131
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2022   00482-90000-00000-AA114
Microsoft Visual C++ 2022

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools   17.5.317.37931
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.5.317.37931
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.5.317.37931
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   4.5.0-6.23123.11+271ccd71554f7d28d2f90551aafd0bdeb5d327aa
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   17.0.22336.2
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Extensibility Message Bus   1.4.3 (main@2a4517a)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Linux Core Dump Debugging   1.0.9.33414
Enables debugging of Linux core dumps.

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.5.9 (11975e6)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.5.50105.3 Commit Hash:882de61a7c99ae988d4c62029301292a3e0b1d56
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   6.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

NVIDIA CUDA 11.7 Wizards   11.7
Wizards to create new NVIDIA CUDA projects and source files.

NVIDIA Nsight Visual Studio Edition   2022.2.1.22136
NVIDIA Nsight Visual Studio Edition provides tools for GPGPU and graphics development.  Copyright © NVIDIA 2010 - 2022.
•Direct3D® and DirectX® are registered trademarks of Microsoft Corporation in the United States and/or other countries.
•Microsoft Detours is used under the Professional license (http://research.microsoft.com/en-us/projects/detours/).
•Gardens Point Parser Generator Copyright 2005 Queensland University of Technology (QUT). All rights reserved.
•Icons from Axialis Software used under the licensing terms found here: www.axialis.com
•NLog Copyright © 2004-2006 Jaroslaw Kowalski (jaak@jkowalski.net)
•zlib and libpng used under the zlib/libpnc license (http://opensource.org/licenses/Zlib) 
•Breakpad Copyright ©2006, Google Inc. All rights reserved.
•The OpenGL Extension Wrangler Library
Copyright ©2008-2016, Nigel Stewart (nigels@users.sourceforge.net), Copyright ©2002-2008, Milan Ikits (milan.ikits@ieee.org), Copyright ©2002-2008, Marcelo E. Magallon (mmagallo@debian.org), Copyright ©2002, Lev Povalahev. 
All rights reserved. 
•LIBSSH2 Copyright ©2004-2007 Sara Golemon (sarag@libssh2.org), Copyright ©2005,2006 Mikhail Gusarov (dottedmag@dottedmag.net),Copyright ©2006-2007 The Written Word, Inc.,Copyright ©2007 Eli Fant (elifantu@mail.ru),Copyright ©2009-2014 Daniel Stenberg., Copyright ©2008, 2009 Simon Josefsson.
All rights reserved. 
•Protobuf Copyright ©2014, Google Inc. All rights reserved.
•xxHASH Library Copyright ©2012-2014, Yann Collet. All rights reserved. 
•FMT Copyright ©2012 - 2016, Victor Zverovich 
•Font Awesome Copyright 2018 Fonticons, Inc. 
•ELF Definitions Copyright (c) 2010 Joseph Koshy, All rights reserved.

Warning: This computer program is protected by copyright law and international treaties. Unauthorized reproduction or distribution of this program, or any portion of it, may result in severe civil and criminal penalties, and will be prosecuted to the maximum extent possible under the law.

NVIDIA Nsight Visual Studio Edition - CUDA support   2022.2.1.22136
NVIDIA Nsight Visual Studio Edition - CUDA support provides tools for CUDA development and debugging.

Python - Django support   17.0.22336.2
Provides templates and integration for the Django web framework.

Python - Profiling support   17.0.22336.2
Profiling support for Python projects.

Python with Pylance   17.0.22336.2
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Razor (ASP.NET Core)   17.5.2.2307502+8b3141d86b738daf2ca3ed9c15b12513071fc676
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.2.40118.0
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.20105.2003
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.5.0-6.23123.11+271ccd71554f7d28d2f90551aafd0bdeb5d327aa
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Linux Development   1.0.9.33414
Visual C++ for Linux Development

Visual F# Tools   17.5.0-beta.23053.5+794b7c259d9646a7eb685dad865aa27da7940a21
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Xamarin   17.5.0.173 (d17-5@33e727c)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.5.3.46 (remotes/origin/d17-5@e4dd80b2bb)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   13.2.0.0 (d17-5/797e2e1)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 6dd9def
    Java.Interop: xamarin/java.interop/main@149d70fe
    SQLite: xamarin/sqlite/3.40.0@fdc1e34
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@9f02d77
```
**Additional context**
* Database is Azure SQL Server. 
* Location: North Central US

**Comment by JRahnama** [comment]
@AaronViviano we will look into this and will get back to you.

**Comment by AaronViviano** [comment]
Hello @JRahnama,
"@AaronViviano we will look into this and will get back to you."
Thank you.

"@AaronViviano can handle the exception in the code and try that again to see the results?"
My appologies if I am not being clear or I don't understand your question. I believe the issue here is that an exception is not being thrown by the `ExecuteReader` method, when it is being run in an Azure Function, and the connection property isn't set. Under these conditions the the method never returns. When the `ExecuteReader` method is run in a command line application, and the connection property isn't set, an exception is thrown as expected. I'm not sure what is being asked for by "handle the exception" as there is no exception being thrown by `ExecuteReader` method in the Azure Function implementation.

Regards,
Aaron

**Comment by JRahnama** [comment]
@AaronViviano:

> To avoid loss of data or missed messages, it's important to practice good error handling.

you can read more [here](To avoid loss of data or missed messages, it's important to practice good error handling.).

**Comment by cheenamalhotra** [comment]
Closing this issue as outdated/stale. If you are still experiencing this, please let us know by reopening the issue.
