### ISSUE TITLE
GetSchema("DataType") is not compatible with Azure SQL Edge

### ISSUE THREAD

**Issue by MaceWindu** [dotnet/SqlClient#2086]
### Describe the bug

GetSchema('DataType") loads UDT types using CLR features of SQL Server, not supported on `Azure SQL Edge` leading to exception from server.

You can see that `addUDTsToDataTypesTable` method checks only SQL Server version [here](https://github.com/dotnet/SqlClient/blob/3cb9730a848c919c765036d48cb79440030f3df5/src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlMetadataFactory.cs#L28C22-L47).

```
Unhandled exception: Common Language Runtime(CLR) is not enabled on this instance.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at Microsoft.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at Microsoft.Data.SqlClient.SqlDataReader.Read()
   at Microsoft.Data.SqlClient.SqlMetaDataFactory.addUDTsToDataTypesTable(DataTable dataTypesTable, SqlConnection connection, String ServerVersion)
   at Microsoft.Data.SqlClient.SqlMetaDataFactory.GetDataTypesTable(SqlConnection connection)
   at Microsoft.Data.SqlClient.SqlMetaDataFactory.PrepareCollection(String collectionName, String[] restrictions, DbConnection connection)
   at Microsoft.Data.ProviderBase.DbMetaDataFactory.GetSchema(DbConnection connection, String collectionName, String[] restrictions)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.GetSchema(DbConnectionFactory factory, DbConnectionPoolGroup poolGroup, DbConnection outerConnection, String collectionName, String[] restrictions)
   at Microsoft.Data.SqlClient.SqlConnection.GetSchema(String collectionName, String[] restrictionValues)
   at Microsoft.Data.SqlClient.SqlConnection.GetSchema(String collectionName)
```

### To reproduce

```c#
connection.GetSchema("DataType")
```

### Expected behavior

API doesn't try to access unsupported by server functionality.

### Further technical details

Microsoft.Data.SqlClient version: 5.1.1

**Additional context**

[Azure Edge unsupported features](https://learn.microsoft.com/en-us/azure/azure-sql-edge/features#unsupported-features)

Original issue : https://github.com/linq2db/linq2db/issues/4195

**Comment by Kaur-Parminder** [comment]
@MaceWindu I will look into it and report back.

**Comment by ErikEJ** [comment]
@MaceWindu Does it work with Azure SQL database or is it same issue?

**Comment by MaceWindu** [comment]
@ErikEJ , Azure SQL has own limitations, but this part works fine
