### ISSUE TITLE
Different SQL server certificate requirements for native and managed SNI on Windows

### ISSUE THREAD

**Issue by swh-cb** [dotnet/SqlClient#2115]
### Describe the bug

The Native SNI and the Managed SNI have different SQL server certificate requirements when connecting to the local SQL Server Express named instance using the server name `localhost\SQLEXPRESS` on Windows with `Microsoft.Data.SqlClient 5.0.0` and later:

- Native SNI: Requires `$env:ComputerName` as subject alternative name (SAN) in the SQL server certificate and throws a connection error (`Target principal name is incorrect`) if the certificate does not include the computer name as SAN
- Managed SNI: Requires `localhost` as SAN in the SQL server certificate (as expected)

With `Microsoft.Data.SqlClient 4.1.1`, both native SNI and managed SNI can connect to the SQL server using a certificate that includes `localhost` as SAN (and does not include the computer name as SAN).

Native SNI throws the following exception during the login process:

```
Exception message: A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The target principal name is incorrect.)
Stack trace:
at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParserStateObject.ThrowExceptionAndWarning(Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParserStateObject.SNIWritePacket(PacketHandle packet, UInt32& sniError, Boolean canAccumulate, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParserStateObject.WriteSni(Boolean canAccumulate)
   at Microsoft.Data.SqlClient.TdsParserStateObject.WritePacket(Byte flushMode, Boolean canAccumulate)
   at Microsoft.Data.SqlClient.TdsParser.TdsLogin(SqlLogin rec, FeatureExtension requestedFeatures, SessionData recoverySessionData, FederatedAuthenticationFeatureExtensionData fedAuthFeatureExtensionData, SqlConnectionEncryptOption encrypt)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.Login(ServerInfo server, TimeoutTimer timeout, String newPassword, SecureString newSecurePassword, SqlConnectionEncryptOption encrypt)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
```

The system event log contains the following Schannel error:

```xml
// The certificate received from the remote server does not contain the expected name.
// It is therefore not possible to determine whether we are connecting to the correct server.
// The server name we were expecting is $env:ComputerName.
// The SSL connection request has failed.
// The attached data contains the server certificate.
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Schannel" Guid="{1f678132-5938-4686-9fdc-c8ff68f15c85}" />
    <EventID>36884</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2023-08-08T11:15:48.3880148Z" />
    <EventRecordID>1997658</EventRecordID>
    <Correlation ActivityID="{96368eb4-c9c9-0004-d88e-3696c9c9d901}" />
    <Execution ProcessID="1140" ThreadID="38604" />
    <Channel>System</Channel>
    <Computer>[computer]</Computer>
    <Security UserID="[sid]" />
  </System>
  <UserData>
    <EventXML xmlns="LSA_NS">
      <Name>$env:ComputerName</Name>
    </EventXML>
  </UserData>
</Event>
```

### To reproduce

Create a first self signed certificate that includes `localhost` and the FQDN as SAN:

```ps1
New-SelfSignedCertificate -Type SSLServerAuthentication -Subject "CN=$env:ComputerName" -DnsName ("{0}" -f [System.Net.Dns]::GetHostByName($env:computerName).HostName),'localhost' -KeyAlgorithm "RSA" -KeyLength 2048 -HashAlgorithm "SHA256" -TextExtension "2.5.29.37={text}1.3.6.1.5.5.7.3.1" -NotAfter (Get-Date).AddYears(10) -KeySpec KeyExchange -Provider "Microsoft RSA SChannel Cryptographic Provider" -CertStoreLocation "cert:\LocalMachine\My"
```

Create a second self signed certificate that includes `localhost`, the FQDN and the computer name as SAN:

```ps1
New-SelfSignedCertificate -Type SSLServerAuthentication -Subject "CN=$env:ComputerName" -DnsName ("{0}" -f [System.Net.Dns]::GetHostByName($env:computerName).HostName),("{0}" -f $env:computerName),'localhost' -KeyAlgorithm "RSA" -KeyLength 2048 -HashAlgorithm "SHA256" -TextExtension "2.5.29.37={text}1.3.6.1.5.5.7.3.1" -NotAfter (Get-Date).AddYears(10) -KeySpec KeyExchange -Provider "Microsoft RSA SChannel Cryptographic Provider" -CertStoreLocation "cert:\LocalMachine\My"
```

(Based on https://learn.microsoft.com/en-US/sql/database-engine/configure-windows/configure-sql-server-encryption?view=sql-server-ver16#powershell-script-to-create-self-signed-certificate-for-sql-server)

Use the following C# code:

```c#
// Enable the switch to test managed SNI on Windows
AppContext.SetSwitch("Switch.Microsoft.Data.SqlClient.UseManagedNetworkingOnWindows", false);

using (var connnection = new SqlConnection(@"Server=localhost\SQLEXPRESS;Database=master;Integrated Security=true;Connection Timeout=30"))
{
	await connnection.OpenAsync();
}
```

### Expected behavior

Like the Managed SNI, the Native SNI can connect to the SQL server using the first certificate that includes only `localhost` as SAN because the server name from the connection string should be used for certificate validation. Currently, the Native SNI can only connect to the SQL server using the second certificate that includes the computer name as SAN as well.

Workaround: Explicitly set `HostNameInCertificate=localhost` in the connection string.

### Further technical details
Microsoft.Data.SqlClient version: 5.0.0 - 5.1.1
.NET target: .NET 6.0 / .NET 7.0
SQL Server version: SQL Server 2019 15.0.2080.9
Operating system: Windows 10 21H2

**Comment by JRahnama** [comment]
SNI [v5.1.1](https://www.nuget.org/packages/Microsoft.Data.SqlClient.SNI/5.1.1) is released to address this issue. 

Closing as resolved.

**Comment by swh-cb** [comment]
@JRahnama Thanks for the quick fix. I can confirm that the SQL connection can now be established successfully again using the latest `Microsoft.Data.SqlClient.SNI.runtime` package.
