### ISSUE TITLE
SqlException: Login failed for user '<token-identified principal>'.

### ISSUE THREAD

**Issue by VigneashSelvaraj** [dotnet/SqlClient#2125]
I'm using below connection string to connect AZURE SQL server, however We see below error. Please advice 

Connection string:  Data Source=servername.database.windows.net;Encrypt=True;Initial Catalog=dbname;Authentication=Active Directory Service Principal;User Id=userid;Password=password;

Activity done: 
1. Added the respective service principal is AZURE SQL server
2. ran below queries 
- DB: master -> CREATE USER [MyServicePrincipleName] FROM EXTERNAL PROVIDER;
- DB: target DB -> CREATE USER [MyServicePrincipleName] FROM EXTERNAL PROVIDER;
- GRANT CONNECT TO [MyServicePrincipleName];
- EXEC sp_addrolemember N'db_datareader', N'MyServicePrincipleName';
- EXEC sp_addrolemember N'db_datawriter', N'MyServicePrincipleName';
- ALTER ROLE db_datareader ADD MEMBER [MyServicePrincipleName];
- ALTER ROLE db_datawriter ADD MEMBER [MyServicePrincipleName];
- GRANT EXECUTE TO [MyServicePrincipleName];
- GRANT UNMASK TO [MyServicePrincipleName];

Error message:
System.Data.Entity.Core.EntityException
  HResult=0x80131501
  Message=The underlying provider failed on Open.
  Source=EntityFramework
  StackTrace:
   at System.Data.Entity.Core.EntityClient.EntityConnection.Open()
   at System.Data.Entity.Core.Objects.ObjectContext.EnsureConnection(Boolean shouldMonitorTransactions)
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass41_0.<GetResults>b__0()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__31_0()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()  This exception was originally thrown at this call stack:
    [External Code]
Inner Exception 1:
SqlException: Login failed for user '<token-identified principal>'.

**Comment by ErikEJ** [comment]
Wrong appRegistration ID or Secret in your connection string?

**Comment by VigneashSelvaraj** [comment]
No, I can connect with same credentials using SSMS

**Comment by ErikEJ** [comment]
I dont thinks SSMS supports: "Active Directory Service Principal" - what auth type do you choose with SSMS?

**Comment by VigneashSelvaraj** [comment]
I'm using SSMS 19.0 and could see Active Directory Service Principal option in it

**Comment by VigneashSelvaraj** [comment]
![ssms](https://github.com/dotnet/SqlClient/assets/69391996/d2eca113-2739-40e1-a9d7-2cae569da383)

**Comment by VigneashSelvaraj** [comment]
Please disregard this Erik, My bad, I was targeting a different DB. This is working now
