### ISSUE TITLE
Tests do not run inside visual studio which blocks coverage

### ISSUE THREAD

**Issue by Wraith2** [dotnet/SqlClient#217]
When trying to run tests inside visual studio in debug mode tests cannot be run due to a missing dll: 

```
[25/09/2019 11:13:45.071 PM Informational] ---------- Discovery started ----------
[25/09/2019 11:13:45.285 PM Error] Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Unable to find E:\Programming\csharp7\SqlClient\bin\Windows_NT\Debug.AnyCPU\CoreFx.Private.TestUtilities\netcoreapp2.1\testhost.dll. Please publish your test project and retry.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.GetTestHostPath(String runtimeConfigDevPath, String depsFilePath, String sourceDirectory)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.GetTestHostProcessStartInfo(IEnumerable`1 sources, IDictionary`2 environmentVariables, TestRunnerConnectionInfo connectionInfo)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.DiscoverTests(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler)
[25/09/2019 11:13:45.899 PM Informational] [xUnit.net 00:00:00.3081508]   Discovering: Microsoft.Data.SqlClient.Tests
[25/09/2019 11:13:45.970 PM Informational] [xUnit.net 00:00:00.3776758]   Discovering: Microsoft.Data.SqlClient.ManualTesting.Tests
[25/09/2019 11:13:46.350 PM Informational] [xUnit.net 00:00:00.6369007]   Discovered:  Microsoft.Data.SqlClient.ManualTesting.Tests
[25/09/2019 11:13:46.456 PM Informational] [xUnit.net 00:00:00.7167884]   Discovered:  Microsoft.Data.SqlClient.Tests
[25/09/2019 11:13:46.962 PM Warning] No test is available in E:\Programming\csharp7\SqlClient\bin\Windows_NT\Debug.AnyCPU\Microsoft.Data.SqlClient\netfx\Microsoft.Data.SqlClient.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
[25/09/2019 11:13:47.024 PM Informational] ========== Discovery aborted: -1 tests found (0:00:01.9150349) ==========
```

In release mode an different exception occurs

```
[25/09/2019 11:31:00.082 PM Informational] ---------- Run started ----------
[25/09/2019 11:31:01.655 PM Warning] [xUnit.net 00:00:00.3381307] Microsoft.Data.SqlClient.Tests: Catastrophic error during deserialization: System.InvalidOperationException: Could not de-serialize type 'Xunit.NetCore.Extensions.SkippedTestCase' because it lacks a parameterless constructor.
   at Xunit.Serialization.XunitSerializationInfo.DeserializeSerializable(Type type, String serializedValue) in C:\Dev\xunit\xunit\src\common\XunitSerializationInfo.cs:line 213
   at Xunit.Serialization.XunitSerializationInfo.Deserialize(Type type, String serializedValue) in C:\Dev\xunit\xunit\src\common\XunitSerializationInfo.cs:line 110
   at Xunit.Sdk.SerializationHelper.Deserialize[T](String serializedValue) in C:\Dev\xunit\xunit\src\common\SerializationHelper.cs:line 40
   at Xunit.Sdk.XunitTestFrameworkExecutor.Deserialize(String value) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\XunitTestFrameworkExecutor.cs:line 59
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at Xunit.Runner.VisualStudio.VsTestRunner.RunTestsInAssembly(IRunContext runContext, IFrameworkHandle frameworkHandle, LoggerHelper logger, TestPlatformContext testPlatformContext, IMessageSinkWithTypes reporterMessageHandler, AssemblyRunInfo runInfo) in C:\Dev\xunit\xunit\src\xunit.runner.visualstudio\VsTestRunner.cs:line 522
[25/09/2019 11:31:01.656 PM Warning] [xUnit.net 00:00:00.3733263] Microsoft.Data.SqlClient.ManualTesting.Tests: Catastrophic error during deserialization: System.InvalidOperationException: Could not de-serialize type 'Xunit.NetCore.Extensions.SkippedTestCase' because it lacks a parameterless constructor.
   at Xunit.Serialization.XunitSerializationInfo.DeserializeSerializable(Type type, String serializedValue) in C:\Dev\xunit\xunit\src\common\XunitSerializationInfo.cs:line 213
   at Xunit.Serialization.XunitSerializationInfo.Deserialize(Type type, String serializedValue) in C:\Dev\xunit\xunit\src\common\XunitSerializationInfo.cs:line 110
   at Xunit.Sdk.SerializationHelper.Deserialize[T](String serializedValue) in C:\Dev\xunit\xunit\src\common\SerializationHelper.cs:line 40
   at Xunit.Sdk.XunitTestFrameworkExecutor.Deserialize(String value) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\XunitTestFrameworkExecutor.cs:line 59
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at Xunit.Runner.VisualStudio.VsTestRunner.RunTestsInAssembly(IRunContext runContext, IFrameworkHandle frameworkHandle, LoggerHelper logger, TestPlatformContext testPlatformContext, IMessageSinkWithTypes reporterMessageHandler, AssemblyRunInfo runInfo) in C:\Dev\xunit\xunit\src\xunit.runner.visualstudio\VsTestRunner.cs:line 522
[25/09/2019 11:31:01.660 PM Informational] [xUnit.net 00:00:00.3467437]   Starting:    Microsoft.Data.SqlClient.Tests
[25/09/2019 11:31:01.660 PM Informational] [xUnit.net 00:00:00.3819797]   Starting:    Microsoft.Data.SqlClient.ManualTesting.Tests
[25/09/2019 11:31:01.683 PM Informational] [xUnit.net 00:00:00.4053009]   Finished:    Microsoft.Data.SqlClient.ManualTesting.Tests
[25/09/2019 11:31:01.688 PM Informational] [xUnit.net 00:00:00.3746166]   Finished:    Microsoft.Data.SqlClient.Tests
[25/09/2019 11:31:01.822 PM Informational] ========== Run finished: 0 tests run (0:00:01.7358321) ==========
```

The release serialization error has been mentioned https://github.com/dotnet/buildtools/issues/2017 but the buildtools package is [no longer active](https://github.com/dotnet/buildtools/pull/2258) and a fix won't be provided for the problem.

### To reproduce
To reproduce use the download and build instructions from buildguide then open the solution in visual studio 16.3+ and attempt to run all tests in any debug or release configuration.

### Additional Technical Info

The tests really need to be run in debug mode or the assertions littered through the codebase are of no worth. I know there are historic reasons for them to be run in release mode but doing so has hidden at least one bug (https://github.com/dotnet/corefx/pull/38266).

The inability to run tests blocks generation of code coverage reports.

**Comment by cheenamalhotra** [comment]
Ack: It is in our backlog, to be done sometime soon.

**Comment by ErikEJ** [comment]
Is this not fixed now?

**Comment by Wraith2** [comment]
functional tests run. manual ones won't because there's no way to specify the required environment variables as far as I can tell.

**Comment by v-kaywon** [comment]
@Wraith2, with PR #280 merged, the environment variables are not longer needed. You can set the variables in [config.json](https://github.com/dotnet/SqlClient/blob/master/src/Microsoft.Data.SqlClient/tests/ManualTests/config.json). For more information for how config.json works, take a look at the [BUILDGUIDE](https://github.com/dotnet/SqlClient/blob/master/BUILDGUIDE.md#run-manual-tests).

However I tried to run all the test in test explorer in both Release and Debug modes, I'm still getting the exception mentioned in this issue. It's in our backlog, we'll look into it.

**Comment by Wraith2** [comment]
In that case you should probably add a git exclusion for config.json so people don't constantly try to replace it in PRs.

**Comment by David-Engel** [comment]
I've been looking at this for a few hours now and it seems like VS 2019 always throws the catastrophic exception when a parameter to a ConditionFact returns false. VS 2017 runs most tests for me without throwing the catastrophic exception and skips tests when appropriate but it did throw this eventually, which I have not yet dug into:
```
The active test run was aborted. Reason: Assertion Failed
Invalid attentionSent state at end of ProcessAttention
   at Microsoft.Data.SqlClient.TdsParser.ProcessAttention(TdsParserStateObject stateObj) in C:\Source\GitHub\David-Engel\SqlClient\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\TdsParser.cs:line 7324
   at Microsoft.Data.SqlClient.TdsParser.ProcessPendingAck(TdsParserStateObject stateObj) in C:\Source\GitHub\David-Engel\SqlClient\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\TdsParser.cs:line 311
   at Microsoft.Data.SqlClient.TdsParserStateObject.ResetCancelAndProcessAttention() in C:\Source\GitHub\David-Engel\SqlClient\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\TdsParserStateObject.cs:line 745
   at Microsoft.Data.SqlClient.TdsParserStateObject.CloseSession() in C:\Source\GitHub\David-Engel\SqlClient\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\TdsParserStateObject.cs:line 721
   at Microsoft.Data.SqlClient.SqlCommand.PutStateObject() in C:\Source\GitHub\David-Engel\SqlClient\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\SqlCommand.cs:line 4702
   at Microsoft.Data.SqlClient.SqlCommand.ReliablePutStateObject() in C:\Source\GitHub\David-Engel\SqlClient\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\SqlCommand.cs:line 4692
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteReaderAsync(IAsyncResult asyncResult) in C:\Source\GitHub\David-Engel\SqlClient\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\SqlCommand.cs:line 1795
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   at System.Threading.Tasks.TaskFactory`1.<>c__DisplayClass38_0`1.<FromAsyncImpl>b__0(IAsyncResult iar)
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<BeginExecuteReaderInternal>b__166_1(Task`1 task, Object state) in C:\Source\GitHub\David-Engel\SqlClient\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\SqlCommand.cs:line 1917
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by David-Engel** [comment]
The exlude is already in there:
https://github.com/dotnet/SqlClient/blob/master/.gitignore#L362

**Comment by cheenamalhotra** [comment]
Hi @Wraith2 

Can you confirm if you're able to run tests in Visual Studio now (including Manual Tests), with provided configuration in config.json file?

**Comment by Wraith2** [comment]
Yes, I have to change to netcore3.1-release but it does work now, thanks.
