### ISSUE TITLE
Unable to connect ARM VS2022 to MSSQL Server due to TdsParser

### ISSUE THREAD

**Issue by erikmartinessanches** [dotnet/SqlClient#2175]
### Describe the bug
Trying to connect ARM VS2022 Enterprise v 17.7.4 on Win 11 ARM version 10.0.25201 build 25201 to MSSQL Server 2022 Dev edition on Win 10 x64 version 10.0.19045. 

Exception message: 
```
The type initializer for 'Microsoft.Data.SqlClient.TdsParser' threw an exception. (Microsoft.Data.SqlClient)

------------------------------
ADDITIONAL INFORMATION:

The type initializer for 'Microsoft.Data.SqlClient.SNILoadHandle' threw an exception. (Microsoft.Data.SqlClient)

------------------------------

Unable to load DLL 'Microsoft.Data.SqlClient.SNI.arm64.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E) (Microsoft.Data.SqlClient)

------------------------------
```

 
Stack trace:
```
===================================

The type initializer for 'Microsoft.Data.SqlClient.TdsParser' threw an exception. (Microsoft.Data.SqlClient)

------------------------------
Program Location:

   at Microsoft.Data.SqlClient.TdsParser..ctor(Boolean MARS, Boolean fAsynchronous)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, ServerCertificateValidationCallback serverCallback, ClientCertificateRetrievalCallback clientCallback, DbConnectionPool pool, String accessToken, SqlClientOriginalNetworkAddressInfo originalNetworkAddressInfo, Boolean applyTransientFaultHandling)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
   at Microsoft.VisualStudio.Data.Tools.SqlEditor.DataModel.SqlConnectionStrategy.ValidateConnection(UIConnectionInfo ci, IServerConnectionProvider server)
   at Microsoft.SqlServer.ConnectionDlg.UI.ConnectionDialogViewModel.OpenConnectionWithVerifier(IServerConnectionProvider serverConnectionProvider)

===================================

The type initializer for 'Microsoft.Data.SqlClient.SNILoadHandle' threw an exception. (Microsoft.Data.SqlClient)

------------------------------
Program Location:

   at Microsoft.Data.SqlClient.TdsParser..cctor()

===================================

Unable to load DLL 'Microsoft.Data.SqlClient.SNI.arm64.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E) (Microsoft.Data.SqlClient)

------------------------------
Program Location:

   at Microsoft.Data.SqlClient.SNINativeManagedWrapperARM64.SNIInitialize(IntPtr pmo)
   at Microsoft.Data.SqlClient.SNILoadHandle..ctor()
   at Microsoft.Data.SqlClient.SNILoadHandle..cctor()


```

### To reproduce
In VS use SQL Server Object Explorer, then add a SQL Server. Server name: local IP address, Authentication: SQL Server with a name and password I created (and used successfully via MSSMS and Azure Data Studio). 

### Expected behavior
We should connect to MS SQLServer 2022 on the network, just as we can with MSSMS and Azure Data Studio.

### Further technical details
Microsoft.Data.SqlClient version: 
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\Microsoft.Data.SqlClient.dll File version 3.13.23069.2 Product Version 3.1.3

(Interestingly, the Microsoft.Data.SqlClient.dll associated with Azure Data Studio, located at C:\Program Files\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\4.9.1.4\refs, is product version 5.0.1 and file version 5.0.0.0. Since Azure Data Studio is able to connect.)

.NET target: not sure, this happens when no project is loaded
SQL Server version: 2022 Dev ed.
Operating system: Win 11 ARM version 10.0.25201 build 25201 inside UTM 4.3.5 on macOS 13.5.2 (22G91) Apple Silicon M1.

**Comment by SasaCetkovic** [comment]
This happens to me as well, with a similar configuration to yours (Win 11 ARM on VMWare Fusion, Apple M2 Pro)

**Comment by DavoudEshtehari** [comment]
This issue seems related to Visual Studio not SqlClient, and you can raise it on the [Developer community](https://developercommunity.visualstudio.com/home) for VS.

**Comment by JRahnama** [comment]
Closing the issue as external.
