### ISSUE TITLE
[Ubuntu 23.10] Microsoft.Data.SqlClient is not supported on this platform.

### ISSUE THREAD

**Issue by olibos** [dotnet/SqlClient#2183]
### Describe the bug
After upgrade from Ubuntu 23.04 to 23.10, the package Microsoft.Data.SqlClient is not working anymore.

```
Exception message:
      System.PlatformNotSupportedException: Microsoft.Data.SqlClient is not supported on this platform.
Stack trace:
         at Microsoft.Data.SqlClient.SqlConnection..ctor(String connectionString)
         at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerConnection.CreateDbConnection()
         at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.get_DbConnection()
         at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)

```

### To reproduce
Simple .net 7 console application, only with Microsoft.Data.SqlClient nuget package.

```c#
using Microsoft.Data.SqlClient;
new SqlConnection("");
```

### Expected behavior
Not receiving the `System.PlatformNotSupportedException` exception.

### Further technical details
Microsoft.Data.SqlClient version: 5.1.1 (tested 5.2.0-preview3.23201.1 with the same outcome)
```
dotnet --info
.NET SDK:
 Version:   7.0.112
 Commit:    c972157895

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  23.10
 OS Platform: Linux
 RID:         ubuntu.23.04-x64
 Base Path:   /usr/lib/dotnet/sdk/7.0.112/

Host:
  Version:      7.0.12
  Architecture: x64
  Commit:       4a824ef37c

.NET SDKs installed:
  6.0.123 [/usr/lib/dotnet/sdk]
  7.0.112 [/usr/lib/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.23 [/usr/lib/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.12 [/usr/lib/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.23 [/usr/lib/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.12 [/usr/lib/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by JRahnama** [comment]
@olibos I just installed an Ubuntu Server 23.10
![image](https://github.com/dotnet/SqlClient/assets/32077152/e9253452-52b7-4ee5-924d-882574d175bb)

and added a simple application to connect to a server and open a connection and had no issues.

![image](https://github.com/dotnet/SqlClient/assets/32077152/78cfd88d-abeb-4fa8-a213-c4db8625822c)
 and here is the csproj file:
![image](https://github.com/dotnet/SqlClient/assets/32077152/d3adda2c-d55c-4d9e-b882-b7f60417d1e4)


Did I miss anything on the steps to repro?

**Comment by JRahnama** [comment]
the only difference I see is the SDK version.

**Comment by olibos** [comment]
You're a lifesaver @JRahnama!

It was the SDK version! All my dot net packages were still on lunar instead of mantic.

If anyone had the same problem, I followed these steps: [My Linux distribution provides .NET packages, and I want to use them](https://learn.microsoft.com/en-us/dotnet/core/install/linux-package-mixup?pivots=os-linux-ubuntu#my-linux-distribution-provides-net-packages-and-i-want-to-use-them)

1. Remove the existing .NET packages from your distribution. You want to start over and ensure that you don't install them from the wrong repository.
```sh
sudo apt remove 'dotnet*' 'aspnet*' 'netstandard*'
```
2. Create /etc/apt/preferences, if it doesn't already exist.
```sh
touch /etc/apt/preferences

Open /etc/apt/preferences in an editor and add the following settings, which prevents packages that start with dotnet, aspnetcore, or netstandard from being sourced from the Microsoft repository:
```text
Package: dotnet* aspnet* netstandard*
Pin: origin "packages.microsoft.com"
Pin-Priority: -10
```
3. Reinstall .NET from the distribution's package feed. For more information, see [Install .NET on Linux](https://learn.microsoft.com/en-us/dotnet/core/install/linux).
