### ISSUE TITLE
SqlConnection object is getting deprecated very shorty when Msal access token is used instead of Adal Access token.

### ISSUE THREAD

**Issue by Manoj-Kothapalli-Microsoft** [dotnet/SqlClient#2216]
We are currently eliminating the usage of ADAL packages in our cod which resulted in chnaging the access token generation code from ADAL to MSAL to connect to our SQL stores. We have made below changes and used ManagedIdentitiyCredential object to generate the token and assigned it to SqlConection object. Post deployment, we are experience frequent SqlConnection object disposed exception while using Msal token. When code is chnaged back to use Adal token it is working as expected.

Note: The issue is very intermittent. We can see some success OpenAsync execution. after 3-4 calls immediately next call goes to error state. We are getting connection.OpenAsync when we use Msal Token only and not for Adal token. We have also updated resource uri to https://database.windows.net//.default and for 2 or 3 runs it is able to access sb and execute queries and fails with disposed object exception. 

Code change:
![image](https://github.com/dotnet/SqlClient/assets/150523291/0a1ab2fb-7f44-49cb-8892-29f54402ab5d)

Error: 
Error:

Exception: System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught)
---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
at System.Net.Sockets.Socket.ThrowObjectDisposedException()
at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue)
at System.Data.SqlClient.SNI.SNITCPHandle..ctor(String serverName, Int32 port, Int64 timerExpire, Object callbackObject, Boolean parallel)
at System.Data.ProviderBase.DbConnectionPool.CheckPoolBlockingPeriod(Exception e)
at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
at System.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location ---
at Microsoft.Commerce.Billing.Storage.SqlCommandExecutor`1.Execute(CancellationToken cancellationToken, EventTraceActivity traceId) in C:__w\1\s\private\Billing\shared\Common.Storage.Core\V1\SqlCommandExecutor.cs:line 187

**Comment by ErikEJ** [comment]
This repo is not for System.Data.SqlClient. have you tried Microsoft.Data.SqlClient, which supports managed identity via connection string?

**Comment by David-Engel** [comment]
System.Data.SqlClient is legacy. It's effectively only accepting security fixes, at this point.

The error seems unlikely to be due to the access token acquisition. Was there another change in your environment? (Upgraded .NET versions?) Regardless, the path forward is going to be to migrate to Microsoft.Data.SqlClient. You'll get built-in support for Managed Identity, among other improvements.

https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/

**Comment by kf-gonzalez** [comment]
Issue has been inactive for over a week, it will be closed next week if not feedback is received

**Comment by ErikEJ** [comment]
@kf-gonzalez  Could this be closed now?
