### ISSUE TITLE
Issue Loading Types From Microsoft.Data.SqlClient via Reflection

### ISSUE THREAD

**Issue by JasonBock** [dotnet/SqlClient#2228]
### Describe the bug
Calling `GetTypes()` on the Microsoft.Data.SqlClient assembly causes a `TypeLoadException`.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Unhandled exception. System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load type 'SqlGuidCaster' from assembly 'Microsoft.Data.SqlClient, Version=5.0.0.0, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5' because it contains an object field at offset 0 that is incorrectly aligned or overlapped by a non-object field.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at Program.<Main>$(String[] args)
```

### To reproduce

* Create a console application that targets .NET 8.
* Reference the Microsoft.Data.SqlClient package version 5.1.2
* Add this code to Program.cs:

```c#
var types = typeof(Microsoft.Data.SqlClient.ActiveDirectoryAuthenticationProvider).Assembly.GetTypes();
```

### Expected behavior
No exceptions occur.

**Comment by Wraith2** [comment]
Either use the latest preview version or call GetExportedTypes(). You're attempting to load an internal type which has a base class which changed layout in net8.

**Comment by KimzInc** [comment]
I was creating a minimal API using NET8 and when I added automapper to program.cs file for dependency injection, I experienced the same problem. See attached screenshot
![issues](https://github.com/dotnet/SqlClient/assets/43719694/e2dfb232-56d8-4e7d-a5de-aaba9cc8987f)

**Comment by JRahnama** [comment]
@KimzInc we are in the process of adding Net8 support to the driver. We can test back later when it is official.

**Comment by KimzInc** [comment]
> @KimzInc we are in the process of adding Net8 support to the driver. We can test back later when it is official.

Thank you.

**Comment by allygreen** [comment]
@JRahnama Do you have an ETA of when the dotnet8 support will move from preview to full release? 

Currently experiencing this same issue when calling 
AppDomain.CurrentDomain.GetAssemblies()

Thanks

**Comment by ErikEJ** [comment]
@allygreen The current plan is here: https://github.com/dotnet/SqlClient/milestones

**Comment by allygreen** [comment]
@ErikEJ thanks

**Comment by alhafibarefoot** [comment]
replace Rabota.Data.SqlClient" Version="3.0.24"

**Comment by mdaigle** [comment]
Is anyone still facing this issue? If not, I will close this issue.

**Comment by benrr101** [comment]
Closing as no one has mentioned it still being an issue.
