### ISSUE TITLE
NullReferenceException when calling ExecuteReaderAsync without a connection

### ISSUE THREAD

**Issue by ChristofferGersen** [dotnet/SqlClient#2246]
### Describe the bug
`ExecuteReaderAsync` and `ExecuteScalarAsync` methods (and possibly other Execute* methods) on a `SqlCommand` without a `SqlConnection` throw a `NullReferenceException`, where it should be an `InvalidOperationException`.

```
Exception message: System.NullReferenceException: 'Object reference not set to an instance of an object.'
Stack trace:
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReaderAsync()
```

The InvalidOperationException is thrown from `Microsoft.Data.SqlClient.SqlCommand.RegisterForConnectionCloseNotification<T>(Task<T> outerTask)`. The problem is that this exception is replaced with a NullReferenceException inside `Microsoft.Data.SqlClient.SqlCommand.InternalExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)`. This happends because the `context` variable is null, but the catch block calls `context.Dispose()`.

### To reproduce
```c#
try
{
  using var command = new Microsoft.Data.SqlClient.SqlCommand();
  command.CommandText = "SELECT 1";
  await command.ExecuteReaderAsync(); // Or ExecuteScalarAsync
}
catch (System.Exception ex)
{
  await System.Console.Error.WriteLineAsync(ex.ToString()); // Will show NullReferenceException
}
```

### Expected behavior
When calling Execute* methods on a SqlCommand without a SqlConnection I expect an InvalidOperationException with the message "Invalid operation. The connection is closed.".

### Further technical details
Microsoft.Data.SqlClient version: 5.1.2 (file version 5.12.23290.5)
.NET target: .Net 8.0
SQL Server version: N/A
Operating system: Windows 10

**Additional context**
This worked as expected in 5.0.1 (when targeting .Net 7.0). I believe this change is caused by commit https://github.com/dotnet/SqlClient/commit/1cda34531e660b8a16759c88b6c06ab53a07d7c1.

It is also worth noting that `ExecuteNonQueryAsync` still throws the expected exception, because `InternalExecuteNonQueryAsync` calls 
`RegisterForConnectionCloseNotification` before the try/catch block and not from within the try-block.

**Comment by ErikEJ** [comment]
@Wraith2 FYI

**Comment by Wraith2** [comment]
Ok, sure. 
Why does it make a difference which exception is thrown when you attempt something which is always going to fail one way or another? Calling execute without a connection is a clear fault.

**Comment by ChristofferGersen** [comment]
It is not a huge difference no, but it can help with troubleshooting when you get a better exception. 

I only noticed this change during testing. I have a library that wraps SqlClient, which helps with building the command text with parameters. In the unit tests I just create the SqlCommand without a SqlConnection. Then I try to execute some query, catching the InvalidOperationException and afterwards asserting that the command text and parameters were set correctly. I can just as easily catch a NullReferenceException instead, but I just thought it would be better to keep the previous behavior.

At first I thought that this problem may also occur with connection problems. Because the documentation states you get a InvalidOperationException when "The SqlConnection closed or dropped during a streaming operation". Now I see that in those situations the context variable will probably not be null anymore and you will probably get the correct exception.

**Comment by ChristofferGersen** [comment]
This issue seems to be resolved after updating to v6.1.2. I did not find the commit that fixed this, but on the main branch I saw that a null check was added to the catch block of `InternalExecuteReaderAsync`.
