### ISSUE TITLE
Microsoft.Data.SqlClient 5.1.2 throws InvalidOperationException: The requested operation cannot be completed because the connection has been broken

### ISSUE THREAD

**Issue by SailAwayWine** [dotnet/SqlClient#2285]
### Description
This started happening recently and it occurs about once a week (averaging once per 725,000 queries) under light or nominal load.  There have been no code changes for years. This seems to have started when we updated/recompiled to .NET 8 from .NET 6 and updated to the most recent version of SqlClient, but given the sporadic occurrence, that it just a guess. There is nothing in sql server's extended events to indicate its an issue with the database engine.  This program is part of a large body of programs that run 24/7 and no other issues are occurring elsewhere.

There are 6 threads in the same program executing the following query every 5 seconds continuously:

`Select top 1 ThermalPrintRequestID,  PreCut, PostCut, AttemptCount from loc.ThermalToPrint with (ROWLOCK, READPAST, UPDLOCK) where Printed = 0 and StationCode = 1 order by ThermalPrintRequestID`

We are using the latest version of Dapper to wrap the query and the connections are pooled.  Here is what that looks like:

```vb
    Using trans As New TransactionScope(TransactionScopeOption.Required, New TransactionOptions With {.IsolationLevel = IsolationLevel.RepeatableRead}, TransactionScopeAsyncFlowOption.Enabled)
      Using connection As DbConnection = ThermalToPrint.CreateDBConnection()
        ThermalToPrint = connection.QuerySingleOrDefault(Of POSThermalPrintQueue)($"Select top 1 ThermalPrintRequestID, PreCut, PostCut, AttemptCount from loc.ThermalToPrint with (ROWLOCK, READPAST, UPDLOCK) where Printed = 0 and StationCode = 1 order by ThermalPrintRequestID")
      End Using
```
When the program is started, it creates a DBProviderFactory as follows:
```vb
    DbProviderFactories.RegisterFactory("Microsoft.Data.SqlClient", Microsoft.Data.SqlClient.SqlClientFactory.Instance)
    SQLFactory = DbProviderFactories.GetFactory("Microsoft.Data.SqlClient")
```
The connection is created as follows:
```vb
  Friend Function CreateDBConnection() As DbConnection
    Dim conn As DbConnection = _ConnectionFactory.CreateConnection
    conn.ConnectionString = "Server=.\SQLEXPRESS;Database=SailAwayWineLocalDB; Integrated Security=True;Encrypt=False;MultipleActiveResultSets=True;"
    Return conn
  End Function
```
Here is the exception/call stack:
```
System.InvalidOperationException: The requested operation cannot be completed because the connection has been broken
at Microsoft.Data.SqlClient.SqlDelegatedTransaction.Initialize()
at System.Transactions.TransactionStatePSPEOperation.PSPEInitialize(InternalTransaction tx, IPromotableSinglePhaseNotification promotableSinglePhaseNotification, Guid promoterType)
at System.Transactions.TransactionStateActive.EnlistPromotableSinglePhase(InternalTransaction tx, IPromotableSinglePhaseNotification promotableSinglePhaseNotification, Transaction atomicTransaction, Guid promoterType)
at System.Transactions.Transaction.EnlistPromotableSinglePhase(IPromotableSinglePhaseNotification promotableSinglePhaseNotification, Guid promoterType)
at System.Transactions.Transaction.EnlistPromotableSinglePhase(IPromotableSinglePhaseNotification promotableSinglePhaseNotification)
at Microsoft.Data.SqlClient.SqlInternalConnection.EnlistNonNull(Transaction tx)
at Microsoft.Data.ProviderBase.DbConnectionPool.PrepareConnection(DbConnection owningObject, DbConnectionInternal obj, Transaction transaction)
at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
at Dapper.SqlMapper.QueryRowImpl[T](IDbConnection cnn, Row row, CommandDefinition& command, Type effectiveType)
in /_/Dapper/SqlMapper.cs:line 1276
at AutoPilotDeckhandThermal.ThermalPrint.DoWork()
at AutoPilotDeckhandThermal.TimerBase.Body()
```

### To reproduce
Again, this happens once a week under non-heavy loads.  This query is called approximately 725,000 times per week and only 1 out of those calls fails, on average.  This is a long-running program that just keeps looking for work to do, over and over, for days on end.  It is unknown how to create a reproducible failure.

### Expected behavior
No random, unpredictable exception is expected.  

### Further technical details
Microsoft.Data.SqlClient version: 5.1.2
.NET 8.0
SQL Version 16.0.4080.1
Operating system: Windows Server 2019, fully patched

**Comment by ErikEJ** [comment]
Do you really need to use MARS?

**Comment by SailAwayWine** [comment]
This is a valid, good question.  Since the code has been around for sometime, 

> Do you really need to use MARS?

This is a valid, good question.  Thanks.  Since the code has been around for sometime, the motivation behind including that in the connection string may no longer be applicable, as the scope of the program has been narrowed considerable from its original incarnation.  I will take that out of the connection string and see if the problem reoccurs.

**Comment by kf-gonzalez** [comment]
Please let us know if this would still be an issue otherwise we are looking into closing this issue by next week

**Comment by SailAwayWine** [comment]
> Please let us know if this would still be an issue otherwise we are looking into closing this issue by next week

MARS was removed from the connection string on 12/31/2023 and since that change the exception has not been thrown.   If the exception doesn't reappear in the next 3 weeks then it would appear that removing MARS was the proper workaround for this application.  That said, if the issue is truly related to MARS, then there still may be edge-case flaw in SqlClient.

**Comment by SailAwayWine** [comment]
This issue just reappeared after 2 months.  MARS is not in use.  The latest exception/call stack is identical to the stack previously reported.  Microsoft.Data.SqlClient version: 5.1.5

**Comment by kf-gonzalez2** [comment]
Can you provide a standalone application to reproduce the issue just using Microsoft.Data.SqlClient please?

**Comment by SailAwayWine** [comment]
Just to clarify, are you asking that I create a special case, narrower version of the program, and then let it run for weeks on end to see if that special case program eventually encounters the broken connection exception?

**Comment by David-Engel** [comment]
Unfortunately, there isn't enough info here for us to do anything. This could simply be an intermittent issue with a component related to the transaction or a connectivity issue.
