### ISSUE TITLE
NullReferenceException on using Backup by SMO

### ISSUE THREAD

**Issue by V-Kiehne** [dotnet/SqlClient#2404]
### Describe the bug
Using SqlClient 5.2.0 crashes on backup a database using SMO 170.23.0.
Using 5.1.5 it is working.

```
Exception message:
Stack trace:

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.Data.SqlClient
  StackTrace:
   at Microsoft.Data.SqlClient.SqlCommand.GetCurrentBatchCommand() in Microsoft.Data.SqlClient\SqlCommand.cs:line 5195
   at Microsoft.Data.SqlClient.TdsParser.FireInfoMessageEvent(SqlConnection connection, SqlCommand command, TdsParserStateObject stateObj, SqlError error) in Microsoft.Data.SqlClient\TdsParser.cs:line 1378
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) in Microsoft.Data.SqlClient\TdsParser.cs:line 1926
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite) in Microsoft.Data.SqlClient\SqlCommand.cs:line 3089

  This exception was originally thrown at this call stack:
    Microsoft.Data.SqlClient.SqlCommand.GetCurrentBatchCommand() in SqlCommand.cs
    Microsoft.Data.SqlClient.TdsParser.FireInfoMessageEvent(Microsoft.Data.SqlClient.SqlConnection, Microsoft.Data.SqlClient.SqlCommand, Microsoft.Data.SqlClient.TdsParserStateObject, Microsoft.Data.SqlClient.SqlError) in TdsParser.cs
    Microsoft.Data.SqlClient.TdsParser.TryRun(Microsoft.Data.SqlClient.RunBehavior, Microsoft.Data.SqlClient.SqlCommand, Microsoft.Data.SqlClient.SqlDataReader, Microsoft.Data.SqlClient.BulkCopySimpleResultSet, Microsoft.Data.SqlClient.TdsParserStateObject, out bool) in TdsParser.cs
    Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(string, bool, int, bool) in SqlCommand.cs

```

### Further technical details
Microsoft.Data.SqlClient version: (found on the nuget or Microsoft.Data.SqlClient.dll)
.NET target:  Framework 4.8
SQL Server version: SQL Server 2022
Operating system: Windows 11

**Additional context**
I guess the changes on TdsParser.cs FireInfoMessageEvent()
```
   SqlException exc = SqlException.CreateException(sqlErs, serverVersion, _connHandler);
to
   SqlException exc = SqlException.CreateException(sqlErs, serverVersion, _connHandler, innerException:null, batchCommand: command?.GetCurrentBatchCommand());
```
are causing that issue.

**Comment by arellegue** [comment]
@V-Kiehne We are aware of this issue. It is related to issue #2388. We are working on a fix.

**Comment by JRahnama** [comment]
Can you test with below package to see if the issue is resolved? Remember to change the extension from .zip to .nupkg
[Microsoft.Data.SqlClient.6.0.0-pull.109201.zip](https://github.com/dotnet/SqlClient/files/14826773/Microsoft.Data.SqlClient.6.0.0-pull.109201.zip)

**Comment by V-Kiehne** [comment]
Sorry, as long as the assemblies are not signed, I'm unable to use it inside my project.

**Comment by JRahnama** [comment]
Closing it as addressed by PR #2388
