### ISSUE TITLE
A null was returned after calling the 'GetService' method on a store provider instance of type 'Microsoft.Data.SqlClient.SqlClientFactory'. The store provider might not be functioning correctly.'

### ISSUE THREAD

**Issue by jons-bakerhill** [dotnet/SqlClient#2504]
### Describe the bug
Trying to use Microsoft.Data.SqlClient with OData and getting errors trying to retrieve data.

```
Exception message: A null was returned after calling the 'GetService' method on a store provider instance of type 'Microsoft.Data.SqlClient.SqlClientFactory'. The store provider might not be functioning correctly.'
Stack trace:
   at System.Data.Common.DbProviderServices.GetProviderServices(DbProviderFactory factory)
   at System.Data.Metadata.Edm.StoreItemCollection.Loader.InitializeProviderManifest(Action`3 addError)
   at System.Data.EntityModel.SchemaObjectModel.Schema.HandleAttribute(XmlReader reader)
   at System.Data.EntityModel.SchemaObjectModel.SchemaElement.ParseAttribute(XmlReader reader)
   at System.Data.EntityModel.SchemaObjectModel.SchemaElement.Parse(XmlReader reader)
   at System.Data.EntityModel.SchemaObjectModel.Schema.HandleTopLevelSchemaElement(XmlReader reader)
   at System.Data.EntityModel.SchemaObjectModel.Schema.InternalParse(XmlReader sourceReader, String sourceLocation)
   at System.Data.EntityModel.SchemaObjectModel.Schema.Parse(XmlReader sourceReader, String sourceLocation)
   at System.Data.EntityModel.SchemaObjectModel.SchemaManager.ParseAndValidate(IEnumerable`1 xmlReaders, IEnumerable`1 sourceFilePaths, SchemaDataModelOption dataModel, AttributeValueNotification providerNotification, AttributeValueNotification providerManifestTokenNotification, ProviderManifestNeeded providerManifestNeeded, IList`1& schemaCollection)
   at System.Data.Metadata.Edm.StoreItemCollection.Loader.LoadItems(IEnumerable`1 xmlReaders, IEnumerable`1 sourceFilePaths)
   at System.Data.Metadata.Edm.StoreItemCollection.Init(IEnumerable`1 xmlReaders, IEnumerable`1 filePaths, Boolean throwOnError, DbProviderManifest& providerManifest, DbProviderFactory& providerFactory, String& providerManifestToken, Memoizer`2& cachedCTypeFunction)
   at System.Data.Metadata.Edm.StoreItemCollection..ctor(IEnumerable`1 xmlReaders, IEnumerable`1 filePaths)
   at System.Data.Metadata.Edm.MetadataWorkspace.CreateMetadataWorkspaceWithResolver(IEnumerable`1 paths, Func`1 wildcardAssemblies, Func`2 resolveReference)
   at System.Data.Metadata.Edm.MetadataWorkspace..ctor(IEnumerable`1 paths, IEnumerable`1 assembliesToConsider)
   at XXXX.YYYYY.EntityController.get_GetEntityConnection()
   at XXXX.YYYYY.EntityController.Get(ODataPath odataPath)
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_0.<GetExecutor>b__2(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
```

### To reproduce

Reproduction console app attached
[GetServiceReturnsNull.zip](https://github.com/dotnet/SqlClient/files/15338172/GetServiceReturnsNull.zip)

### Expected behavior
I expected data to load without throwing exceptions.

### Further technical details
Microsoft.Data.SqlClient version: 5.2.0
.NET target: (e.g. Framework 4.8.1)
SQL Server version: N/A
Operating system: Windows 10

**Additional context**

**Comment by arellegue** [comment]
Thank you for letting us know about this issue with M.D.S.SqlClientFactory when using the driver with .Net4.8 Framework.  We will investigate this issue and we'll let you know of our findings.

**Comment by jons-bakerhill** [comment]
> In the meantime, could you please test using Entity Framework Core to see if that fixes your issue.

I missed updating the .NET target in the original template. The vast majority of our code still targets .NET 4.8 and the .NET 8 code we have I don't think uses SqlClient directly. We are in the process of migrating to .NET 8+ but that's at least a year out.

I can try and see if the reproduction project works when targeting .NET 8 but until I run into an issue there myself it'll be pretty far down my priority list.

**Comment by arellegue** [comment]
@jons-bakerhill I have confirmed that Entity Framework 6.x is not compatible with Microsoft.Data.SqlClient.

However, I found a package created by @ErikEJ at his [blog page](https://erikej.github.io/ef6/sqlserver/2021/08/08/ef6-microsoft-data-sqlclient.html).  I followed the instructions there how to use the Microsoft.EntittyFramework.SqlServer package to make EntityFramework 6.4 connect to Microsoft.Data.SqlClient. The Microsoft.EntittyFramework.SqlServer is a preview version and is mentioned near the bottom of the blog page.

Here is the updated repro with the addition of ClientLibrary2 that uses EntityFramework 6.4 and the addition of Microsoft.EntittyFramework.SqlServer package in the ConsoleApp project.

[GetServiceReturnsNull.zip](https://github.com/dotnet/SqlClient/files/15354733/GetServiceReturnsNull.zip)

I do hope that this workaround will work for you.

**Comment by jons-bakerhill** [comment]
I'm using the EF 6.5 preview with newly added support for Microsoft.Data.SqlClient https://github.com/dotnet/ef6/issues/2237 . My understanding is that it is based on ErikEJ's package. Sorry for not including that in the initial report.

**Comment by ErikEJ** [comment]
@jons-bakerhill Thanks for reporting this. No testing has been done with OData, I will have a look.

**Comment by ErikEJ** [comment]
@jons-bakerhill The code in your repro does not use or reference Microsoft.Data.SqlClient, (but rather System.Data.SqlClient), but you are referencing Microsoft.Data.SqlClient in your EDMX file. So getting an error does not seem like a surprise to me.

**Comment by jons-bakerhill** [comment]
> @jons-bakerhill The code in your repro does not use or reference Microsoft.Data.SqlClient, (but rather System.Data.SqlClient), but you are referencing Microsoft.Data.SqlClient in your EDMX file. So getting an error does not seem like a surprise to me.

I definitely missed that. I swapped the using statement to Microsoft.Data.SqlClient and still get the same error though.

**Comment by ErikEJ** [comment]
You are also not referencing the new provider anywhere. Please share an updated repro, and I will have a look.

**Comment by jons-bakerhill** [comment]
I added a NuGet reference to Microsoft.EntityFramework.SqlServer 6.5.0-preview2 but still get the same error. If that's not what you meant by referencing it I'm not sure what to try next.

[GetServiceReturnsNullWithMicrosoft.EntityFramework.SqlServer6.5.0Preview2.zip](https://github.com/dotnet/SqlClient/files/15378812/GetServiceReturnsNullWithMicrosoft.EntityFramework.SqlServer6.5.0Preview2.zip)

**Comment by ErikEJ** [comment]
This is definitely not a SqlClient issue, but an EF 6 issue. I think this is a scenario that is just not supported by the new provider.

**Comment by JRahnama** [comment]
Closing the issue as external.
