### ISSUE TITLE
SqlClient's reference assemblies should declare all dependencies

### ISSUE THREAD

**Issue by benjamin-hodgson** [dotnet/SqlClient#2541]
### Describe the bug
`SqlClient` was compiled with `Azure.Core` version 1.**35**.0.0. When building a project using version 1.**38**.0.0 (or indeed any other version), the appropriate binding redirect is not generated. This results in `FileLoadException`s in the AD authentication codepath - example:

```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Azure.Core, Version=1.35.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Microsoft.Data.SqlClient.ActiveDirectoryAuthenticationProvider.AcquireTokenAsync(SqlAuthenticationParameters parameters)
   at Program.Main() in D:\test\Program.cs:line 7
```

(My minimal repro, below, trips on `Azure.Core` but I've also seen errors mentioning `ValueTuple` and `System.Threading.Tasks.Extensions` in other contexts. I believe they're all due to the same issue.)

The problem here is that the `ResolveAssemblyReferences` target consumes **reference** assemblies from Nuget (when they exist), and `SqlClient`'s reference assemblies do not declare the library's runtime dependency on `Azure.Core`.

The reference assembly in ILSpy (`ref\net462\Microsoft.Data.SqlClient.dll`):
![ref\net462\Microsoft.Data.SqlClient.dll](https://github.com/dotnet/SqlClient/assets/3857587/dd6474cc-9f5a-4bba-b43e-aba70894770f)

The code assembly (`lib\net462\Microsoft.Data.SqlClient.dll`):
![lib\net462\Microsoft.Data.SqlClient.dll](https://github.com/dotnet/SqlClient/assets/3857587/e4d29de0-59ca-430c-85cc-7bc3a8039a83)

This means `ResolveAssemblyReferences` doesn't realise there's a conflict (it thinks `SqlClient` doesn't require `Azure.Core` at all) so fails to generate the correct binding redirects. When `SqlClient`'s **code** assembly is deployed into the bin folder and run, it requires version 1.35, and, absent the required binding redirect, it dies because it can only find 1.38.

### To reproduce

The issue manifests when the _other_ assemblies in your compilation all reference v1.38 of the `Azure.Core` assembly. This combination of versions reproduces the issue (though there are other scenarios that produce the same issue with various other assemblies):

```xml
<!-- test.csproj -->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.11.2" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.0" />
  </ItemGroup>

</Project>
```

```csharp
// Program.cs
using Microsoft.Data.SqlClient;

public class Program
{
    public static void Main()
    {
        // We just need to cause AcquireTokenAsync to be jitted.
        // In practice this'll typically happen during a call to
        // SqlConnection.Open() when authenticating via AD
        new ActiveDirectoryAuthenticationProvider().AcquireTokenAsync(null);
    }
}

```

Build this project and observe the lack of binding redirect for `Azure.Core` (and others, eg `Tasks.Extensions`) in `bin\Debug\net472\test.exe.config`:

```xml<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.2" />
  </startup>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Identity.Client" publicKeyToken="0a613f4dd989e8ae" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.60.3.0" newVersion="4.60.3.0" />
      </dependentAssembly>
    </assemblyBinding>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Buffers" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.3.0" newVersion="4.0.3.0" />
      </dependentAssembly>
    </assemblyBinding>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Diagnostics.DiagnosticSource" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-6.0.0.1" newVersion="6.0.0.1" />
      </dependentAssembly>
    </assemblyBinding>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Security.AccessControl" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Security.Cryptography.ProtectedData" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.5.0" newVersion="4.0.5.0" />
      </dependentAssembly>
    </assemblyBinding>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Text.Encodings.Web" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Text.Json" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.1.2" newVersion="4.0.1.2" />
      </dependentAssembly>
    </assemblyBinding>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Threading.Tasks.Extensions" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.2.0.1" newVersion="4.2.0.1" />
      </dependentAssembly>
    </assemblyBinding>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.ValueTuple" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.3.0" newVersion="4.0.3.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

Running the project using `dotnet run` causes the exception above.

### Expected behavior
The reference assemblies for `SqlClient` should correctly declare all of the library's (immediate) runtime dependencies. This will allow `ResolveAssemblyReference` to solve the versions correctly and generate the required binding redirects.

### Further technical details
Microsoft.Data.SqlClient version: 5.2.0 or 3.1.5 (but probably others too)
.NET target: net472
SQL Server version: Any
Operating system: Windows 11

**Additional context**
Probably not relevant, but: I found this issue in a large repo with thousands of projects. The repo is in the process of being migrated off of CoreXT and onto CentralPackageVersions.

**Comment by benjamin-hodgson** [comment]
I'm guessing https://github.com/dotnet/SqlClient/pull/2414 would fix the issue once and for all if/when it gets merged.

**Comment by benjamin-hodgson** [comment]
Is this a dupe of https://github.com/dotnet/SqlClient/issues/1900 ?

**Comment by arellegue** [comment]
We will investigate this issue and we'll get back to you when we have an update.

**Comment by benjamin-hodgson** [comment]
Looks like this'll work for now, at least for our purposes, but it's liable to become broken again as new versions of the upstream libraries come out. The root cause is the missing references in the ref assemblies. (I don't think this issue should be closed)

**Comment by zoeperryman** [comment]
With the release of Azure.Identity 1.12 (and Azure.Core 1.40) this is broken again. My full framework projects (net462 and net48) fail to automatically generate the binding redirects, it needs to be done manually.

Referencing the following project combination:

```
    <PackageReference Include="Azure.Identity" Version="1.12.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
```

Results in the following error:

> Microsoft.Data.SqlClient.SqlException : Could not load file or assembly 'Azure.Core, Version=1.38.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' or one of its dependencies.

Adding the following bindings *manually* to a app/web.config resolves the problem. But this should be done automatically when automatic binding redirects are enabled.

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Azure.Core" publicKeyToken="92742159e12e44c8" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.40.0.0" newVersion="1.40.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Identity.Client" publicKeyToken="0a613f4dd989e8ae" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.61.3.0" newVersion="4.61.3.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Azure.Identity" publicKeyToken="92742159e12e44c8" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.12.0.0" newVersion="1.12.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

**Comment by JRahnama** [comment]
@zoeperryman Do you suggest that this should be handled on the driver side or as a general workaround? I believe it would be overstepping for the driver to make decisions regarding user-defined redirects or bindings.

**Comment by zoeperryman** [comment]
I'm suggesting that the binding redirects should automatically be generated when referencing later versions of Azure (and other) libraries then what Microsoft.Data.SqlClient is compiled against. This works for all the other nuget packages out there (well most I guess), what is different or broken about this one?

@benjamin-hodgson's original post seemed to suggest this was a problem with the reference assemblies for Microsoft.Data.SqlClient in the nuget file. 

The fact that these bindings don't get added automatically means the bindings need to be manually added and maintained which is a pain and hugely error prone when you have dozens of solutions that require it.

**Comment by JRahnama** [comment]
Here is the package from that build. Simply change the extension to .nupkg. Please note, this is an unsigned test package and is not intended for production use.

[Microsoft.Data.SqlClient.6.0.0-pull.126701.zip](https://github.com/user-attachments/files/17103099/Microsoft.Data.SqlClient.6.0.0-pull.126701.zip)

**Comment by edwardneal** [comment]
Thanks @JRahnama - and yes, it's definitely not intended for production use. This package isn't designed to be anything more than a sanity check to make sure that the downstream projects referencing SqlClient build and that VS generates the correct binding redirects in the output app.config.

**Comment by DavidHopkinsFbr** [comment]
I think this issue just bit me. I had `Microsoft.Data.SqlClient 5.1.5` installed as a transitive dependency of `Microsoft.EntityFramework.SqlServer 6.5.1` (which is the current version). `Microsoft.Data.SqlClient 5.1.5` depends on `Microsoft.Identity.Client >= 4.56.0` and `Azure.Identity >= 1.10.3`, both of which minimum versions are flagged as vulnerable in the NuGet package repository. In a .NET 4.8 WPF project (with "auto-generate binding redirects" turned on), upgrading those transitive dependencies to their respective current versions broke `Microsoft.Data.SqlClient 5.1.5`, causing runtime exceptions like this:

```
System.TypeInitializationException: The type initializer for 'Microsoft.Data.SqlClient.SqlAuthenticationProviderManager' threw an exception.
---> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Identity.Client, Version=4.56.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae' or one of its dependencies. 
The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

I was able to eliminate the vulnerable dependencies and get a working `Microsoft.Data.SqlClient` by upgrading to 5.2.2, but a permanent fix for similar loading failures in the future would be welcome.

**Comment by DavidHopkinsFbr** [comment]
I should also note that if `Microsoft.Data.SqlClient 5.1.5` depends on vulnerable packages, and those packages cannot be upgraded without breaking `SqlClient`, then that version of `SqlClient` should also be flagged as Vulnerable. This will guide users to upgrade the whole `Microsoft.Data.SqlClient` version _and_ its dependencies to non-vulnerable versions, without runtime breakage.

**Comment by edwardneal** [comment]
I've just re-tested this with the latest versions (6.0.2, 5.2.3 and 5.1.7) of each SqlClient release, and this should now be working properly.

**Comment by cg110** [comment]
It's still not working with 6.0.2.  MSbuild picks up the ref dll and uses it to work out if any suggesting binding redirects are needed.  As the ref version doesn't mention all the dlls it doesn't cause redirects to be generated.

Could you just remove the ref dll? (as very few nugets provide a ref) and provide just the lib version, which means that msbuild will then use the lib to work out any binding redirects, and get it right.

The reproduction at the start of this ticket is still valid with newer nugets, eg:
```
  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.14.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.2" />
  </ItemGroup>
```
