### ISSUE TITLE
Cannot connect to Azure SQL Database with SqlClient when minimum TLS set to v1.3

### ISSUE THREAD

**Issue by frankbuckley** [dotnet/SqlClient#2546]
Attempting to connect to an Azure SQL Database with the minimum TLS version set to 1.3 using .NET 8.0.6 and SqlClient 5.2.1 fails with "Reason: Login failed due to client TLS version being less than minimal TLS version allowed by the server" or "A connection was successfully established with the server, but then an error occurred during the pre-login handshake"

(**Edited to reflect this reproduces on Windows and Mac OS as well**)

Error seen using latest ASP.NET Core Runtime image (mcr.microsoft.com/dotnet/aspnet:8.0.6-noble) and replicated in Ubuntu-24.04 on WSL, on Windows 11 and on Mac OS 14.5.

### To reproduce

- Create Azure SQL database and set minimum TLS version to 1.3
- With clean WSL installation of Ubuntu 24.04 with apt-get update/upgrade and latest .NET SDK installed using official install script, or on Windows 11 with latest .NET SDK, or on Mac OS with latest .NET SDK
- dotnet new console app / dotnet add package Microsoft.Data.SqlClient --version 5.2.1 

```c#
using Microsoft.Data.SqlClient;

var connection = new SqlConnection("Server=tcp:XXXXX.database.windows.net,1433;Initial Catalog=connect;Persist Security Info=False;User ID=XXXXX;Password=XXXXX;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;");

await connection.OpenAsync();

var command = new SqlCommand("SELECT 1", connection);

var reader = await command.ExecuteReaderAsync();

while (await reader.ReadAsync())
{
    Console.WriteLine(reader[0]);
}

Console.WriteLine("Completed!");
```

Result:

```c#
Unhandled exception. Microsoft.Data.SqlClient.SqlException (0x80131904): Reason: Login failed due to client TLS version being less than minimal TLS version allowed by the server.
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, SqlCommand command, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.CompleteLogin(Boolean enlistOK)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, TimeoutTimer timeout, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool, Func`3 accessTokenCallback)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location ---
   at Program.<Main>$(String[] args) in /home/frankbuckley/dev/temp/sqlclienttest/Program.cs:line 7
   at Program.<Main>(String[] args)
ClientConnectionId:47de995d-bd56-4adf-adc7-16fc0218cde8
Error Number:47072,State:1,Class:20
```

### Expected behavior

Application runs, outputs 1 and Completed.

### After adjusting OpenSSL configuration (on Ubuntu) [**turns out this is not needed - see comments below**]

Editing `/etc/ssl/openssl.cnf` to include the following gets past the "client TLS version being less than minimal TLS version" error:

```ini
[openssl_init]
providers = provider_sect
ssl_conf = ssl_sect

[ssl_sect]
system_default = system_default_sect

[system_default_sect]
MinProtocol = TLSv1.3
```

However, having done this, the following exception occurs:

```c#
Unhandled exception. Microsoft.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: SSL Provider, error: 31 - Encryption(ssl/tls) handshake failed)
 ---> System.IO.IOException: Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.Security.SslStream.ReceiveHandshakeFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions)
   at Microsoft.Data.SqlClient.SNI.SNITCPHandle.EnableSsl(UInt32 options)
   at Microsoft.Data.SqlClient.SNI.TdsParserStateObjectManaged.EnableSsl(UInt32& info, Boolean tlsFirst, String serverCertificateFilename)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, SqlCommand command, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.EnableSsl(UInt32 info, SqlConnectionEncryptOption encrypt, Boolean integratedSecurity, String serverCertificateFilename)
   at Microsoft.Data.SqlClient.TdsParser.ConsumePreLoginHandshake(SqlConnectionEncryptOption encrypt, Boolean trustServerCert, Boolean integratedSecurity, Boolean& marsCapable, Boolean& fedAuthRequired, Boolean tlsFirst, String serverCert)
   at Microsoft.Data.SqlClient.TdsParser.Connect(ServerInfo serverInfo, SqlInternalConnectionTds connHandler, TimeoutTimer timeout, SqlConnectionString connectionOptions, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, TimeoutTimer timeout, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool, Func`3 accessTokenCallback)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location ---
   at Program.<Main>$(String[] args) in /home/frankbuckley/dev/temp/sqlclienttest/Program.cs:line 5
   at Program.<Main>(String[] args)
ClientConnectionId:5e2506c5-46c3-4206-876a-768c434ae36f
```

Changing to `TrustServerCertificate=True` makes no difference.

As well as wondering what is required to make this work, if `MinProtocol = TLSv1.3` is enforced system-wide then other things will likely break (Cosmos DB currently only supports TLS 1.2, for example). Is there a way of configuring this just for SQL database connections?

**Comment by ErikEJ** [comment]
Have you tried with `Encrypt=Strict` 

https://learn.microsoft.com/en-us/sql/connect/ado-net/encryption-and-certificate-validation?view=sql-server-ver16#version-40

**Comment by frankbuckley** [comment]
@ErikEJ - thank you for the link and the suggestion:

`Encrypt=Strict` gets past TLS error without changes to `/etc/ssl/openssl.cnf` but results in "Login failed":

#### (1) With AZ SQL set to min TLS 1.2 and OpenSSL config as default and Encrypt=True

Connects and executes command

#### (2) With AZ SQL set to min TLS 1.2 and OpenSSL config as default and Encrypt=Strict

Connects and executes command

#### (3) With AZ SQL set to min TLS 1.3 and OpenSSL config as default and Encrypt=True

"Login failed due to client TLS version being less than minimal TLS version allowed by the server."

#### (4) With AZ SQL set to min TLS 1.3 and OpenSSL config as default and Encrypt=Strict

"Login failed for user 'user_name'."

(Which it cannot be the problem as connection string identical for all except for Encrypt changes: if I switch back to 2 from 4 - no connection string change - it works.)

**Comment by frankbuckley** [comment]
OK - I assumed this was a Linux thing. However, I can replicate on Windows 11 - using the same reproduction as above - results for 1, 2, 3 and 4 are exactly the same.

```
dotnet --info
.NET SDK:
 Version:           8.0.301
 Commit:            1a0e9c0300
 Workload version:  8.0.300-manifests.011fccd5
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22635
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.301\

```

**Comment by frankbuckley** [comment]
...and on macOS - fails but with one difference (4):

(1) With AZ SQL set to min TLS 1.2 and OpenSSL config as default and Encrypt=True

Connects and executes command

(2) With AZ SQL set to min TLS 1.2 and OpenSSL config as default and Encrypt=Strict

Connects and executes command

(3) With AZ SQL set to min TLS 1.3 and OpenSSL config as default and Encrypt=True

"Login failed due to client TLS version being less than minimal TLS version allowed by the server."

(4) With AZ SQL set to min TLS 1.3 and OpenSSL config as default and Encrypt=Strict

"Login failed due to client TLS version being less than minimal TLS version allowed by the server."

```
dotnet --info
.NET SDK:
 Version:           8.0.301
 Commit:            1a0e9c0300
 Workload version:  8.0.300-manifests.011fccd5
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.5
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.301/
```

**Comment by JRahnama** [comment]
@frankbuckley TLS 1.3 has a different setup comparing to TLS 1.2. 

This seems like your machine/Server setup issue. Basically, when you set `Encrypt = Strict` in your connection string or set `Encrypt = SqlConnectionEncryptOption.Stric` in SqlConnectionStringBuilder both server and client need to be supporting TLS1.3 if you want the connection use TLS 1.3. If server supports TLS 1.3 and the client does not it will fallback on TLS 1.2.

Keep in mind that TLS 1.3 is enabled on Windows 11 by default and it is only supported on SQL Server 2022 and Azure SQL DB. I have tested that with Azure SQL DB and it works as expected. I would suggest look into[ this documentation](SqlConnectionEncryptOption) and set your SQL DB accordingly.

Also I would suggest setting the minimum TLS version to 1.2 and let OS decide which one to use.

**Comment by frankbuckley** [comment]
> I have tested that with Azure SQL DB and it works as expected.

@JRahnama - thanks for the explanation - just to confirm, have you observed it working **with minimum TLS 1.3 selected on Azure SQL Database**?

![image](https://github.com/dotnet/SqlClient/assets/5655810/df2bf646-9556-4f15-96c4-fd780afe19c3)

If I set this 1.2, all works fine. If I set this to 1.3, it fails from Ubuntu 24.04, Windows 11 and Mac OS 14.5 when using SqlClient 5.2.1 and .NET 8.0, including using the official ASP.NET Core Docker Ubuntu Noble image.

> Keep in mind that TLS 1.3 is enabled on Windows 11 by default and it is only supported on SQL Server 2022 and Azure SQL DB

I have tried two Azure SQL databases in different regions and got the same results from Windows 11.

```
Edition	Windows 11 Pro
Version	23H2
OS build	22635.3646
```

Maybe I should raise an Azure Support request?

**Comment by kross51** [comment]
I have run into the exact same issue with my Azure Function. Encrypt=True and Encrypt=Strict results in same error when I switch my Azure SQL database to TLS 1.3 (when I set back to TLS 1.2 connections works fine again).

**Comment by dauinsight** [comment]
Hi @frankbuckley , when running on my machine:

```
.NET SDK:
 Version:           8.0.205
 Commit:            3e1383b780
 Workload version:  8.0.200-manifests.818b3449

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.205\
```

(1) With AZ SQL set to min TLS 1.3 and Encrypt=True

"Login failed due to client TLS version being less than minimal TLS version allowed by the server."

(2) With AZ SQL set to min TLS 1.3 and Encrypt=Strict

Connects and Application runs, outputs 1 and Completed.

My connection string:

`
"Server=tcp:XXXX.database.windows.net,1433;Initial Catalog=XXXX;Persist Security Info=False;User ID=XXXX;Password=XXXX;MultipleActiveResultSets=False;Encrypt=Strict;TrustServerCertificate=False;Connection Timeout=30;"
`

**Comment by frankbuckley** [comment]
Hi @dauinsight - thank you for testing.

It is still failing for me, so I wondered if the SDK (runtime) made a difference, so I set up a repro test and workflow for testing. This suggests the runtime makes no difference:

https://github.com/frankbuckley/sqlclient-azuresql-tls13/actions/runs/9414629170

However, while the test passes on Ubuntu 22.04, Ubuntu 24.04 and Windows Server 2022, it consistently fails on MacOS. It also passes using Ubuntu .NET SDK containers:

https://github.com/frankbuckley/sqlclient-azuresql-tls13/actions/runs/9414883210

I am on Windows 10.0.22635, while you are on 10.0.22631 - I don't know if that could cause a problem.

**Comment by frankbuckley** [comment]
I can also replicate on Windows 10.0.22631 ARM:

![image](https://github.com/dotnet/SqlClient/assets/5655810/47340238-9704-4c80-9bd6-2ad109d30339)

**Comment by JRahnama** [comment]
So, to add more to @dauinsight findings,

I was able to get connection with below setup:
```C#
SqlConnectionStringBuilder builder = new()
{
    DataSource = "*******.database.windows.net",
    UserID = "******",
    Password = "*******",
    InitialCatalog = "TestDB",
    Encrypt = SqlConnectionEncryptOption.Strict
};
```

This will confirm the issue is not related to SqlClient driver.

If you are using SSMS try change Network Packet size from 4096 to 8192 or higher to see the outcome.
![image](https://github.com/dotnet/SqlClient/assets/32077152/c6b55a6e-5ec4-4628-85cb-21f74511d530)

**Comment by JRahnama** [comment]
@frankbuckley I suggest contacting Azure support.

**Comment by JRahnama** [comment]
@frankbuckley I can also suggest going to Registory Editor in the path of 
`Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\` and adding a key for TLS 1.3 same as TLS 1.2  and disable TLS 1.2 that may help you get connection, but that probably will have some effects on other areas of your machine's functionalities.
