### ISSUE TITLE
Fail to connect after database failover

### ISSUE THREAD

**Issue by brunoblank** [dotnet/SqlClient#2610]
### Describe the bug
We have a database setup using mirroring. 

Connection-String: `server=tcp:172.21.6.8;user id=<user>;password=<password>;database=<database>;Failover Partner=tcp:172.21.6.7;TrustServerCertificate=true`

When the database fails over from the "secondary" then everything works instantly.
When the database fails over from the "primary" (the one that _server_ points to) then we see the exception below. The connection works if the application is restarted or if there has been no requests for a couple of minutes.

The exception indicates that `Named pipes` are being used even though we are specifying `tcp:`

```
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, SqlCommand command, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.Connect(ServerInfo serverInfo, SqlInternalConnectionTds connHandler, TimeoutTimer timeout, SqlConnectionString connectionOptions, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, TimeoutTimer timeout, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginWithFailover(Boolean useFailoverHost, ServerInfo primaryServerInfo, String failoverHost, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool, Func`3 accessTokenCallback)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.InternalOpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Program.<Main>$(String[] args) in C:\temp\SQLFailover\SQLFailover\Program.cs:line 14
   at Program.<Main>$(String[] args) in C:\temp\SQLFailover\SQLFailover\Program.cs:line 18
```

### To reproduce
```c#
using Microsoft.Data.SqlClient;

Console.WriteLine("Hello, World!");

var connectionString = "server=tcp:172.21.6.8;user id=<user>;password=<password>;database=<database>;Failover Partner=tcp:172.21.6.7;TrustServerCertificate=true";

while (true)
{
    try
    {
        await using var connection = new SqlConnection(connectionString);
        await connection.OpenAsync();

        var command = new SqlCommand("SELECT 1", connection);
        await command.ExecuteNonQueryAsync();
        Console.WriteLine("Success");
    }
    catch (Exception ex)
    {
        Console.WriteLine($"Error: {ex.Message}\r\n{ex.StackTrace}");
    }
    await Task.Delay(2000);
} 
```
cs-proj;
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.1" />
  </ItemGroup>

</Project>
```

### Expected behavior
Connection to the failover partner to succeed 

### Further technical details
Microsoft.Data.SqlClient version: 5.2.1
.NET target: net8.0
SQL Server version: SQL Server 13.0.5698.0
Operating system: Windows (also aks: _FROM mcr.microsoft.com/dotnet/aspnet:8.0_)

**Additional context**

**Comment by arellegue** [comment]
Thank you for reporting this issue with database failover. Could you confirm that you have configured the endpoints correctly. Please refer to the documentation at https://learn.microsoft.com/en-us/sql/database-engine/database-mirroring/the-database-mirroring-endpoint-sql-server?view=sql-server-ver16.

**Comment by brunoblank** [comment]
Yes, the application can connect to both servers. We have only experienced the problem described when fail over from the primary side to the failover partner. The other directions works without any issues.
Thanks
/Bruno

**Comment by arellegue** [comment]
We are wondering if this is the first time you had this issue and if it has worked before.

I believe the database mirroring endpoints must have authorization to connect to each other in addition to the client application's authorization to connect to each database.  Could you confirm that authentication between the database mirroring endpoints are in place. Please refer to the documentation at https://learn.microsoft.com/en-us/sql/database-engine/database-mirroring/example-setting-up-database-mirroring-using-windows-authentication-transact-sql?view=sql-server-ver16

**Comment by brunoblank** [comment]
![image](https://github.com/dotnet/SqlClient/assets/13798530/a6999093-cd6f-4ada-aab8-cc41ffff3716)

**Comment by brunoblank** [comment]
As a side note, our legacy application running with .net framework 4.6.1 with System.Data.SqlClient does not experience connection problems when the database fails over.

**Comment by arellegue** [comment]
At this point we can assume that it is an initial setup as we noticed that you are using the option "High safety without automatic failover" but did not configure a witness server instance. Please refer to the documentation on using that option at 
https://learn.microsoft.com/en-us/sql/database-engine/database-mirroring/setting-up-database-mirroring-sql-server?view=sql-server-ver16

**Comment by brunoblank** [comment]
We are experiencing the problem in the production environment, which is configured with a witness server. We do not choose to do failover in the production environment, but when the database failover we either have to restart our applications or do manual failover back to the original state to restore database connectivity.

It is not possible for us to run these kind of test in the production environment, so we have created the smallest setup both code and databases to be able to reproduce the problem. 

Thanks for looking into this problem
/Bruno

**Comment by arellegue** [comment]
Thank you for the clarification. We will investigate and try to reproduce the issue and then you know.

**Comment by brunoblank** [comment]
Hi @arellegue 

Is there any updates to this issue?

**Comment by josephgrice** [comment]
Hey @arellegue 

I am also experiencing this error when failing over mirrored instances. 

In my case this started when moving hosting patterns from EC2 to ECS Fargate running on net8.0 and using package `Microsoft.Data.SqlClient` Version `5.2.1` 

These failovers continue to work successfully for our services still hosted on EC2, running on net8.0 and using package `Microsoft.Data.SqlClient` Version `5.2.1` but this issue seems to manifest when switching to the container runtime (Ubuntu) and can be reproduced both locally and when hosted in ECS Fargate.

Also, similarly to @brunoblank we also see this - 
- `When the database fails over from the "secondary" then everything works instantly.`
- `When the database fails over from the "primary" (the one that server points to) then we see the exception below`
- `A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught)`

Has there been any updates on this?

**Comment by David-Engel** [comment]
Given the second observance of this issue, I tried to repro this locally and wasn't able to.

I have a mirrored configuration (two SQL Server 2022 instances on two Windows Server 2022 VMs) with no witness. Running the code in the top comment always results in success after failover from primary to secondary or secondary to primary (after 1 or 2 login failure errors during the transition).

I'm running the client on Windows 11 using .NET 8. I tried some variations of native and Managed SNI on Windows along with variations of `server=<IP address>`, `server=tcp:<IP address>`, `server=tcp:<name>`, Encrypt=true/false. I don't have docker or WSL set up locally, so haven't been able to try an Ubuntu client (container or plain WSL).

I'm not sure what else could be different that would cause the issue.

**Comment by brunoblank** [comment]
Hi @David-Engel,

From the exception we see it looks like the driver is trying a `Named Pipes` connection

> A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)

We don't have named pipes enabled on our sql-server. We are experience the problem both in aks and on my windows machine.

Is there any other test I can do?

**Comment by josephgrice** [comment]
Hey @David-Engel ,

Thanks for looking into this.

I notice you mention this in your testing - 
`I don't have docker or WSL set up locally, so haven't been able to try an Ubuntu client (container or plain WSL).`

But as per my comment here - 
`this issue seems to manifest when switching to the container runtime (Ubuntu) and can be reproduced both locally and when hosted in ECS Fargate.`

The same code gracefully handles failovers when hosted locally or on EC2 when not containerised

Would you be able to conduct similar tests with the follow parameters?
- Code running in an Ubuntu container
- Under a constant load (enough for active connections to be in the pool during the failover)

**Comment by VladimirReshetnikov** [comment]
I have been investigating this issue, and I'd like to share my findings and seek some additional information:

## Findings

1. Protocol Handling:
   The `ServerInfo` class is responsible for storing and manipulating server connection details. It has a method `SetDerivedNames` that sets the `ExtendedServerName` property:

   ```csharp
   internal void SetDerivedNames(string protocol, string serverName)
   {
       if (!string.IsNullOrEmpty(protocol))
       {
           ExtendedServerName = protocol + ":" + serverName;
       }
       else
       {
           ExtendedServerName = serverName;
       }
       ResolvedServerName = serverName;
   }
   ```

   This method is crucial because it determines whether the protocol (e.g., "tcp:") is prepended to the server name. It's the only place I found where the information about the protocol can potentially be lost.

2. Failover Logic:
   In the `LoginWithFailover` method, I found a section that updates the failover partner information:

   ```csharp
   if (null != ServerProvidedFailOverPartner && failoverServerInfo.ResolvedServerName != ServerProvidedFailOverPartner)
   {
       SqlClientEventSource.Log.TryAdvancedTraceEvent("<sc.SqlInternalConnectionTds.LoginWithFailover|ADV> {0}, new failover partner={1}", ObjectID, ServerProvidedFailOverPartner);
       failoverServerInfo.SetDerivedNames(string.Empty, ServerProvidedFailOverPartner);
   }
   ```

3. Potential Issue:
   If this condition is met, `SetDerivedNames` is called with an empty string as the protocol. This would erase the "tcp:" prefix, which would lead to the connection attempting other protocols, including Named Pipes.

## Limited Scope and Applicability

@brunoblank, based on the screenshot you provided showing your mirroring configuration, I don't see why the condition `null != ServerProvidedFailOverPartner && failoverServerInfo.ResolvedServerName != ServerProvidedFailOverPartner` would be met in your case. This condition can occur when the server provides a failover partner that differs from what was initially specified in the connection string. However, I'd like to confirm it. Does your application ever receive a failover partner address from the server that differs from what's specified in your connection string?

## Possible Fix and Next Steps

If this issue is confirmed to be the root cause, one potential fix would be to modify the `LoginWithFailover` method to preserve the protocol information:

```csharp
if (null != ServerProvidedFailOverPartner && failoverServerInfo.ResolvedServerName != ServerProvidedFailOverPartner)
{
    SqlClientEventSource.Log.TryAdvancedTraceEvent("<sc.SqlInternalConnectionTds.LoginWithFailover|ADV> {0}, new failover partner={1}", ObjectID, ServerProvidedFailOverPartner);
    
    // Preserve the existing protocol instead of using an empty string
    string existingProtocol = failoverServerInfo.UserProtocol;
    failoverServerInfo.SetDerivedNames(existingProtocol, ServerProvidedFailOverPartner);
}
```

But I'm continuing my investigation to identify other possible causes for the behavior you're experiencing. The scenario I've already identified might not be the actual explanation for the issue in your specific setup.

**Comment by David-Engel** [comment]
@brunoblank 
> From the exception we see it looks like the driver is trying a `Named Pipes` connection
> 
> > A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
> 
> We don't have named pipes enabled on our sql-server. We are experience the problem both in aks and on my windows machine.
> 
> Is there any other test I can do?

I saw that and that's pretty strange given all your connection settings. I don't have named pipes enabled on my servers, either. The client-side code is pretty simple, so I don't think we have significant differences there (assuming you are running exactly what you said). Maybe there's a difference in how we have our mirrors configured. Do you have a set of scripts you used to configure your test mirror environment so that can be replicated?

@josephgrice 
> I notice you mention this in your testing - `I don't have docker or WSL set up locally, so haven't been able to try an Ubuntu client (container or plain WSL).`
> 
> But as per my comment here - `this issue seems to manifest when switching to the container runtime (Ubuntu) and can be reproduced both locally and when hosted in ECS Fargate.`
> 
> The same code gracefully handles failovers when hosted locally or on EC2 when not containerised
> 
> Would you be able to conduct similar tests with the follow parameters?
> 
> * Code running in an Ubuntu container
> * Under a constant load (enough for active connections to be in the pool during the failover)

Yes, I noticed that. But the original reporter repro'd it on Windows and that environment was easier for me to replicate. I also tried running the Linux code (managed SNI) on Windows to see if it made a difference. (The rest of the code is virtually identical) I'm kind of stumped why it would behave differently specifically from an Ubuntu container. I did try constant load with pooled connections.

I'll let @VladimirReshetnikov investigate this issue further.

**Comment by brunoblank** [comment]
@David-Engel, @VladimirReshetnikov Tanks for looking into this problem.

I am talking to the infra team to get the scripts for setting up mirroring. 

While checking database versions, we noticed that the test-environment is running in an "unsupported" setup.
```
Primary:
Microsoft SQL Server 2019 (RTM-CU17) (KB5016394) - 15.0.4249.2 (X64)   Jul 22 2022 12:11:33   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2022 Datacenter 10.0 <X64> (Build 20348: ) (Hypervisor)

Failover Partner:
Microsoft SQL Server 2016 (SP2-CU12) (KB4536648) - 13.0.5698.0 (X64)   Feb 15 2020 01:47:30   Copyright (c) Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor)  
```
Where we can see that the primary is running 2019 and the failover partner is running 2016. This could be the reason why we are able to do the failover from 2016 => 2019 but not the other direction.

We will now create a database in the production environment where we can do failover testing and verify that the test program run into the same problem.

We are running these versions in the production environment
```
Primary:
Microsoft SQL Server 2016 (SP3-OD) (KB5006943) - 13.0.6404.1 (X64)   Oct 18 2021 09:37:01   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor) 

Failover Partner:
Microsoft SQL Server 2016 (SP3-GDR) (KB5029186) - 13.0.6435.1 (X64)   Jul 30 2023 19:53:42   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor)

Witness:
Microsoft SQL Server 2016 (SP3-GDR) (KB5040946) - 13.0.6441.1 (X64)   Jun 18 2024 00:46:21   Copyright (c) Microsoft Corporation  Express Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor)
```

Is there any diagnostics I can enable for the SqlClient to help understand what goes wrong?

Thanks
Bruno

**Comment by brunoblank** [comment]
@David-Engel 

We have now run the test in the production environment on a newly created database using this script:
```
BACKUP DATABASE [BrunoDatabase] TO  DISK = N'F:\Log\BrunoDatabase.bak' WITH NOFORMAT, NOINIT,  NAME = N'BrunoDatabase-Full Database Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
BACKUP LOG [BrunoDatabase] TO  DISK = N'F:\Log\BrunoDatabase_TRANS.bak' WITH NOFORMAT, NOINIT,  NAME = N'BrunoDatabase-Transaction Log  Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 10

RESTORE DATABASE [BrunoDatabase] FROM  DISK = N'F:\Log\BrunoDatabase.bak' WITH  FILE = 1,  MOVE N'BrunoDatabase' TO N'F:\data\BrunoDatabase.mdf',  MOVE N'BrunoDatabase_log' TO N'F:\log\BrunoDatabase_log.LDF',  NORECOVERY,  NOUNLOAD,  STATS = 10
RESTORE LOG [BrunoDatabase] FROM  DISK = N'F:\Log\BrunoDatabase_TRANS.bak' WITH  FILE = 1,  NORECOVERY,  NOUNLOAD,  STATS = 10

--- Mirror side  ---
alter database BrunoDatabase set partner = 'tcp://10.31.10.4:5024'

---- Principal side  ---
alter database BrunoDatabase set partner = 'tcp://10.31.10.5:5024';


alter database BrunoDatabase set witness = 'tcp://10.31.10.9:5024';
```

The exception occurs when failing from primary side to failover partner (10.31.10.4 => 10.31.10.5). But not the other direction.

**Comment by josephgrice** [comment]
> @brunoblank
> 
> > From the exception we see it looks like the driver is trying a `Named Pipes` connection
> > > A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
> > 
> > 
> > We don't have named pipes enabled on our sql-server. We are experience the problem both in aks and on my windows machine.
> > Is there any other test I can do?
> 
> I saw that and that's pretty strange given all your connection settings. I don't have named pipes enabled on my servers, either. The client-side code is pretty simple, so I don't think we have significant differences there (assuming you are running exactly what you said). Maybe there's a difference in how we have our mirrors configured. Do you have a set of scripts you used to configure your test mirror environment so that can be replicated?
> 
> @josephgrice
> 
> > I notice you mention this in your testing - `I don't have docker or WSL set up locally, so haven't been able to try an Ubuntu client (container or plain WSL).`
> > But as per my comment here - `this issue seems to manifest when switching to the container runtime (Ubuntu) and can be reproduced both locally and when hosted in ECS Fargate.`
> > The same code gracefully handles failovers when hosted locally or on EC2 when not containerised
> > Would you be able to conduct similar tests with the follow parameters?
> > 
> > * Code running in an Ubuntu container
> > * Under a constant load (enough for active connections to be in the pool during the failover)
> 
> Yes, I noticed that. But the original reporter repro'd it on Windows and that environment was easier for me to replicate. I also tried running the Linux code (managed SNI) on Windows to see if it made a difference. (The rest of the code is virtually identical) I'm kind of stumped why it would behave differently specifically from an Ubuntu container. I did try constant load with pooled connections.
> 
> I'll let @VladimirReshetnikov investigate this issue further.

Thanks for the update on this.

@VladimirReshetnikov did you get a chance to look into this further?

**Comment by brunoblank** [comment]
@VladimirReshetnikov have you had time to investigate further?

Thanks
/Bruno

**Comment by SeeWhat** [comment]
I've experienced this scenario before, and what you need to remember is how the values in the connection string are used.

The _Server/Data Source/etc_ value from the connection string is used to perform the initial connection, if that initial connection fails **only then** it will use the _Failover Partner_ details. 

When a connection is established, the driver receives the failover partner details from the database. The value returned for the failover partner does not necessarily contain the FQDN to the failover partner. (At least we could never figure out how to get it to contain the FQDN and I don't believe you can have it return an IP address either.) It seems even if you point mirroring to an IP, when the mirror is established, it ends up fetching the server’s name from the partner and uses that.

i.e. if your severs are configured as `primary-sql.mycompany.com` and `secondary-sql.mycompany.com`
The driver will be receiving the value `secondary-sql` only.

If you run the below query, you'll see the _mirroring_partner_instance_ just contains the server name. This is what the driver is trying to connect to when you failover if you've already got a connection.

`SELECT DB_NAME(database_id) AS 'DatabaseName', mirroring_partner_instance FROM sys.database_mirroring`

If you've confirmed this is the case, you can try to resolve it a number of ways.
1. Create specific host entries on your machine/container to directly resolve the hostname to IP
2. Setup specific name resolution on your machine/container to resolve the name but appending in various domains.
3. If your environment is resolving IPs via DHCP, you can have your team configure the DHCP properties to include the domain which gets passed down to the machine/container when it gets an IP.

For this last scenario in AWS you can see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-dhcpoptions.html#aws-resource-ec2-dhcpoptions-properties

You should then set the DomainName property to your domain.

Hopefully this helps.

**Comment by brunoblank** [comment]
@SeeWhat Thanks for your insights,

I ran the query and the database and we can confirm it is the server name.

We are not running DNS in our environment and using option `1` there is no problem doing the failover in both directions from my local machine. I will continue test this in the our AKS environment ant see if it solves the problem

/Bruno

**Comment by josephgrice** [comment]
We were unable to get it working with SQL server standard edition. 

Upgrading to enterprise and using high avaliablilty fixed the problem for us.

**Comment by ktrace2** [comment]
For anyone experiencing the "Named Pipes Provider, error: 40 - Could not open a connection to SQL Server" error after a failover from primary to failover partner. Ensure you can resolve both primary and failover SQL server instances by only their DNS name without their DNS suffix.

We had this issue when using an AG on SQL VMs in Azure. 

For example we had two SQL nodes.

**Domain A**
SQL-01.DomainA
SQL-02.DomainA

Connection string specified both like this:
`Data Source=tcp:SQL-01.DomainA;Failover Partner=tcp:SQL-02.DomainA`

Failing over from SQL-02 to SQL-01 worked no problem but when failover over from SQL-01 to SQL-02 we got the error above and it would never recover.

The issue turned out to be the following:

When failing over from SQL-01 to SQL-02 the application did not use the FQDN from the Failover Partner in the connection string but instead only used SQL-02 without the DNS suffix. This caused problems for any computers not in Domain A as they did not know how to resolve SQL-02.

Solution was to add a CNAME in Domain B, etc. for SQL-02 -> SQL-02.DomainA

You can check the DNS name it will use by running the following query:
`SELECT * FROM sys.dm_hadr_cluster_members`
The member_name column shows the DNS name without the DNS suffix.

This also fixed a problem in SQL Management Studio allowing us to perform an AG failover. Before the Server name was always greyed out and hardcoded to SQL-02 without the DNS suffix. It never allowed us to connect to the secondary replica because it could not resolve it. After adding the CNAME we could continue with the failover wizard.
