### ISSUE TITLE
System.AggregateException: One or more errors occurred. (Name or service not known)

### ISSUE THREAD

**Issue by huangsha-ops** [dotnet/SqlClient#2613]
hello everyone  I get a problem confused me
I use ip connect to sqlsever server but I still got the dns error
System.AggregateException: One or more errors occurred. (Name or service not known)
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): Name or service not known
   at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses, AddressFamily addressFamily, ValueStopwatch stopwatch)
   at System.Net.Dns.<>c.<GetHostEntryOrAddressesCoreAsync>b__33_0(Object s, ValueStopwatch stopwatch)
   at System.Net.Dns.<>c__DisplayClass39_0`1.<RunAsync>b__0(Task <p0>, Object <p1>)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.InternalOpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at FreeSql.Internal.CommonProvider.DbConnectionStringPool.GetAsync()
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteReaderMultipleAsync(Int32 multipleResult, DbConnection connection, DbTransaction transaction, Func`3 fetchHandler, Action`2 schemaHandler, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms, CancellationToken cancellationToken)

this is my sqlserver connection config
Data Source=192.168.0.195;Initial Catalog=database;User ID=**;Password=***; MultipleActiveResultSets=True;Encrypt=False;TrustServerCertificate=True;Min Pool Size=1;Max Pool Size=200",
who can help me? Thank you very much

**Comment by h200621119** [comment]
<img width="1131" alt="image" src="https://github.com/dotnet/SqlClient/assets/7223124/d86b70c8-03ae-4467-aa47-3220a8b0261d">
this is a trace you can see  the last sql command return this error 
the envirment is dotnet6.0  sqlclient 5.2.0

**Comment by ErikEJ** [comment]
The IP address is an address in the private range - is that deliberate?

**Comment by h200621119** [comment]
> The IP address is an address in the private range - is that deliberate?

yes,  it's a private ip  in the same network

**Comment by arellegue** [comment]
@huangsha-ops You can do the following:
1. Check if the Sql Server is using TCP protocol and using default port 1433. You can use SqlServer Configuration Manager to see if it is.

2. The firewall where Sql Server is running is not blocking your client application's traffic. Use telnet or powershell test-netconnection to see if "test-netconnection 192.168.0.195 -P 1433" succeeds.

For example issue the powershell command from you client machine, (change the localhost to your SqlServer Ip address)

test-netconnection localhost -P 1433
ComputerName     : localhost
RemoteAddress    : ::1
RemotePort       : 1433
InterfaceAlias   : Loopback Pseudo-Interface 1
SourceAddress    : ::1
TcpTestSucceeded : True

4. The firewall in your client machine is not blocking traffic from the SqlServer.

**Comment by huangsha-ops** [comment]
> @huangsha-ops You can do the following:
> 
> 1. Check if the Sql Server is using TCP protocol and using default port 1433. You can use SqlServer Configuration Manager to see if it is.
> 2. The firewall where Sql Server is running is not blocking your client application's traffic. Use telnet or powershell test-netconnection to see if "test-netconnection 192.168.0.195 -P 1433" succeeds.
> 
> For example issue the powershell command from you client machine, (change the localhost to your SqlServer Ip address)
> 
> test-netconnection localhost -P 1433 ComputerName : localhost RemoteAddress : ::1 RemotePort : 1433 InterfaceAlias : Loopback Pseudo-Interface 1 SourceAddress : ::1 TcpTestSucceeded : True
> 
> 3. The firewall in your client machine is not blocking traffic from the SqlServer.

@arellegue  hi
The protocol and port has no problem,  I can promise.  there is no firewall  
This  is an accidental error. Most of time the sql are running OK.

**Comment by arellegue** [comment]
Could you try to use Max Pool Size=15 and see if you still get the same issue.

**Comment by cheenamalhotra** [comment]
Closing as stale
