### ISSUE TITLE
A transport-level error has occurred when receiving results from the server. (provider: TCP Provider, error: 0 - Undefined error: 0)

### ISSUE THREAD

**Issue by Oriu** [dotnet/SqlClient#2640]
Using Microsoft.Data. SqlClient on MAC M1 MAX's rider  connection to SqlServer query error,But it can be done on the window。

Code:
string connectionString = "Persist Security Info=True;TrustServerCertificate=True;Data Source=myaddress;User ID=myuserid;Password=mypassword;DataBase=mydbname";  
using (SqlConnection connection = new SqlConnection(connectionString))  
{
    connection.Open();  
    using (SqlCommand command = new SqlCommand("SELECT * FROM myTable", connection))  
    {  
        command.ExecuteReader();  
    }  
    connection.Close();  
}

Error message：
Microsoft.Data.SqlClient.SqlException (0x80131904): A transport-level error has occurred when receiving results from the server. (provider: TCP Provider, error: 0 - Undefined error: 0)
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParserStateObject.ThrowExceptionAndWarning(Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParserStateObject.ReadSniError(TdsParserStateObject stateObj, UInt32 error)
   at Microsoft.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync()
   at Microsoft.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()
   at Microsoft.Data.SqlClient.TdsParserStateObject.TryPrepareBuffer()
   at Microsoft.Data.SqlClient.TdsParserStateObject.TryReadByte(Byte& value)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at SqlSugar.AdoProvider.GetDataReader(String sql, SugarParameter[] parameters)
   at SqlSugar.AdoProvider.SqlQuery[T,T2,T3,T4,T5,T6,T7](String sql, Object parameters)
   at SqlSugar.AdoProvider.SqlQuery[T](String sql, SugarParameter[] parameters)
   at SqlSugar.AdoProvider.SqlQuery[T](String sql, Object parameters)
   at TestWeb.Controllers.WeatherForecastAppService.PostProducts(TestPage testPage) in /Volumes/magic/MyWork/MyCode/xy.libcore/TestWeb/AppServices/WeatherForecastController.cs:line 333
ClientConnectionId:1366f45c-7f42-4d3a-bdec-98b0006a4e58

**Comment by chenxiang0114** [comment]
My Microsoft.Data.SqlClient already update to the version 5.2.1.  
![image](https://github.com/dotnet/SqlClient/assets/26212607/a7f4e05e-45b6-495e-8e2f-98014f56e978)

If I use 2.1.7, SQL Server can work completely normally, but upgrading to 5.2.0 5.2.1 will not work

.net8

**Comment by arellegue** [comment]
Thank you for reporting this issue. Could you provide an event trace log, please. You can find more information at:
https://learn.microsoft.com/en-us/sql/connect/ado-net/enable-eventsource-tracing?view=sql-server-ver16

Please provide 2 event trace logs, one from 2.1.7 and one for 5.2.1 versions of the SqlClient driver.

Once, we receive the above information, we can begin our investigation.

**Comment by Oriu** [comment]
> 感谢您报告此问题。请提供事件跟踪日志。您可以在以下位置找到更多信息： [https://learn.microsoft.com/en-us/sql/connect/ado-net/enable-eventsource-tracing ?view=sql-server-ver16](https://learn.microsoft.com/en-us/sql/connect/ado-net/enable-eventsource-tracing?view=sql-server-ver16)
> 
> 请提供 2 个事件跟踪日志，一个来自 2.1.7 版本，另一个来自 SqlClient 驱动程序 5.2.1 版本。
> 
> 一旦我们收到上述信息，我们就可以开始调查。

But my computer is macOS, it seems like I can't run PerfView and Xperf for collection? Can you provide me with more detailed methods for collecting information on macOS?

**Comment by Oriu** [comment]
> Thank you for reporting this issue. Could you provide an event trace log, please. You can find more information at: https://learn.microsoft.com/en-us/sql/connect/ado-net/enable-eventsource-tracing?view=sql-server-ver16
> 
> Please provide 2 event trace logs, one from 2.1.7 and one for 5.2.1 versions of the SqlClient driver.
> 
> Once, we receive the above information, we can begin our investigation.

But my computer is macOS, it seems like I can't run PerfView and Xperf for collection? Can you provide me with more detailed methods for collecting information on macOS?

**Comment by chenxiang0114** [comment]
[nettrace.zip](https://github.com/user-attachments/files/16082504/nettrace.zip)
 my computer is MacOS, so I can only provide log files with the suffix. nettrace. Can you parse them? If it doesn't work, could you please inform me of other collection methods for Mac OS (the document you sent above seems to be from Windows)

**Comment by arellegue** [comment]
The EventSource trace will work in Mac OS as long as you have dotnet SDK and runtimes installed for Mac OS.

https://learn.microsoft.com/en-us/dotnet/core/install/macos

**Comment by JRahnama** [comment]
@chenxiang0114 there are several breaking changes between versions 2.1.7 and 5.2.1. The most important one is changing the default value of the connection string property `Encrypt` from `false` to `true`. If you do not have a certificate (it could be self-signed) for SQL/client authentication and your application is not in production, I suggest testing by adding `Encrypt=false` to your connection string.

**Comment by samsharma2700** [comment]
Could you please also check on the latest version 5.2.2 (https://www.nuget.org/packages/Microsoft.Data.SqlClient/5.2.2) if this issue persists

**Comment by samsharma2700** [comment]
Closing as needed information has not been provided in quite some time. Please reopen if needed.
