### ISSUE TITLE
Application crash - DbConnectionPool.CleanupCallback - SemaphoreFullException

### ISSUE THREAD

**Issue by danielsOink** [dotnet/SqlClient#2673]
Currently we have an application crash due an unhandled exception on our customer systems. I'm not able to reproduce it on my developer machine. We are doing...
- a lot of async work in our code
- using DI for DbContext
- using manual creation of DbContext with using-statement or dispose-pattern
- a lot of work in multiple background threads

Exception Info : System.Threading.SemaphoreFullException: Adding the specified count to the semaphore would cause it to exceed its maximum count.

![image](https://github.com/user-attachments/assets/bf5214da-6b2f-4da5-94a0-a7dbb31c791d)

.NET Version: 7.0.14
CLR Version: 7.0.1423.51910
Microsoft.Data.SqlClient: 5.2.0
EF Core: 7.0.14

Please write me if you need further information. In the moment I've no further idea where I could search to fix the bug in our application. We only get the stacktrace of the image above, thus we've no information about the crash in our application!

**Comment by arellegue** [comment]
Thank for reporting this issue. Before we can begin our investigation, please provide a sample code of your application to reproduce the issue. We need to follow the issue based on your code.

As well, please provide an EventSource trace log from the SqlClient driver. More information on this can be found at:

https://learn.microsoft.com/en-us/sql/connect/ado-net/enable-eventsource-tracing?view=sql-server-ver16

However, this sort of error is usually caused by undisposed command and connection objects. Could you please ensure that unused command and connections objects are properly disposed of so as not to leave unused resources open. One way to do this is to wrap your connection and command with a using statement. Please try this and see if the error still comes up.

**Comment by danielsOink** [comment]
Thank you for your reply. Before I can give you a sample code, I needed to understand why the error was occurring. Currently, the problem only occurs on the customer's system after a day of running the application. 

I have already analysed the DbConnectionPool.CleanupCallback function and identified the issue. However, I am unsure why the Semaphore.Release() has no items to release. I would be grateful for any advice on how to proceed with analysing the issue.

I will enable the EventSource tracing an share these information with you!

**Comment by mrichgml** [comment]
Is there any update to this issue?
We are having an almost identical exception:
`Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Threading.SemaphoreFullException
   at System.Threading.Semaphore.Release(Int32)
   at System.Data.ProviderBase.DbConnectionPool.CleanupCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()`

We also are unable to replicate the issue but the customer experiences the issue regularly. The actual period between occurrences varies from a few days to less than a day.

**Comment by cheenamalhotra** [comment]
@mrichgml @danielsOink 

Checking in, if you're still experiencing this issue, please upload eventsource logs for the event when it occurs. If you can provide more information on how to reproduce the issue, that would be helpful in investigating for a fix as well.

Please try with the latest v6.1.3 to ensure you get latest fixes if they apply here.

**Comment by mdaigle** [comment]
@mrichgml @danielsOink checking in again to see if you have any updates?

**Comment by mrichgml** [comment]
We no longer have access to the customers system so we are unable to provide any more information.

**Comment by benrr101** [comment]
Closing as there is no repo available. If a repo becomes available, please post back and we can reopen and reassess.
