### ISSUE TITLE
.netcorapp tests fail to run using Test Explorer

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/SqlClient#268]
### Describe the bug
This test using netcoreapp2.1 causes all test to fail (not run, as discovery breaks) in Test Explorer

        public static bool IsUsingManagedSNI() => ManualTesting.Tests.DataTestUtility.IsUsingManagedSNI();

        [ConditionalFact(nameof(IsUsingManagedSNI))]
        public void NamedPipeInvalidConnStringTest_ManagedSNI()

```
[13-10-2019 1:27:20.938  Warning] [xUnit.net 00:00:01.4281768] Microsoft.Data.SqlClient.Tests: Catastrophic error during deserialization: System.InvalidOperationException: Could not de-serialize type 'Xunit.NetCore.Extensions.SkippedTestCase' because it lacks a parameterless constructor.
   at Xunit.Serialization.XunitSerializationInfo.DeserializeSerializable(Type type, String serializedValue) in C:\Dev\xunit\xunit\src\common\XunitSerializationInfo.cs:line 213
   at Xunit.Serialization.XunitSerializationInfo.Deserialize(Type type, String serializedValue) in C:\Dev\xunit\xunit\src\common\XunitSerializationInfo.cs:line 110
   at Xunit.Sdk.SerializationHelper.Deserialize[T](String serializedValue) in C:\Dev\xunit\xunit\src\common\SerializationHelper.cs:line 40
   at Xunit.Sdk.XunitTestFrameworkExecutor.Deserialize(String value) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\XunitTestFrameworkExecutor.cs:line 59
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at Xunit.Runner.VisualStudio.VsTestRunner.RunTestsInAssembly(IRunContext runContext, IFrameworkHandle frameworkHandle, LoggerHelper logger, TestPlatformContext testPlatformContext, IMessageSinkWithTypes reporterMessageHandler, AssemblyRunInfo runInfo) in C:\Dev\xunit\xunit\src\xunit.runner.visualstudio\VsTestRunner.cs:line 522
[13-10-2019 1:27:20.956  Informational] [xUnit.net 00:00:01.4581487]   Starting:    Microsoft.Data.SqlClient.Tests```

### Further technical details
Microsoft.Data.SqlClient version: Latest source
.NET target:  Core 21
SQL Server version: N/A
Operating system: Windows 10, VS 2019 16.3

**Comment by ErikEJ** [comment]
Workaround is to remove the test, and tests are discovered and run.

**Comment by cheenamalhotra** [comment]
Thanks for finding this out.
I'll address that when working on some test design changes, currently in progress.

**Comment by Wraith2** [comment]
a fix of this would also address https://github.com/dotnet/SqlClient/issues/217

**Comment by v-kaywon** [comment]
Issue is fixed after merging PR #280. Closing this issue.

**Comment by David-Engel** [comment]
I've been looking at this for a few hours now and it seems like VS 2019 always throws the catastrophic exception when a parameter to a ConditionFact returns false. VS 2017 runs most tests for me without throwing the catastrophic exception and skips tests when appropriate but it did throw this eventually, which I have not yet dug into:
```
The active test run was aborted. Reason: Assertion Failed
Invalid attentionSent state at end of ProcessAttention
   at Microsoft.Data.SqlClient.TdsParser.ProcessAttention(TdsParserStateObject stateObj) in C:\Source\GitHub\David-Engel\SqlClient\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\TdsParser.cs:line 7324
   at Microsoft.Data.SqlClient.TdsParser.ProcessPendingAck(TdsParserStateObject stateObj) in C:\Source\GitHub\David-Engel\SqlClient\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\TdsParser.cs:line 311
   at Microsoft.Data.SqlClient.TdsParserStateObject.ResetCancelAndProcessAttention() in C:\Source\GitHub\David-Engel\SqlClient\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\TdsParserStateObject.cs:line 745
   at Microsoft.Data.SqlClient.TdsParserStateObject.CloseSession() in C:\Source\GitHub\David-Engel\SqlClient\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\TdsParserStateObject.cs:line 721
   at Microsoft.Data.SqlClient.SqlCommand.PutStateObject() in C:\Source\GitHub\David-Engel\SqlClient\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\SqlCommand.cs:line 4702
   at Microsoft.Data.SqlClient.SqlCommand.ReliablePutStateObject() in C:\Source\GitHub\David-Engel\SqlClient\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\SqlCommand.cs:line 4692
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteReaderAsync(IAsyncResult asyncResult) in C:\Source\GitHub\David-Engel\SqlClient\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\SqlCommand.cs:line 1795
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   at System.Threading.Tasks.TaskFactory`1.<>c__DisplayClass38_0`1.<FromAsyncImpl>b__0(IAsyncResult iar)
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<BeginExecuteReaderInternal>b__166_1(Task`1 task, Object state) in C:\Source\GitHub\David-Engel\SqlClient\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\SqlCommand.cs:line 1917
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by David-Engel** [comment]
A subsequent run of all tests in VS 2017 worked, so I'm not sure what the assertion failed error was about. It looks like this might just be an issue in VS 2019. (I'm running the latest update: 16.3.6)

**Comment by Wraith2** [comment]
I'm using 16.3.6 and it's been the same on previous versions of 2019 I've tried.

**Comment by David-Engel** [comment]
I filed an issue against Microsoft.xunit.netcore.extensions:  https://github.com/microsoft/msbuild/issues/4845

We'll see where it goes from here. I'd rather not have to refactor all the tests to no longer use ConditionalFact.

**Comment by cheenamalhotra** [comment]
Closing as issue is now fixed.
