### ISSUE TITLE
Raising error 50000 throws an exception when attempting to catch specifically

### ISSUE THREAD

**Issue by landymore** [dotnet/SqlClient#2866]
### Describe the bug
Microsoft.Data.SqlClient does not seem to like the default error number of 50000 when it is raised by a T-SQL statement, and it throws an exception.

```
Exception message: Error number 50000 is invalid. The number must be from 13000 through 2147483647 and it cannot be 50000.
Stack trace:
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Error number 50000 is invalid. The number must be from 13000 through 2147483647 and it cannot be 50000.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, SqlCommand command, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()

```

### To reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
string sql = "[MySchema].[MyProcName]";

try
{
    using (var sqCon = new SqlConnection(_connectionString))
    {
        DateTime transactionBegin = DateTime.UtcNow;

        sqCon.Open();
        using (var sqCmd = sqCon.CreateCommand())
        {
            sqCmd.CommandType = CommandType.StoredProcedure;
            sqCmd.CommandText = sql;

            sqCmd.Parameters.AddWithValue("@SomeParameter", someId);

            sqCmd.ExecuteNonQuery();
        }

        sqCon.Close();

        DateTime transactionEnd = DateTime.UtcNow;
        TimeSpan tran = transactionEnd - transactionBegin;

        _log.Debug($"{{\"result\": \"success\", \"elapsed\": \"{Math.Round(tran.TotalMilliseconds, 2)}\", \"data\": \"{someId}\"}}");
    }    
}
catch (SqlException sqx) when (sqx.Number == 50000)
{
    _log.Warn($"The Specific thing we were looking for happened so we raised error 50000 in the proc: {sqx.Number} {sqx.Message}");
    throw new CustomExceptionForThisCondition(task);
}
catch (Exception ex)
{
    throw new Exception($"Something unexpected went wrong for {someId}", ex);
}
```

In [MySchema].[MyProcName]

```sql
-- detect some condition and decide you wish to raise an error back to the caller:
IF @IsSomethingBad = 1
BEGIN
		RAISERROR(50000, 16,1);
END;
```

### Expected behavior
When RAISEERR is called and raises the default error number, a SQLException should be thrown with the correct error number noted so that it can be caught and handled as intended.

### Further technical details
Microsoft.Data.SqlClient version: 5.2.0
.NET target: Net 8
SQL Server version: Azure SQL
Operating system: Windows 2019

**Additional context**
It seems like this is something the SqlClient library is intentionally looking for and having a problem with, due to the specificity of the exception message, in an attempt to force us to specify an error code other than 50000 which is the default. We should be consistent across the offerings by supporting the ability handle errors with the default error number https://learn.microsoft.com/en-us/sql/t-sql/language-elements/raiserror-transact-sql?view=sql-server-ver16#msg_id and not imposing a requirement in dotnet which does not exist in SQL itself.

**Comment by landymore** [comment]
After doing a small test which I should have done prior to submitting this bug, I can see this error is coming from the database and not SqlClient. Closing.
