### ISSUE TITLE
Unable to load DLL 'sni.dll' in SqlTableDependency

### ISSUE THREAD

**Issue by Rahulx1710** [dotnet/SqlClient#3038]
### Describe the bug
When attempting to initialize a SqlTableDependency instance, the application crashes with the following exception:

```
Unhandled exception. System.DllNotFoundException: Unable to load DLL 'sni.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at System.Data.SqlClient.SNINativeMethodWrapper.UnmanagedIsTokenRestricted(IntPtr token, Boolean& isRestricted)
   at System.Data.Win32NativeMethods.IsTokenRestrictedWrapper(IntPtr token)
   at System.Data.ProviderBase.DbConnectionPoolIdentity.GetCurrent()
```
This issue occurs when initializing the following code:
```
_tableDependency = new SqlTableDependency<Employee>(connectionString, tableName: "Employees");
```

### To reproduce
1.Add the following packages to your project:
Microsoft.Data.SqlClient (v5.2.2)
SqlTableDependency (v8.5.8)
TableDependency.SqlClient (v1.0.0).

2.Use this program.cs snippet:
```c#
builder.Services.AddSingleton<EmployeeTableDependency>(sp =>
{
    var connectionString = builder.Configuration.GetConnectionString("DefaultConnection");
    var hubContext = sp.GetRequiredService<IHubContext<SignalRHub>>();
    return new EmployeeTableDependency(connectionString, hubContext);
});
```
3.Add the following code in EmployeeTableDependency.cs:
```c#
public class EmployeeTableDependency : IDisposable
{
    private readonly SqlTableDependency<Employee> _tableDependency;
    private readonly IHubContext<SignalRHub> _hubContext;

    public EmployeeTableDependency(string connectionString, IHubContext<SignalRHub> hubContext)
    {
        // Initialize table dependency and SignalR hub context
        _tableDependency = new SqlTableDependency<Employee>(connectionString, tableName: "Employees");
        _hubContext = hubContext;

        // Subscribe to table change events
        //_tableDependency.OnChanged += TableDependency_OnChanged;
       // _tableDependency.OnError += TableDependency_OnError;

        // Start the table dependency listener
        _tableDependency.Start();
    }

    public void Dispose()
    {
        _tableDependency?.Dispose();
    }
}
```

### Expected behavior
The SqlTableDependency instance should initialize and listen to database changes without errors.

### Further technical details
packages
```c#
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.6" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.6">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.6" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.6">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="SqlTableDependency" Version="8.5.8" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="7.0.0" />
		<PackageReference Include="TableDependency.SqlClient" Version="1.0.0" />
	</ItemGroup>
</Project>
```
Target Framework: .NET 8.0
SQL Server Version: SQL Server 2019
Operating System: Windows 11

**Additional context**
Attempted to reinstall all packages, including Microsoft.Data.SqlClient and SqlTableDependency.
This issue blocks the use of SqlTableDependency for listening to database changes.

**Comment by cheenamalhotra** [comment]
SqlDependency is not maintained here. Please contact its owners for support and compatibility with Microsoft.Data.SqlClient.
