### ISSUE TITLE
EF Core 3.1 SQLClient issue on UWP ARM

### ISSUE THREAD

**Issue by GRS-Leedo** [dotnet/SqlClient#351]
I have a UWP app that used EF Core 2.2.6 successfully on x86, x64 and ARM.
After upgrading to EF Core 3.1, the app still runs successfully on x86 and x64 but on ARM fails with several exceptions:
The first is
Exception thrown: 'System.DllNotFoundException' in Microsoft.Data.SqlClient.dll
followed by
Exception thrown: 'System.TypeInitializationException' in Microsoft.Data.SqlClient.dll
Exception thrown: 'System.TypeInitializationException' in Microsoft.Data.SqlClient.dll
Exception thrown: 'System.TypeInitializationException' in Microsoft.Data.SqlClient.dll
Exception thrown: 'System.TypeInitializationException' in Microsoft.Data.SqlClient.dll
Exception thrown: 'System.TypeInitializationException' in Microsoft.Data.SqlClient.dll
Exception thrown: 'System.TypeInitializationException' in Microsoft.Data.SqlClient.dll
Exception thrown: 'System.TypeInitializationException' in Microsoft.Data.SqlClient.dll
Exception thrown: 'System.TypeInitializationException' in Microsoft.EntityFrameworkCore.Relational.dll
Exception thrown: 'System.TypeInitializationException' in Microsoft.EntityFrameworkCore.Relational.dll
Exception thrown: 'System.Reflection.TargetInvocationException' in System.Private.CoreLib.dll
Exception thrown: 'System.Reflection.TargetInvocationException' in LoadingDockDisplay.exe
Is there an issue with EF Core 3.1 on ARM?
Any ideas on the cause and how to fix this?

The error handler doesn't provide much detail...
Inner Exception

  | Name | Value | Type
-- | -- | -- | --
▶ | InnerException | {"The type initializer for 'Microsoft.Data.SqlClient.SNILoadHandle' threw an exception."} | System.Exception {System.TypeInitializationException}

Exception Message:
The type initializer for 'Microsoft.Data.SqlClient.TdsParser' threw an exception.
Source
Microsoft.Data.SqlClient
Stack Trace
   at Microsoft.Data.SqlClient.TdsParser..ctor(Boolean MARS, Boolean fAsynchronous)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at Microsoft.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
   at NetCoreCustomConfiguration.EFConfigProvider.Load() in C:\Users\gswanson\source\Workspaces\NetCoreCustomConfiguration\NetCoreCustomConfiguration\EFConfigProvider.cs:line 38
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at LoadingDockDisplay.MainPage..ctor() in C:\Users\gswanson\source\repos\LoadingDockDisplay\LoadingDockDisplay\MainPage.xaml.cs:line 69

Inner Exception of Inner Exception

  | Name | Value | Type
-- | -- | -- | --
▶ | InnerException | {"Unable to load DLL 'sni.dll' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)"} | System.Exception {System.DllNotFoundException}

Message
The type initializer for 'Microsoft.Data.SqlClient.SNILoadHandle' threw an exception.
Source
Microsoft.Data.SqlClient
Stack Trace
   at Microsoft.Data.SqlClient.TdsParserStateObjectFactory.get_EncryptionOptions()
   at Microsoft.Data.SqlClient.TdsParser..cctor()

The exception occurs on this line of code
`App SelectedApp = _context.Tbl_Apps.Where(a => a.AppDotName == AppDotName).FirstOrDefault();`
### Expected behavior
I would expect to get back an app object.  This works on x86 and x64, but not on ARM.  T

### Further technical details
Microsoft.Data.SqlClient version: 1.0.19269.1
.NET target: (Core 2.2.6 EF Core 3.1
SQL Server version: (e.g. SQL Server 2017)
Operating system: Win10 x86 and x64 OK, Windows IOT ARM Fails

**Additional context**

**Comment by cheenamalhotra** [comment]
Hi @GRS-Leedo 

Could you also provide version of UAP in your UWP app?

**Comment by GRS-Leedo** [comment]
Sorry for the slow response.  The UAP version is UAP,Version=10.0.17763.0

**Comment by cheenamalhotra** [comment]
Hi @GRS-Leedo 

Your version of UAP seems higher than 10.0.16299 that's compatible with .NET Standard 2.0. I would hope .NET Standard runtime dlls shipped with Microsoft.Data.SqlClient to be loaded seamlessly.

Please check this article "[UWP & .NET Standard 2.0](https://devblogs.microsoft.com/dotnet/uwp-net-standard-2-0-preview/)", that says:

> In order to use .NET Standard 2.0 in UWP, you need to target Fall Creators Update (FCU) as the minimum version of your UWP project.

To demonstrate the same, I created a sample project that uses **Microsoft.Data.SqlClient** in a **UWP** App, which I would request you to test and confirm it works in your case too.

[UWPExample.zip](https://github.com/dotnet/SqlClient/files/3970576/UWPExample.zip)

**Comment by GRS-Leedo** [comment]
Changing the targeted version of Windows 10 has had no effect.

The same errors exist
Exception thrown: 'System.DllNotFoundException' in Microsoft.Data.SqlClient.dll

Followed by
Exception thrown: 'System.TypeInitializationException' in Microsoft.Data.SqlClient.dll
Exception thrown: 'System.TypeInitializationException' in Microsoft.Data.SqlClient.dll
Exception thrown: 'System.TypeInitializationException' in Microsoft.Data.SqlClient.dll
Exception thrown: 'System.TypeInitializationException' in Microsoft.Data.SqlClient.dll
Exception thrown: 'System.TypeInitializationException' in Microsoft.Data.SqlClient.dll
Exception thrown: 'System.TypeInitializationException' in Microsoft.Data.SqlClient.dll
Exception thrown: 'System.TypeInitializationException' in Microsoft.Data.SqlClient.dll
Exception thrown: 'System.TypeInitializationException' in Microsoft.EntityFrameworkCore.Relational.dll
Exception thrown: 'System.TypeInitializationException' in Microsoft.EntityFrameworkCore.Relational.dll
'LoadingDockDisplay.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Programs\WindowsApps\Microsoft.NET.CoreFramework.Debug.2.2_2.2.27909.0_arm__8wekyb3d8bbwe\System.Diagnostics.Tools.dll'. Symbol loading disabled by Include/Exclude setting.
Exception thrown: 'System.TypeInitializationException' in LoadingDockDisplay.exe

According to this article, https://docs.microsoft.com/en-us/windows/uwp/updates-and-versions/choose-a-uwp-version

"When creating a UWP app in Microsoft Visual Studio, you can choose which version to target. Projects using .NET Standard 2.0 must have a Minimum Version of Build 16299 or later."

It does not seem that the Targeted version must be 16299, just a minimum of 16299.

In addition, the code works when compiled to x86 or x64, just not ARM.

As far as your example, it doesn't seem to do anything.  Here is a screen shot


![2019-12-16_17h38_28](https://user-images.githubusercontent.com/47821931/70952140-02bf5e80-202b-11ea-82f6-868726c35c41.png)

I don't mean to be unhelpful, but I do not have time to dig into your example to figure out what is going on.  No errors are reported.  In fact, the Output Window is VS is blank.

**Comment by cheenamalhotra** [comment]
I'm gonna try out with ARM too.. the app just connects to Target SQL Server and reports output in text.

I'll check back and confirm

**Comment by GRS-Leedo** [comment]
It looks like this was an issue from April 2016 until September 2017 when someone solved it by loading another NuGet package.  It also seems to have been an issue in 2018 as well.

**Comment by GRS-Leedo** [comment]
This seems to be at the heart of the problem  It is the inner most exception and seems to come up with each major release.

◢ | InnerException | {"Unable to load DLL 'sni.dll' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)"} | System.Exception {System.DllNotFoundException}

This is the stack trace
   at Microsoft.Data.SqlClient.SNINativeMethodWrapper.SNIInitialize(IntPtr pmo)
   at Microsoft.Data.SqlClient.SNILoadHandle..ctor()
   at Microsoft.Data.SqlClient.SNILoadHandle..cctor()

I tried adding the SNI nuget package, but it did not help.  The version of the SNI DLL was 4.4 when the current seems to be 4.7.  Also, the current version of SqlClient seems to be 4.8, but EF Core 3.1 uses 4.7.  I don't know if any of this is part of the problem.

**Comment by GRS-Leedo** [comment]
Is there any update on this?

**Comment by cheenamalhotra** [comment]
Hi @GRS-Leedo 

The problem is only related to Microsoft.Data.SqlClient since that's referenced by EF Core 3.1. I'm leaning towards the fact that we don't ship a specific DLL for UAP in Microsoft.Data.SqlClient NuGet (targeting `uap10.0.16299`) like System.Data.SqlClient does, and that may be the cause of the problem.

It's possible that ARM applications are referencing .NET Standard 2.0 DLL (Built for AnyCPU) as fallback which is trying to load SNI.dll for x86 (read it [here](http://blogs.microsoft.co.il/sasha/2012/04/04/what-anycpu-really-means-as-of-net-45-and-visual-studio-11/): "_If the process runs on an ARM Windows system, it runs as a 32-bit process. IL is compiled to ARM machine code._").

So it looks like it cannot load the x86 DLL it's referencing which is not compatible with ARM platform.

I'm trying to compile UAP targeting DLL which can reference the correct SNI.dll (for ARM platform) in this case.

Let me know if you have any other thoughts.

**Comment by GRS-Leedo** [comment]
Hi Cheena,
Have you had any success with this issue?  I really want to get off of EF Core 2.2.6 because of the issues that it has with UWP across all CPU's.  3.1 solves them on x86 and x64 but I have some ARM apps that need the same help.

Thanks.

**Comment by cheenamalhotra** [comment]
Hi @GRS-Leedo 

I'm waiting for @saurabh500 to be back from vacation to discuss this issue in depth and understand how they built UAP library for System.Data.SqlClient. I tried for Microsoft.Data.SqlClient but doesn't seem very straightforward to me.

**Comment by cheenamalhotra** [comment]
@Wraith2 

Since you mentioned in issue #375 :

> The current library uses native mode on win32 windows and managed mode in any other environment (including UAP on windows).

It doesn't seem the case with Microsoft.Data.SqlClient, refer to this [issue](https://github.com/dotnet/SqlClient/issues/351#issue-537280114) where SNI.dll is loaded for UAP apps. I've also heard samilar response from @saurabh500 once but didn't get a chance to discuss in detail. Are you referencing to the same or there's a difference in behaviors between System.Data.SqlClient and Microsoft.Data.SqlClient in this regard?

Because, since we do not ship `uap` targeted DLL with Microsoft.Data.SqlClient, could that be the reason the .NET Standard DLL referenced by UAP applications does not use Managed SNI and still loads SNI.dll same way as .NET Core? I'm trying to connect the dots if that's the reason this issue is occurring wherein it shouldn't be looking for SNI.dll in UAP apps at the first place?

**Comment by Wraith2** [comment]
As always the code is the current truth and I know that the loading of sni.dll was changed when the library moved out of the corefx repo so my information may be out of date. 

Historically uap used the managed version as far as I remember because you weren't allowed to load non approved native dlls sincethey couldn't be verified as being safe so uap used the managed implementation.

**Comment by GRS-Leedo** [comment]
@cheenamalhotra 
Is there any update on this?  It is really starting to cause delays in my project deployment.  Is there a work around until this can be sorted out?

Thanks

**Comment by GRS-Leedo** [comment]
Is there somewhere that I can get the SNI.DLL for ARM so that I can include it directly?

**Comment by cheenamalhotra** [comment]
Hi @GRS-Leedo 

I've been trying to build uap DLL but the change in build architecture here as compared to that of System.Data.SqlClient in CoreFx (now dotnet/runtime) is not making it possible to build for uap the way it was done before.

> Is there somewhere that I can get the SNI.DLL for ARM so that I can include it directly?

Yes, you can include reference to arm-x64 sni.dll from referenced by the below package by making a direct reference: https://www.nuget.org/packages/runtime.native.System.Data.SqlClient.sni/ in the meantime, while we look for alternate solutions.

**Comment by GRS-Leedo** [comment]
I have added the package via NuGet.  Where does the reference go?

**Comment by cheenamalhotra** [comment]
It should download DLL from https://www.nuget.org/packages/runtime.win-arm64.runtime.native.System.Data.SqlClient.sni/ NuGet package which is targeted for Win ARM x64 platform.

**Comment by GRS-Leedo** [comment]
The project is targeted to ARM not ARM64.  I used NuGet package manager to download runtime.native.System.Data.SqlClient.sni but that made no difference.
![2020-01-29_17h44_18](https://user-images.githubusercontent.com/47821931/73407578-31358800-42bf-11ea-9a86-75e0a1519e05.png)

**Comment by Wraith2** [comment]
@cheenamalhotra if we enable the appcontext switch for managed sni in release builds it could be used in this case. Managed reliability is much better now than it was when the switch was disabled.

**Comment by cheenamalhotra** [comment]
@GRS-Leedo 

Could you try referencing the SNI.DLL directly in your csproj from the child (arm-x64) NuGet package?  

@Wraith2 

Yes, I'm on my way to that PR soon. That will enable us to test Managed SNI more rigorously on Windows as part of CI in different setups in order to measure and improve reliability factor.

**Comment by cheenamalhotra** [comment]
@GRS-Leedo 

We recently introduced support for ARM platform on Windows with [v2.0.0-preview4](https://www.nuget.org/packages/Microsoft.Data.SqlClient/2.0.0-preview4.20142.4).
Could you give that a try and let us know if addresses your issues?
