### ISSUE TITLE
PlatformNotSupportedException when loading System.Data.SqlClient in fsx file

### ISSUE THREAD

**Issue by fuchen** [dotnet/SqlClient#363]
test.fsx:
```
#load "..\\.paket\\load\\netstandard2.1\\System.Data.SqlClient.fsx" 

open System.Data.SqlClient
open System.IO

[<Literal>]
let connStr = @"Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=rzcloud-db;Integrated Security=True"

let runSqlFile (connection: SqlConnection) filename =
    printfn "-> %s" filename
    let script = File.ReadAllText(filename)
    use command = new SqlCommand(script, connection)
    command.ExecuteNonQuery() |> ignore

runSqlFile ("test.sql")
```
System.Data.SqlClient.fsx is generated by paket, and its content is:
```
namespace PaketLoadScripts

#load "D:\\work\\.paket\\load\\netstandard2.0\\Microsoft.Win32.Registry.fsx" 
#load "D:\\work\\.paket\\load\\netstandard2.0\\System.Buffers.fsx" 
#load "D:\\work\\.paket\\load\\netstandard2.0\\System.Diagnostics.DiagnosticSource.fsx" 
#load "D:\\work\\.paket\\load\\netstandard2.0\\System.Memory.fsx" 
#load "D:\\work\\.paket\\load\\netstandard2.0\\System.Security.Principal.Windows.fsx" 
#load "D:\\work\\.paket\\load\\netstandard2.0\\System.Text.Encoding.CodePages.fsx" 
#r "C:\\Users\\me\\.nuget\\packages\\system.data.sqlclient\\4.8.0\\lib\\netstandard2.0\\System.Data.SqlClient.dll" 
```

run `dotnet fsi test.fsx`, get below exception message:
```
System.PlatformNotSupportedException: System.Data.SqlClient is not supported on this platform.
   at System.Data.SqlClient.SqlConnection..ctor(String connectionString)
   at FSI_0002.runAll()
   at <StartupCode$FSI_0002>.$FSI_0002.main@()
```

**Comment by cheenamalhotra** [comment]
Hi @fuchen 

It seems like the path of **System.Data.SqlClient.dll** referenced in `System.Data.SqlClient.fsx` is not correct, the correct DLL to use is:

`#r "C:\\Users\\me\\.nuget\\packages\\system.data.sqlclient\\4.8.0\\runtimes\\win\\lib\\netstandard2.0\\System.Data.SqlClient.dll"`

Can you try to modify the path in fsx file and try again?

**Comment by fuchen** [comment]
@cheenamalhotra I modified the path and it works now. So is it a bug of paket?
