### ISSUE TITLE
core3.1 + system.data.sqlclient4.8   System.Data.SqlClient.SqlException  problem

### ISSUE THREAD

**Issue by gaojiandonggg** [dotnet/SqlClient#388]
.net core 3.1
system.data.sqlclient 4.8
dapper 2.0.3
linux+k8s+docker

Pooling=true; Max Pool Size = 512; Min Pool Size = 5; The Connection Timeout = 120;

At the same time, 300 requests come in, query a single table of data, the database connection can be created, and error will be reported in a moment, only when the instance is started for the first time, I am using k8s to start the container instance, is it related to this, the error information is as follows:

Input:; Message:A transport-level error has occurred when receiving results from the server. A transport-level error occurred when receiving results from the server. (provider: TCP provider, error: 35 - An internal exception was caught) || Unable to read data from the transport connection: reset by peer

 at Dapper.SqlMapper.ThrowDataException(Exception ex, Int32 index, IDataReader reader, Object value) in C:\projects\dapper\Dapper\SqlMapper.cs:line 3633
   at Deserialize27fb26cc-e5f4-485a-be83-8e735ff75836(IDataReader )
   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command)
   at Open.SchoolBase.SqlServerProvider.SqlServerProvider.<>c__DisplayClass33_0`1.<<GetListByQueryAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at XXXXX.SqlServerProvider.SqlServerProvider.Execute[R](Func`3 func)
   at XXXXX.SqlServerProvider.SqlServerProvider.GetListByQueryAsync[T](Expression`1 condition, String orderBy, Boolean isDesc)
   at XXXXX.Core.DataAccess.BaseRepository.GetListByQueryAsync[T](Expression`1 condition, String orderBy, Boolean isDesc)
   at XXXXX.Core.DataAccess.BaseRepository.GetListByQueryAsync[T](Expression`1 condition)
   at XXXXX.BasicLogic.SCHB_Common_Logic.GetListByQueryAsync[T](Expression`1 condition)
   at BasicManagement.Controllers.ActivityTemplateController.GetTemplateList()
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) ||    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParserStateObject.ThrowExceptionAndWarning(Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParserStateObject.ReadSniError(TdsParserStateObject stateObj, UInt32 error)
   at System.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync()
   at System.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()
   at System.Data.SqlClient.TdsParserStateObject.TryPrepareBuffer()
   at System.Data.SqlClient.TdsParserStateObject.TryReadByteArray(Span`1 buff, Int32 len, Int32& totalRead)
   at System.Data.SqlClient.TdsParserStateObject.TryReadStringWithEncoding(Int32 length, Encoding encoding, Boolean isPlp, String& value)
   at System.Data.SqlClient.TdsParser.TryReadSqlStringValue(SqlBuffer value, Byte type, Int32 length, Encoding encoding, Boolean isPlp, TdsParserStateObject stateObj)
   at System.Data.SqlClient.TdsParser.TryReadSqlValue(SqlBuffer value, SqlMetaDataPriv md, Int32 length, TdsParserStateObject stateObj)
   at System.Data.SqlClient.SqlDataReader.TryReadColumnInternal(Int32 i, Boolean readHeaderOnly)
   at System.Data.SqlClient.SqlDataReader.GetValueInternal(Int32 i)
   at System.Data.SqlClient.SqlDataReader.GetValue(Int32 i)
   at Deserialize27fb26cc-e5f4-485a-be83-8e735ff75836(IDataReader ) ||    at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Data.SqlClient.SNI.SNITCPHandle.Receive(SNIPacket& packet, Int32 timeoutInMilliseconds) ||    at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)

**Comment by cheenamalhotra** [comment]
Hi @gaojiandonggg 

Can you reproduce this issue independent of Dapper? If yes, please provide a standalone repro with SqlClient only in order to reproduce the issue so we can investigate.

**Comment by cheenamalhotra** [comment]
Hi @gaojiandonggg 

Did you manage to get the issue reproduced independent of Dapper?

**Comment by cheenamalhotra** [comment]
Closing as inactive
