### ISSUE TITLE
EF Core SaveChanges | The connection is broken and recovery is not possible

### ISSUE THREAD

**Issue by p1p3** [dotnet/SqlClient#400]
Hi, 
 
 Currently we are developing an application using the following stack : 
  - **aspnet core** : 3.1
  - **efcore** :  3.1 
  - **docker** : aspnet:3.1-nanoserver-1809.
  - **docker-desktop** : 2.1.0.5
  - **Microsoft SQL Server Developer (64-bit)**: 14.0.1000.169

Recently we faced a new scenario when we needed to store into the database a large amount of data within only one context saveChanges operation ( it could take more than 3 minutes to execute).

In most of the machines it works completely fine but there are two machines were the following error is thrown every time we try to execute that kind of operations:

`[Microsoft.EntityFrameworkCore.Update] An exception occurred in the database while saving changes for context type '"Y.Z.Infrastructure.SpecificDbContext"'."
 ""Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. 
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): The connection is broken and recovery is not possible. The connection is marked by the server as unrecoverable. No attempt was made to restore the connection. 
 at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action1 wrapCloseInAction)
 at Microsoft.Data.SqlClient.SqlConnection.ValidateAndReconnect(Action beforeDisconnect, Int32 timeout)
 at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
 at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
 at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method) at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
 at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior) at System.Data.Common.DbCommand.ExecuteReader()
 at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
 at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
 ClientConnectionId:f9fecebf-15ae-4dd0-984e-dbc5a1d5b131 
 — End of inner exception stack trace — 
 at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
 at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable1 commandBatches, IRelationalConnection connection)
 at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList1 entries)
 at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList1 entriesToSave)
 at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
 at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation[TState,TResult](Func3 operation, Func3 verifySucceeded, TState state)
 at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.Execute[TState,TResult](TState state, Func3 operation, Func3 verifySucceeded)
 at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
 at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
 " Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): The connection is broken and recovery is not possible. The connection is marked by the server as unrecoverable. No attempt was made to restore the connection.
 at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action1 wrapCloseInAction)
 at Microsoft.Data.SqlClient.SqlConnection.ValidateAndReconnect(Action beforeDisconnect, Int32 timeout)
 at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
 at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
 at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
 at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
 at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
 at System.Data.Common.DbCommand.ExecuteReader() at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
 at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection) ClientConnectionId:f9fecebf-15ae-4dd0-984e-dbc5a1d5b131 
 — End of inner exception stack trace — 
 at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
 at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable1 commandBatches, IRelationalConnection connection)
 at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList1 entries)
 at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList1 entriesToSave)
 at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
 at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation[TState,TResult](Func3 operation, Func3 verifySucceeded, TState state)
 at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.Execute[TState,TResult](TState state, Func3 operation, Func3 verifySucceeded)
 at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
 at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess) Zervice_1  `

We performed  some tests to identify where the problem is coming from (Database/Application) but sadly it only happens when the database and the application are hosted in the same machine that has the problems, 
 
 Meaning that :
  - if an application hosted in a different server is pointing any of those SQL server instances, it will result in a successful operation.
  - If the application is hosted in any of the machines that has the problem and pointing to an external database, it will result in a successful operation. 
 
 So far we have changed the value of the Auto-growth properties but the error still persist, We are running out of ideas and our last resource is to ask here if anyone has any clue of where the problem could be.

 There are two issues currently open that contains the same error however I cannot identify if they are really related
#64 
#78 

 We will be more than happy to provide any further information.

**Comment by cheenamalhotra** [comment]
@p1p3 

Looking at the logs it looks like the connection is not recovered properly when reading result from "ExecuteReader", as attempted with "ValidateAndReconnect". This is possibly a failed case of Connection Resiliency, which is currently not fully supported on Unix clients.

**Comment by p1p3** [comment]
@cheenamalhotra 

Thanks for the prompt response

Two things that I find interesting is that I can reproduce it 100% of the times in these specific machines and configuration (So  I hardly think it is an intermittent connection problem) plus the containers/images we are using are windows based.

**Comment by cheenamalhotra** [comment]
@p1p3 

Is it possible to create a simple app for your scenario and that you can provide in a zip to help reproduce the issue and understand the environment setup.. also I'd like to know more about the machine that has problems, and are you connecting from Docker image to SQL Server hosted on the same host?

**Comment by p1p3** [comment]
@cheenamalhotra 

-Today I will try to create a simple app in where I can reproduce the issue in the machine that has problems.

- What kind of data do you want from the machine that has problems? 

- We are connecting from a Docker image to a SQL server hosted on the same host, however is worth to mention that SQL instance is not running under docker.

**Comment by p1p3** [comment]
@cheenamalhotra 

Today we managed to reproduce the issue in all the machines, we found there was a close relation between the amount of memory available in the host at the moment of calling SaveChanges for a large amount of data and the error we are experiencing. However, we only managed to get this error while running  the solution under windows containers.

![image](https://user-images.githubusercontent.com/10712317/73450359-862bd980-4365-11ea-9430-98e985fd3639.png)


Here is also a simple project which you can use to reproduce the behavior: 
[SqlClientException.zip](https://github.com/dotnet/SqlClient/files/4133995/SqlClientException.zip)

**Comment by JRahnama** [comment]
@p1p3 is this still an issue? Have you tested with latest release of the driver?

**Comment by JRahnama** [comment]
Closing the issue due to inactivity. Feel free to reopen or create a new issue if this is still a problem.
