### ISSUE TITLE
System.Data.SqlClient throws "System.InvalidOperationException : Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool. "

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/SqlClient#413]
In ASP.NET Core tests, we started getting persistent errors in our tests that use SQL Server Local DB 2016, .NET Core 3, and System.Data.SqlClient.

```
Error Message:
 System.InvalidOperationException : Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.
Stack Trace:
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
```

This error seemed to only affect Windows 7 and Windows 8.1.
https://mc.dot.net/#/user/aspnetcore/pr~2Faspnet~2Faspnetcore/ci/20190522.38/workItem/Microsoft.AspNetCore.Identity.EntityFrameworkCore.Test~2Fnetcoreapp3.0

This error was encountered as a result of a dependency-flow PR into AspNetCore https://github.com/aspnet/AspNetCore/pull/10434. This PR attempted to move System.Data.SqlClient from 4.7.0-preview6.19264.9 to 4.7.0-preview6.19270.12, and included these changes: https://github.com/dotnet/corefx/compare/a28176b5ec68b6da1472934fe9493790d1665cae...ef1a5aa730098b6c3350977a991232c1ff11cfe3.

cc @ajcvickers @Pilchie

**Comment by cheenamalhotra** [comment]
@ajcvickers 

Does this issue need any investigations or can it be closed?

**Comment by cheenamalhotra** [comment]
Closing due to inactivity.
