### ISSUE TITLE
TypeInitializationException: Failed to load SNI.dll when using DeploymentItem

### ISSUE THREAD

**Issue by mvandegoor** [dotnet/SqlClient#452]
Failed to load SNI.dll when using DeploymentItem and running all tests in Visual Studio.

```
Exception message: System.TypeInitializationException: The type initializer for 'Microsoft.Data.SqlClient.SNINativeMethodWrapper' threw an exception. ---> System.ComponentModel.Win32Exception: Failed to load <path>\Out\x86\SNI.dll ---> System.ComponentModel.Win32Exception: The specified module could not be found
Stack trace:
Test Name:	ConnectorTest
Test Outcome:	Failed
Result StackTrace:	
at Microsoft.Data.SqlClient.SNINativeMethodWrapper..cctor()
--- End of inner exception stack trace ---
    at Microsoft.Data.SqlClient.SNINativeMethodWrapper.UnmanagedIsTokenRestricted(IntPtr token, Boolean& isRestricted)
   at Microsoft.Data.Win32NativeMethods.IsTokenRestrictedWrapper(IntPtr token)
   at Microsoft.Data.ProviderBase.DbConnectionPoolIdentity.GetCurrent()
   at Microsoft.Data.ProviderBase.DbConnectionPoolGroup.GetConnectionPool(DbConnectionFactory connectionFactory)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.GetConnectionPool(DbConnection owningObject, DbConnectionPoolGroup connectionPoolGroup)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at Microsoft.Data.SqlClient.SqlConnection.Open()
   at Library.Connector.Connect() in C:\Repos\SqlClientTransitive-DeploymentItem\Library\Connector.cs:line 11
   at Consumer.Program.Connect() in C:\Repos\SqlClientTransitive-DeploymentItem\Consumer\Program.cs:line 15
   at Consumer.UnitTest.ProgramTest.ConnectorTest() in C:\Repos\SqlClientTransitive-DeploymentItem\Consumer.UnitTest\ProgramTest.cs:line 12
Result Message:	
Test method Consumer.UnitTest.ProgramTest.ConnectorTest threw exception: 
System.TypeInitializationException: The type initializer for 'Microsoft.Data.SqlClient.SNINativeMethodWrapper' threw an exception. ---> System.ComponentModel.Win32Exception: Failed to load <path>\Out\x86\SNI.dll ---> System.ComponentModel.Win32Exception: The specified module could not be found
```

### To reproduce
1. Clone [repo with a repro scenario](https://github.com/mvandegoor/SqlClientTransitive/tree/repro/sni_load_failed_deploymentitem)
2. Choose Test => Run All Tests.

The test fails with the exception as shown above. The test succeeds if the line containing `DeploymentItem` is commented out.

### Further technical details
For the provided repo, the following is used:
- Microsoft.Data.SqlClient version: 1.1.0
- .NET target: .NET Framework 4.7.2
- NuGet 5.3
- Visual Studio 2019 16.4.2
- C++ Runtime:
  * Microsoft Visual C++ 2015-2019 Redistributable (x86) - 14.23.27820
  * Microsoft Visual C++ 2015-2019 Redistributable (x64) - 14.23.27820
- Operating System: Windows Server 2012 R2 Datacenter

In our intended solution, we use Microsoft.EntityFrameworkCore.SqlServer 3.1.1 instead of an explicit reference to Microsoft.Data.SqlClient.

**Comment by cheenamalhotra** [comment]
Hi @mvandegoor 

The issue seems to be due to below attribute on test method:

`[DeploymentItem("Deployables")]`

SNI.dll targets are currently not aware of this copy process and therefore do not perform any additional copy process. Removing this attribute works normally.

I'm investigating as to whether we can add support for [DeploymentItemAttribute](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.testtools.unittesting.deploymentitemattribute?view=mstest-net-1.2.0) or not since this is MSTest process. Will get back to you with further updates!

**Comment by JRahnama** [comment]
@mvandegoor is this still an issue? Have you tried with the latest version of the driver?

**Comment by mvandegoor** [comment]
@JRahnama : I don't know, I have not tried anymore. We chose a different solution back then, and I'm not working on that project anymore. Do you have difficulties reproducing the issue? As far as I'm concerned, you can close the issue if it fixed in the latest version.

**Comment by mvandegoor** [comment]
Or you can close it if you don't think it has use for other. I don't have a need for it anymore.

**Comment by lcheunglci** [comment]
Close due to inactivity.
