### ISSUE TITLE
NullReferenceException in SNITCPHandle.Send

### ISSUE THREAD

**Issue by domisterwoozy** [dotnet/SqlClient#49]
While attempting to write to a table using a table valued parameters with MARS on I am getting a `NullReferenceException` and the following stack trace.

```	
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Data.SqlClient.SNI.SNITCPHandle.Send(SNIPacket packet)
   at System.Data.SqlClient.SNI.SNIMarsConnection.Send(SNIPacket packet)
   at System.Data.SqlClient.SNI.SNIMarsHandle.SendControlPacket(SNISMUXFlags flags)
   at System.Data.SqlClient.SNI.SNIMarsHandle.Dispose()
   at System.Data.SqlClient.SNI.TdsParserStateObjectManaged.Dispose()
   at System.Data.SqlClient.TdsParserSessionPool.PutSession(TdsParserStateObject session)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQuery(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, 
```

I am on running dotnet-runtime-2.0.5-linux-x64.

**Comment by divega** [comment]
As recently [announced in the .NET Blog](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/), focus on new SqlClient features an improvements is moving to the new [Microsoft.Data.SqlClient package](https://www.nuget.org/packages/Microsoft.Data.SqlClient/). For this reason, we are moving this issue to the new repo at https://github.com/dotnet/SqlClient. We will still use https://github.com/dotnet/corefx to track issues on other providers like System.Data.Odbc and System.Data.OleDB, and general ADO.NET and .NET data access issues.

**Comment by Wraith2** [comment]
If you can provide a reproduction i can investigate and probably fix this issue. Without a reproduction all i have to rely on is guesswork and that isn't an effective or efficient use of time so we may as well close the issue.

**Comment by cheenamalhotra** [comment]
@domisterwoozy 

Please let us know if you're still facing this issue and provide more info on the use case, so we can reproduce at our end.

**Comment by johnsimons** [comment]
I am getting a very similar issue in netcoreapp 2.2 running on docker based on http://mcr.microsoft.com/dotnet/core/sdk:2.2 image
With https://www.nuget.org/packages/System.Data.SqlClient/4.7.0

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Data.SqlClient.SNI.SNIPacket.ReadFromStreamAsync(Stream stream, SNIAsyncCallback callback)
   at System.Data.SqlClient.SNI.SNITCPHandle.ReceiveAsync(SNIPacket& packet)
   at System.Data.SqlClient.SNI.SNIMarsConnection.ReceiveAsync(SNIPacket& packet)
   at System.Data.SqlClient.SNI.SNIMarsConnection.HandleReceiveComplete(SNIPacket packet, UInt32 sniErrorCode)
   at System.Data.SqlClient.SNI.SNIPacket.<ReadFromStreamAsync>g__ReadFromStreamAsync|27_0(SNIPacket packet, SNIAsyncCallback cb, ValueTask`1 valueTask)
```

I seem to be able to repro it quite easily, but that is running our application, it will be quite difficult to repro it in isolation.

**Comment by yukiwongky** [comment]
@johnsimons would be great if you can provide us with a repro script. Do you also encounter this error when trying to use TVP?

**Comment by johnsimons** [comment]
@yukiwongky, as I said, trying to create a small repro, is quite difficult for us. We have tried before but weren't able.
However, we can offer you a pod in our Kubernetes Cluster that we can repro this issue in?

**Comment by cheenamalhotra** [comment]
Closing this issue as no repro code is available and no new additional customers have reported this issue.
Would recommend testing with Microsoft.Data.SqlClient latest versions and open a new issue with repro application if reproduced.
