### ISSUE TITLE
System.TypeInitializationException: The type initializer for 'Microsoft.Data.SqlClient.SNINativeMethodWrapper' threw an exception.

### ISSUE THREAD

**Issue by docfresh** [dotnet/SqlClient#514]
I have a new WinForms project that I recently upgraded from System.Data.SqlClient to Microsoft.Data.SqlClient.  Everything looks fine but now ClickOnce publishing does not work. After installing and running the app from ClickOnce, the error appears:

System.TypeInitializationException: The type initializer for 'Microsoft.Data.SqlClient.SNINativeMethodWrapper' threw an exception. ---> System.ComponentModel.Win32Exception: Failed to load C:\Users\****\AppData\Local\Apps\2.0\L9RAAE32.69T\MHGY46EK.K6A\test..tion_6412cd1ba591f0ae_0001.0000_f22578eef1ecd8cb\x86\SNI.dll ---> System.ComponentModel.Win32Exception: The specified module could not be found
   --- End of inner exception stack trace ---
   at Microsoft.Data.SqlClient.SNINativeMethodWrapper..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Data.SqlClient.SNINativeMethodWrapper.UnmanagedIsTokenRestricted(IntPtr token, Boolean& isRestricted)
   at Microsoft.Data.Win32NativeMethods.IsTokenRestrictedWrapper(IntPtr token)
   at Microsoft.Data.ProviderBase.DbConnectionPoolIdentity.GetCurrent()
   at Microsoft.Data.ProviderBase.DbConnectionPoolGroup.GetConnectionPool(DbConnectionFactory connectionFactory)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.GetConnectionPool(DbConnection owningObject, DbConnectionPoolGroup connectionPoolGroup)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at Microsoft.Data.SqlClient.SqlConnection.Open()

Things I have tried: 
Update Nuget Packages (Microsoft.Data.SqlClient = 1.11 and Microsoft.Data.SqlClient.SNI = 1.11)
Change target configuration to x86 and republish 
Include SNI.dll in project and Copy to Output Directory

### Expected behavior
The app should install successfully from ClickOnce, and run successfully as it does from Visual Studio 2019.

### Further technical details
Visual Studio 2019 16.4.5
Microsoft.Data.SqlClient version: 1.11.20045.2 (Nuget)
.NET target: WinForms Framework 4.7.2, Core 3.1
SQL Server version: SQL Server 2016 SP2 13.0.5337.0 (X64)
Operating system: Windows 10 Pro 64bit

[stack_trace.txt](https://github.com/dotnet/SqlClient/files/4445742/stack_trace.txt)

**Comment by docfresh** [comment]
Possible duplicate of https://github.com/dotnet/SqlClient/issues/441
