### ISSUE TITLE
Microsoft.Data.SqlClient v2.0.0 error connecting to Azure SQL in Windows container app

### ISSUE THREAD

**Issue by alexxie** [dotnet/SqlClient#714]
Have upgraded our Windows container app to Microsoft.Data.SqlClient v2.0.0 and it is getting "The instance of SQL Server you attempted to connect to requires encryption but this machine does not support it." when connecting to Azure SQL database. The application works with v1.1.3. 

Can you please advise what needs to be changed for v2.0.0?

**Comment by cheenamalhotra** [comment]
Hi @alexxie 

Starting with v2.0.0, the driver now performs certificate validation if encryption is required/enforced by server.
You could either install server's SSL certificate on client machine or override certificate validation with connection property:
"Trust Server Certificate=true"

Microsoft.Data.SqlClient now works as other Client drivers as documented here: https://docs.microsoft.com/en-us/sql/relational-databases/native-client/features/using-encryption-without-validation?view=sql-server-ver15

**Comment by alexxie** [comment]
Hi Cheena,

I have tried using different combination of the Encrypt and Trust Server Certificate attributes in the connection string: Server=tcp:xxx.database.windows.net,1433;Persist Security Info=False;User ID=xxx;Password=xxx;MultipleActiveResultSets=False;Encrypt=True;Trust Server Certificate=true;Connection Timeout=30; but still getting the same error. The same connection string works in Linux container and IIS Express. The error only happens when the app runs in Windows container. Any idea?

Below is the stack trace:

Microsoft.Data.SqlClient.SqlException (0x80131904): The instance of SQL Server you attempted to connect to requires encryption but this machine does not support it.
at Microsoft.Data.ProviderBase.DbConnectionPool.CheckPoolBlockingPeriod(Exception e)
at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
at Microsoft.Data.SqlClient.SqlConnection.Open()
at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.<>c__DisplayClass18_0.<Exists>b__0(DateTime giveUp)
at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__DisplayClass12_0`2.<Execute>b__0(DbContext c, TState s)
at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation[TState,TResult](Func`3 operation, Func`3 verifySucceeded, TState state)
ClientConnectionId:f7fd8c91-2d02-44da-b106-1009eb2dc8a6
Error Number:20,State:0,Class:20


Thanks and regards,
Alex

**Comment by cheenamalhotra** [comment]
@alexxie 

You're probably hitting this issue then: https://github.com/dotnet/SqlClient/issues/653#issuecomment-661399108

**Comment by alexxie** [comment]
You are right, the error is caused by the missing security.dll. Is there plan to fix this issue?

**Comment by cheenamalhotra** [comment]
@alexxie 

The missing security.dll is Windows System DLL - it's external to the driver, hence we cannot do anything about it. You may reach out to Windows Nano Server teams to get that resolved in Windows containers.

From driver's perspective, we offer alternative solution to enable Managed networking on Windows, such that Native DLLs are not referenced in such environments.

I will close this issue as **External**.

**Comment by alexxie** [comment]
Hi Cheena,

According to documentation, enable managed networking on Windows is “intended for testing and debugging purposes only”. Is there any downside for production? Does v1.1.3 use this feature by default as it works in Windows Containers.

Thanks and regards,
Alex

**Comment by cheenamalhotra** [comment]
Hi @alexxie 

> According to documentation, enable managed networking on Windows is “intended for testing and debugging purposes only”. Is there any downside for production?

Yes it's not recommended for production use yet.

> Does v1.1.3 use this feature by default as it works in Windows Containers.

No, it does not.
If 1.1.3 version works, then I believe we'll have to re-investigate if this is related to recent changes.

**Comment by cheenamalhotra** [comment]
Hi @alexxie 

To answer why 1.1.3 works and 2.0.0 not in Windows containers:

> Does v1.1.3 use this feature by default as it works in Windows Containers.

1.1.3 works because the driver doesn't validate server certificate if server enforced encryption and client did not request it.
So the behavior is as expected. The missing security.dll stays external issue in Windows containers which is referenced now by the driver for secure connection.

**Comment by mstfgueclue** [comment]
@cheenamalhotra could you maybe help me in this issue :/ 

My ticket has been linked from ef core here: 
#https://github.com/dotnet/efcore/issues/24185
