### ISSUE TITLE
Exception: There is already an open DataReader associated with this Command which must be closed first

### ISSUE THREAD

**Issue by BenoitStutz** [dotnet/SqlClient#807]
.Net Version 4.6.1
Microsoft.Data.SqlClient 2.01
linq2db 3.1.6

**With Oracle:**
	no Problem
**With SQL-Server:**
	Exception: There is already an open DataReader associated with this Command which must be closed first.

using (DbContext dbContext = new DbContext(dbProvider))
{
  IEnumerable\<string\> list = dbContext.MENUS_LOG.Select(obj => obj.DATATYPE).Distinct();
  foreach(string strItem in list)
  {
    dbContext.MENUS_LOG.Where(objWhere => objWhere.DATATYPE == strItem)
      .Update(dbContext.MENUS_LOG, objWhere => new MENUS_LOG
      {
        DATATYPE = strItem + "X"
      }); 
  }
}

**DataProvider**:
  Oracle:
  m_IDataProvider = new LinqToDB.DataProvider.Oracle.OracleDataProvider(ProviderName.OracleManaged,
                              LinqToDB.DataProvider.Oracle.OracleVersion.v12);

  SQL-Server:
  m_IDataProvider = new LinqToDB.DataProvider.SqlServer.SqlServerDataProvider(
                              ProviderName.SqlServer,
                              LinqToDB.DataProvider.SqlServer.SqlServerVersion.v2017,
                              LinqToDB.DataProvider.SqlServer.SqlServerProvider.MicrosoftDataSqlClient);

**ConnectionString:**
  Oracle: 
  @"USER ID=UserDummy;CONNECTION TIMEOUT=60;PASSWORD=XXXXXX;DATA SOURCE=PKSABNAHME12;STATEMENT CACHE SIZE=0;CONNECTION LIFETIME=0;INCR POOL SIZE=1;STATEMENT CACHE PURGE=True";
  
  SQL-Server: 
  @"Data Source=MSTEST17\MSTEST17;Initial Catalog=DUMMYDB;Integrated Security=True;Connect Timeout=60;Multiple Active Result Sets=True;Multi Subnet Failover=True;";

**Exception:**
System.InvalidOperationException
  HResult=0x80131509
  Message=There is already an open DataReader associated with this Command which must be closed first.
  Source=Microsoft.Data.SqlClient
  StackTrace:
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.ValidateConnectionForExecute(SqlCommand command)
   at Microsoft.Data.SqlClient.SqlConnection.ValidateConnectionForExecute(String method, SqlCommand command)
   at Microsoft.Data.SqlClient.SqlCommand.ValidateCommand(String method, Boolean async)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at LinqToDB.Data.DataConnection.ExecuteNonQuery(IDbCommand command)
   at LinqToDB.Data.DataConnection.ExecuteNonQuery()
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteNonQueryImpl(DataConnection dataConnection, PreparedQuery preparedQuery)
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteNonQuery()
   at LinqToDB.DataContext.QueryRunner.ExecuteNonQuery()
   at LinqToDB.Linq.QueryRunner.NonQueryQuery(Query query, IDataContext dataContext, Expression expr, Object[] parameters, Object[] preambles)
   at LinqToDB.Linq.QueryRunner.<>c__DisplayClass32_0.<SetNonQueryQuery>b__0(IDataContext db, Expression expr, Object[] ps, Object[] preambles)
   at LinqToDB.Linq.ExpressionQuery`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at LinqToDB.LinqExtensions.Update[TSource,TTarget](IQueryable`1 source, ITable`1 target, Expression`1 setter)

**Comment by Wraith2** [comment]
```csharp
using (DbContext dbContext = new DbContext(dbProvider))
{
	IEnumerable<string> list = dbContext.MENUS_LOG.Select(obj => obj.DATATYPE).Distinct();
	foreach(string strItem in list)
	{
		dbContext.MENUS_LOG
			.Where(objWhere => objWhere.DATATYPE == strItem)
			.Update(dbContext.MENUS_LOG, objWhere => new MENUS_LOG { DATATYPE = strItem + "X" }
		);
	}
}
```
Assuming that DbContext holds a single connection then you are trying to execute an Update while already in the middle of iterating a DataReader. This is expected behaviour, unless you use MARS (and I don't recommend that). If you must do this then create a second connection.

**Comment by cheenamalhotra** [comment]
Hi @BenoitStutz 

I think by ".Net Version 4.6.1" you mean .NET Framework 4.6.1.

Is it possible to test the same with System.Data.SqlClient v4.6.1 to confirm this is an existing behavior or something specific to Microsoft.Data.SqlClient?

**Comment by cheenamalhotra** [comment]
@BenoitStutz 

Do you have an update for this issue?

**Comment by BenoitStutz** [comment]
My solution is to use a second connection
