### ISSUE TITLE
Keyword not supported: 'column encryption setting'

### ISSUE THREAD

**Issue by cypisek77** [dotnet/SqlClient#875]
### Initial Setup
- For SQL Server, Setup Always Encrypted and encrypted 1 column
- While trying to read the data I get an error message that 'Column Encryption Setting' is not supported
- When I remove the column from the data set, and remove the "column encryption setting" from connection string, I have no problem reading the data 
- I have no problem reading the data from SSMS Client using AlwaysEncrypted option

ConnectionStr =  @"Server=servername\inst; Database=DB; Integrated Security=true; Column Encryption Setting=Enabled";

### Software
Microsoft.Data.SqlClient version: (found on the nuget or Microsoft.Data.SqlClient.dll) 4.8.2
.NET target: (Core 5)
SQL Server version: (e.g. SQL Server 2019)
Operating system: (e.g. Windows 2019)

### Exception

System.ArgumentException
  HResult=0x80070057
  Message=Keyword not supported: 'column encryption setting'.
  Source=System.Data.SqlClient
  StackTrace:
   at System.Data.Common.DbConnectionOptions.ParseInternal(Dictionary`2 parsetable, String connectionString, Boolean buildChain, Dictionary`2 synonyms, Boolean firstKey)
   at System.Data.Common.DbConnectionOptions..ctor(String connectionString, Dictionary`2 synonyms)
   at System.Data.SqlClient.SqlConnectionString..ctor(String connectionString)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnectionOptions(String connectionString, DbConnectionOptions previous)
   at System.Data.ProviderBase.DbConnectionFactory.GetConnectionPoolGroup(DbConnectionPoolKey key, DbConnectionPoolGroupOptions poolOptions, DbConnectionOptions& userConnectionOptions)
   at System.Data.SqlClient.SqlConnection.ConnectionString_Set(DbConnectionPoolKey key)
   at System.Data.SqlClient.SqlConnection.set_ConnectionString(String value)
   at System.Data.SqlClient.SqlConnection..ctor(String connectionString)
   at Library.database.SqlServerDb.ExecuteDataAdapater[T](String command) Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()

**Comment by cheenamalhotra** [comment]
Hi @cypisek77 

The version 4.8.2 corresponds to "System.Data.SqlClient" as also captured by your logs.
System.Data.SqlClient in .NET Core doesn't support Always Encrypted.

Please use [Microsoft.Data.SqlClient](https://www.nuget.org/packages/Microsoft.Data.SqlClient) for the same.

**Comment by ErikEJ** [comment]
You are mixing System.Data.SqlClient and Microsoft.Data.SqlClient - not supported

**Comment by cypisek77** [comment]
Thank you, all set. That worked, should have been using that from the start.

**Comment by ammar-ahmed** [comment]
@cypisek77 @ErikEJ @cheenamalhotra  am using .net core 2.2 and i have installed the microsoft.data.sqlclient but still am getting above exception 
![image](https://user-images.githubusercontent.com/15608971/120605301-5617ad80-c467-11eb-8226-4b448680cc00.png)

**Comment by ErikEJ** [comment]
EF Core 2.2 (which is out of support) depends on System.Data.SqlClient

**Comment by ammar-ahmed** [comment]
@ErikEJ does EF Core2.1 supports Always Encrypte on SQL server?

**Comment by ErikEJ** [comment]
Suggest you raise an issue in the EF Core repository, explaining what "not works" actually means, and notice that 2.2 is no longer supported.

**Comment by cheenamalhotra** [comment]
@ammar-ahmed 

As @ErikEJ mentioned "_EF Core 2.2 (which is out of support) depends on System.Data.SqlClient_", System.Data.SqlClient doesn't support Always Encrypted and so does not EF Core 2.2.

Please upgrade to new version of EF Core  to use Microsoft.Data.SqlClient that supports Always Encrypted.
