### ISSUE TITLE
DllNotFoundException: Unable to load DLL 'Microsoft.Data.SqlClient.SNI.x86.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E

### ISSUE THREAD

**Issue by skopparthi** [dotnet/SqlClient#916]
### Describe the bug
Using Microsoft.Data.SQLClient to talk to database in .NetStandard 2.o class library
getting error while opening the connection.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'Microsoft.Data.SqlClient.TdsParser' threw an exception.
  Source=Microsoft.Data.SqlClient
  StackTrace:
   at Microsoft.Data.SqlClient.TdsParser..ctor(Boolean MARS, Boolean fAsynchronous)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, ServerCertificateValidationCallback serverCallback, ClientCertificateRetrievalCallback clientCallback, DbConnectionPool pool, String accessToken, SqlClientOriginalNetworkAddressInfo originalNetworkAddressInfo, Boolean applyTransientFaultHandling)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open()
   at BrokerEngine.Validator.NewBusinessValidator.ValidateCustom(String BondPrefix, String BondNumber, String ProducerCd, String PrincipalStateCD, String ObligeeStateCD, String RiskStateCD) in C:\myProjects\SuretyExpressRepo\SuretyExpress\Development\Current\Assemblies\BrokerEngine\Validator\NewBusinessValidator.cs:line 38
   at BrokerEngine.BrokerTransaction.CreateDataset(String strXML) in C:\myProjects\SuretyExpressRepo\SuretyExpress\Development\Current\Assemblies\BrokerEngine\BrokerTransaction.cs:line 29
   at BrokerPortal.BookNewBusiness(String InPutXML, String RequestType) in C:\myProjects\SuretyExpressRepo\SuretyExpress\Development\Current\WebServiceApplications\SuretyExpressService\App_Code\BrokerPortal\BrokerPortal.vb:line 25

Inner Exception 1:
TypeInitializationException: The type initializer for 'Microsoft.Data.SqlClient.SNILoadHandle' threw an exception.

Inner Exception 2:
DllNotFoundException: Unable to load DLL 'Microsoft.Data.SqlClient.SNI.x86.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

```

### To reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
Console.WriteLine("Hello World!");
```

### Further technical details
Microsoft.Data.SqlClient version: (found on the nuget or Microsoft.Data.SqlClient.dll)
.NET target: (e.g. Framework 4.7.1, Core 2.2.2)
SQL Server version: (e.g. SQL Server 2017)
Operating system: (e.g. Windows 2019, Ubuntu 18.04, macOS 10.13, Docker container)

**Additional context**

**Comment by skopparthi** [comment]
NET target: .NetStandard 2.0
Win 10 OS

**Comment by cheenamalhotra** [comment]
Hi @skopparthi 

You need to fill in information above or provide us a repro app (upload ZIP) that reproduces this error with instructions to reproduce it. Please provide more details.

I only understand you're trying to target .NET Standard 2.0, but what is the nature of your application where this library is consumed? How can we reproduce this error? 
(I'm assuming your application targets .NET Framework from the error)

**Comment by JRahnama** [comment]
Closing this issue for no activity. Feel free to reopen this if you can provide more information please.

**Comment by brandonramosv** [comment]
when I use the Microsoft.Reporting.WebForms library I get the error only when I launch with docker but when I launch it with IIS everything is correct, it seems that a dll is missing in the containers.

the following error is displayed:

Microsoft.Reporting.WebForms.LocalProcessingException: 'An error occurred during local report processing.'
DllNotFoundException: Unable to load DLL 'T2Embed': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

**Comment by JRahnama** [comment]
@brandonramosv can you provide a sample repro or share your application?

**Comment by JRahnama** [comment]
@brandonramosv the mentioned `dll` is not related to `SqlClient` driver. Probably you need to look for the owner of that dll and open the issue there.

**Comment by tanukus** [comment]
> when I use the Microsoft.Reporting.WebForms library I get the error only when I launch with docker but when I launch it with IIS everything is correct, it seems that a dll is missing in the containers.
> 
> the following error is displayed:
> 
> Microsoft.Reporting.WebForms.LocalProcessingException: 'An error occurred during local report processing.' DllNotFoundException: Unable to load DLL 'T2Embed': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

@brandonramosv Are you able to resolve this issue. We have same issue with Windows Server Core 2019 Container image.?
