### ISSUE TITLE
SqlCommand.ExecuteScalarAsync throw System.NullReferenceException

### ISSUE THREAD

**Issue by TingluoHuang** [dotnet/SqlClient#948]
### Describe the bug

`System.NullReferenceException` from `ExecuteScalarAsync`

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Data.SqlClient.SqlCommand.<>c__DisplayClass131_0.<ExecuteScalarAsync>b__0(Task`1 executeTask)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.TeamFoundation.Framework.Server.TeamFoundationSqlResourceComponent.ExecuteCommandAsync(ExecuteType executeType, CommandBehavior behavior, String performanceGroupName) in D:\a\1\s\Vssf\Sdk\Server\Components\TeamFoundationSqlResourceComponent.Async.cs:line 409
   at Microsoft.TeamFoundation.Framework.Server.TeamFoundationSqlResourceComponent.ExecuteCommandAsync(ExecuteType executeType, CommandBehavior behavior, String performanceGroupName) in D:\a\1\s\Vssf\Sdk\Server\Components\TeamFoundationSqlResourceComponent.Async.cs:line 514
   at Microsoft.VisualStudio.Services.CircuitBreaker.CommandAsync.ExecuteAsync(Func`1 run, Func`1 fallback) in D:\a\1\s\Vssf\Client\Common\CircuitBreaker\Command.cs:line 303
   at Microsoft.VisualStudio.Services.CircuitBreaker.CommandAsync.ExecuteAsync(Func`1 run, Func`1 fallback) in D:\a\1\s\Vssf\Client\Common\CircuitBreaker\Command.cs:line 303
   at Microsoft.TeamFoundation.Framework.Server.DatabaseCircuitBreaker.ExecuteCommandWithBaseCircuitBreakerAsync(ExecuteType executeType, CommandBehavior behavior, String performanceGroupName) in D:\a\1\s\Vssf\Sdk\Server\Components\DatabaseCircuitBreaker.cs:line 120
   at Microsoft.TeamFoundation.Framework.Server.DatabaseCircuitBreaker.ExecuteCommandWithComponentCircuitBreakerAsync(ExecuteType executeType, CommandBehavior behavior, String performanceGroupName) in D:\a\1\s\Vssf\Sdk\Server\Components\DatabaseCircuitBreaker.cs:line 90
   at Microsoft.TeamFoundation.Framework.Server.TeamFoundationSqlResourceComponent.ExecuteScalarAsync[T]() in D:\a\1\s\Vssf\Sdk\Server\Components\TeamFoundationSqlResourceComponent.Async.cs:line 658
   at Microsoft.TeamFoundation.Framework.Server.MessageQueueComponent.EnqueueMessageAsync(String queueName, String messageType, String message) in D:\a\1\s\Vssf\Sdk\Server\Components\MessageQueueComponent.cs:line 122
   at Microsoft.TeamFoundation.Framework.Server.TeamFoundationMessageQueueService.EnqueueMessageAsync(IVssRequestContext requestContext, String queueName, String messageType, String message) in D:\a\1\s\Vssf\Sdk\Server\MessageQueue\TeamFoundationMessageQueueService.cs:line 658
   at Microsoft.TeamFoundation.Framework.Server.TeamFoundationMessageQueueService.EnqueueMessageAsync(IVssRequestContext requestContext, String queueName, String messageType, String message) in D:\a\1\s\Vssf\Sdk\Server\MessageQueue\TeamFoundationMessageQueueService.cs:line 658
   at Microsoft.TeamFoundation.DistributedTask.Server.DistributedTaskResourceService.SendMessageToAgentAsync(IVssRequestContext requestContext, Int32 agentId, TaskAgentMessage message) in D:\a\1\s\Actions\Runtime\Service\Server\DistributedTaskResourceService.cs:line 3433
   at Microsoft.TeamFoundation.DistributedTask.Server.DistributedTaskResourceService.SendJobMessageToAgentAsync(IVssRequestContext requestContext, Int64 requestId, TaskAgentMessage message) in D:\a\1\s\Actions\Runtime\Service\Server\DistributedTaskResourceService.cs:line 1650
   at Microsoft.TeamFoundation.DistributedTask.Server.Controllers.TaskAgentMessagesController.SendMessageAsync(Int32 poolId, Int64 requestId, TaskAgentMessage message) in D:\a\1\s\Actions\Runtime\Service\Server\Controllers\TaskAgentMessagesController.cs:line 52
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

### To reproduce

I don't have a repro, since the error is found in our production telemetry.

### Further technical details
Microsoft.Data.SqlClient version: 2.1.1
.NET target: dotnet core SDK 3.1.406
SQL Server version: SQL Azure
Operating system: Windows

**Additional context**

**Comment by cheenamalhotra** [comment]
Hi @TingluoHuang 

It will be very difficult to find the exact spot at where Null Reference is found without a repro.
Please provide any helpful information to reproduce or event source traces ([Doc: Enable Event Tracing](https://docs.microsoft.com/en-us/sql/connect/ado-net/enable-eventsource-tracing?view=sql-server-ver15)) if possible.

**Comment by TingluoHuang** [comment]
@cheenamalhotra this has only happened few times in our production environment and I am afraid that I can't turn on any trace in prod. 😢

**Comment by SimonCropp** [comment]
@TingluoHuang if you could deploy pdbs for System.Data.SqlClient, the next time the exception happens we should get line numbers

**Comment by David-Engel** [comment]
Closing as stale/not repro.
