### ISSUE TITLE
AspNetCore AddHealthChecks().AddDbContextCheck eventually fails with leaked sqlconnections

### ISSUE THREAD

**Issue by mRowlinson27** [dotnet/SqlClient#987]
### Describe the bug
We have an AspNetCore service which has two different EF core dbcontext health checks on a health endpoint that is called by kubernetes every 10 seconds. Occasionally the health check spontaneously hangs (in this case after 10ish hours) and every subsequent health check on that service will hang as well. The actual endpoints of the service resolve dbcontexts just fine; I was able to make successful requests to the db through the service, it is just the health checks that have hung requests.

Because our kubernetes health check cancels the call after 3 seconds, this exception occurs:
```
Connection id "0HM760H8C8RIB", Request id "0HM760H8C8RIB:00000001": An unhandled exception was thrown by the application.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.<>c__DisplayClass20_0.<<ExistsAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.<>c__DisplayClass20_0.<<ExistsAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
   at Microsoft.Extensions.Diagnostics.HealthChecks.DbContextHealthCheck`1.CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken)
   at Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService.RunCheckAsync(IServiceScope scope, HealthCheckRegistration registration, CancellationToken cancellationToken)
   at Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService.CheckHealthAsync(Func`2 predicate, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Diagnostics.HealthChecks.HealthCheckMiddleware.InvokeAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

Not sure if this is the right spot for the issue, but the dumped threads seem to indicate it was stuck in sqlclient, and the EF code looks like it does a new SqlConnection().Open where it was cancelled.

I took a dump of the issue and found that there is a leak that occurs every time a health check runs from now on. Here is an object count comparison from two dumped heaps taken an hour apart of a few types that looked notable:

Heap1:
```
Count    TotalSize Class Name
12957       621936 Microsoft.Data.ProviderBase.DbConnectionPool+PendingGetConnection
12993       935496 System.Threading.Tasks.Task`1[[Microsoft.Data.ProviderBase.DbConnectionInternal, Microsoft.Data.SqlClient]]
13864      1109120 System.Threading.Tasks.Task+ContingentProperties
12998      2495616 Microsoft.Data.SqlClient.SqlConnection
12998      2703584 Microsoft.Data.SqlClient.SqlStatistics
```

Heap2:
```
Count    TotalSize Class Name
13980       671040 Microsoft.Data.ProviderBase.DbConnectionPool+PendingGetConnection
14003      1008216 System.Threading.Tasks.Task`1[[Microsoft.Data.ProviderBase.DbConnectionInternal, Microsoft.Data.SqlClient]]
14544      1163520 System.Threading.Tasks.Task+ContingentProperties
14007      2689344 Microsoft.Data.SqlClient.SqlConnection
14007      2913456 Microsoft.Data.SqlClient.SqlStatistics
```

I also manually pinged the health check of the unhealthy service. It did not return a response even after I left it open 1.5 hours. I took a dump during this connection and found a thread which seemed relevant, it was not present on any of the control service dumps I took for comparison but that could be coincidence:

```
b794
    1 (dynamicClass).IL_STUB_PInvoke(SafeHandle, MessageHeader*, SocketFlags, Int64*)
    1 System.Net.Sockets.SocketPal.Receive(SafeSocketHandle, SocketFlags, Span<Byte>, Byte[], Int32 ByRef, SocketFlags ByRef, Error ByRef)
    1 System.Net.Sockets.SocketPal.TryCompleteReceiveFrom(SafeSocketHandle, Span<Byte>, IList<ArraySegment<Byte>>, SocketFlags, Byte[], Int32 ByRef, Int32 ByRef, SocketFlags ByRef, SocketError ByRef)
    1 System.Net.Sockets.SocketAsyncContext.ReceiveFrom(Memory<Byte>, SocketFlags ByRef, Byte[], Int32 ByRef, Int32, Int32 ByRef)
    1 System.Net.Sockets.SocketPal.Receive(SafeSocketHandle, Byte[], Int32, Int32, SocketFlags, Int32 ByRef)
    1 System.Net.Sockets.Socket.Receive(Byte[], Int32, Int32, SocketFlags, SocketError ByRef)
    1 System.Net.Sockets.NetworkStream.Read(Byte[], Int32, Int32)
    1 Microsoft.Data.SqlClient.SNI.SslOverTdsStream+<ReadInternal>d__11.MoveNext()
    1 System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start(<ReadInternal>d__11 ByRef)
    1 Microsoft.Data.SqlClient.SNI.SslOverTdsStream.ReadInternal(Byte[], Int32, Int32, CancellationToken, Boolean)
    1 Microsoft.Data.SqlClient.SNI.SslOverTdsStream.Read(Byte[], Int32, Int32)
    1 System.Net.FixedSizeReader.ReadPacket(Stream, Byte[], Int32, Int32)
    1 System.Net.Security.SslStream.StartReceiveBlob(Byte[], AsyncProtocolRequest)
    1 System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken, AsyncProtocolRequest)
    1 System.Net.Security.SslStream.StartSendBlob(Byte[], Int32, AsyncProtocolRequest)
    1 System.Net.Security.SslStream.ForceAuthentication(Boolean, Byte[], AsyncProtocolRequest)
    1 System.Net.Security.SslStream.ProcessAuthentication(LazyAsyncResult, CancellationToken)
    1 System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions)
    1 Microsoft.Data.SqlClient.SNI.SNITCPHandle.EnableSsl(UInt32)
    1 Microsoft.Data.SqlClient.SNI.SNIProxy.EnableSsl(SNIHandle, UInt32)
    1 Microsoft.Data.SqlClient.TdsParser.ConsumePreLoginHandshake(Boolean, Boolean, Boolean, Boolean ByRef, Boolean ByRef)
    1 Microsoft.Data.SqlClient.TdsParser.Connect(ServerInfo, SqlInternalConnectionTds, Boolean, Int64, Boolean, Boolean, Boolean, Boolean, SqlAuthenticationMethod, SqlAuthenticationProviderManager)
    1 Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo, String, SecureString, Boolean, TimeoutTimer, Boolean)
    1 Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo, String, SecureString, Boolean, SqlConnectionString, SqlCredential, TimeoutTimer)
    1 Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer, SqlConnectionString, SqlCredential, String, SecureString, Boolean)
    1 Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity, SqlConnectionString, SqlCredential, Object, String, SecureString, Boolean, SqlConnectionString, SessionData, Boolean, String, DbConnectionPool, SqlAuthenticationProviderManager)
    1 Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions, DbConnectionPoolKey, Object, DbConnectionPool, DbConnection, DbConnectionOptions)
    1 Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool, DbConnection, DbConnectionOptions, DbConnectionPoolKey, DbConnectionOptions)
    1 Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection, DbConnectionOptions, DbConnectionInternal)
    1 Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection, DbConnectionOptions, DbConnectionInternal)
    1 Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection, UInt32, Boolean, Boolean, DbConnectionOptions, DbConnectionInternal ByRef)
    1 Microsoft.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
    1 System.Threading.ExecutionContext.RunInternal(ExecutionContext, ContextCallback, Object)
```

### To reproduce
Not entirely sure, other then to let the service run for a long time. This particular service is the only one we have seen this issue for, and we have seen it at least twice so far. AFAIK it is the only service that has two different dbcontexts for its health check setup so I assume it is something to do with that. Here is the health check setup code we have:

```
public static int Main(string[] args)
        {
            try
            {
                Log.Information("Starting web host");
                CreateHostBuilder(args).Build().Run();
                return 0;
            }
            catch (Exception ex)
            {
                Log.Fatal(ex, "Host terminated unexpectedly");
                Console.WriteLine("Host terminated unexpectedly");
                Console.WriteLine(ex);
                return 1;
            }
            finally
            {
                Log.CloseAndFlush();
            }
        }

 public static IHostBuilder CreateHostBuilder(string[] args)
        {
            Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Debug()
                .MinimumLevel.Override("Microsoft", LogEventLevel.Information)
                .Enrich.FromLogContext()
                .WriteTo.Console()
                .CreateLogger();
            return Host.CreateDefaultBuilder(args)
                .UseSerilog()
                .ConfigureWebHostDefaults(
                webBuilder => { webBuilder.UseStartup<Startup>().ConfigureKestrel(options => { options.AddServerHeader = false; }); });
}
```

```
 services.AddDbContextPool<DbContext1>(
                options => options.UseSqlServer(
                    dbContext1ConnectionString, 
                    opts => opts.EnableRetryOnFailure(100, TimeSpan.FromSeconds(5), null)));

 services.AddDbContextPool<DbContext2>(
                options => options.UseSqlServer(
                    dbContext1ConnectionString, 
                    opts => opts.EnableRetryOnFailure(100, TimeSpan.FromSeconds(5), null)));

services.AddHealthChecks().AddDbContextCheck<DbContext1>().AddDbContextCheck<DbContext2>()
                .AddUrlGroup(setup => { setup.AddUri(new Uri("http://www.msftncsi.com/ncsi.txt")); });
```
```
app.UseHealthChecks("/health");
```

### Expected behavior
Health checks to not spontaneously stop working.

### Further technical details
Microsoft.Data.SqlClient version: 1.13.20136.2
.NET target: Microsoft.NETCore.App/3.1.13
Operating system: ( Docker container, aspnet:3.1-alpine)

**Comment by Wraith2** [comment]
Is it possible for you to update to https://github.com/dotnet/SqlClient/blob/main/release-notes/1.1/1.1.4.md and see if that helps? There are specific fixes in that release around cancellation and that may be involved here.
Otherwise it looks like the connection has been or is being established but that the opening of the socket never times out, that's why the stack ends up in the pinvoke stub to the os, it's still doing a read, no idea why though.

**Comment by mRowlinson27** [comment]
Thanks for the speedy reply. Have upgraded to 1.1.4 and will see if the issue reproduces itself again. If it does, is there any data I can collect that would help diagnose the issue?

**Comment by cheenamalhotra** [comment]
Hi @mRowlinson27 

What is your connection string like? And are you passing any access token to the driver that may not be getting renewed when it expires and same token is used by driver over and over again?

10ish hours makes me remind of similar story where access tokens are re-validated by Azure every 10 hours but let's determine if that's the case first.

**Comment by mRowlinson27** [comment]
Both connection strings are basically just "Data Source=datasource;Initial Catalog=dbname;Integrated Security=False;User ID=userId;Password=password;MultipleActiveResultSets=False". So pretty simple stuff there. We are using azure to host the db though, so maybe that uses Azure tokens under the hood? I'm afraid I don't know too much about that, As far as I know it is just user password auth.

Also in case it wasn't clear, the service doesn't die the moment it hits 10 hours or anything quite so drastic. With about 9 instances service running over the past few months we have only noticed a couple of times that one of the instances will get into this bad state.

**Comment by cheenamalhotra** [comment]
If it's non-AD authentication mode, access token is not involved.
Let us know if you still see issues with latest v1.1.4.

If you still do, please try to upgrade your app in development environment to use [Microsoft.Data.SqlClient v2.1.2](https://www.nuget.org/packages/Microsoft.Data.SqlClient/2.1.2) in order to collect traces. And you will be able to capture [Event Source traces](https://docs.microsoft.com/en-us/sql/connect/ado-net/enable-eventsource-tracing?view=sql-server-ver15) for your application.

**Comment by cheenamalhotra** [comment]
Hi @mRowlinson27 

Do you have any update on this issue?
